### ISSUE TITLE
[DEVEL] high severity vulnerability: @openzeppelin/contracts <=4.9.2

### ISSUE THREAD

**Issue by 0xViva** [smartcontractkit/chainlink#10514]
**Description**
I'm using some of the code found in @chainlink/contracts, and this is bringing in a warning about @chainlink/contracts depending on vulnerable versions of @openzeppelin/contracts with severity level "high" into my project's dev dependencies. Will this be patched?

**Your Environment**
Windows 10, npm installed into a empty project folder just to display the message. 

**Basic Information**

![bilde](https://github.com/smartcontractkit/chainlink/assets/16744145/f7a876ac-37e0-473e-ac6c-182d9f30db58)

**Steps to Reproduce**
npm install @chainlink/contracts --save to any folder, then npm audit while being in that folder.

**Comment by QingyangKong** [comment]
Thanks for raising it. We are investigating the issue.

**Comment by QingyangKong** [comment]
Hi @0xViva,  We have been able to confirm that while some dependencies pulled into this project have vulnerabilities associated with them, however, none of the @chainlink/contracts are impacted by these vulnerabilities. 

The majority of vulnerable dependencies are only used by legacy contracts, and thus are still included in the package.json file. That being said, we are working on a [change](https://github.com/smartcontractkit/chainlink/pull/10887) to bump the version of the @openzeppelin/contracts and @openzeppelin/contracts-upgradeable package to the latest version, which should address these warnings.

**Comment by 0xViva** [comment]
> Hi @0xViva, We have been able to confirm that while some dependencies pulled into this project have vulnerabilities associated with them, however, none of the @chainlink/contracts are impacted by these vulnerabilities.
> 
> The majority of vulnerable dependencies are only used by legacy contracts, and thus are still included in the package.json file. That being said, we are working on a [change](https://github.com/smartcontractkit/chainlink/pull/10887) to bump the version of the @openzeppelin/contracts and @openzeppelin/contracts-upgradeable package to the latest version, which should address these warnings.

Good to know none of your contracts are impacted by these vulnerabilites but also great that the warnings will be addressed so I don't have to be worried anymore when installing my projects. Thanks for letting me know!

**Comment by QingyangKong** [comment]
Fix has been merged
