### ISSUE TITLE
Virtual _ccipReceive method to be implemented takes message argument located in memory and not calldata

### ISSUE THREAD

**Issue by FredCoen** [smartcontractkit/chainlink#10858]
Is there a reason why _ccipReceive takes the message input arg in memory and not calldata? This makes it not possible to slice it up in the implementation.

```
/// @inheritdoc IAny2EVMMessageReceiver
  function ccipReceive(Client.Any2EVMMessage calldata message) external virtual override onlyRouter {
    _ccipReceive(message);
  }

  /// @notice Override this function in your implementation.
  /// @param message Any2EVMMessage
  function _ccipReceive(Client.Any2EVMMessage memory message) internal virtual;
```
  ```

**Comment by Bellamalwa** [comment]
The decision to use memory for the message input argument in _ccipReceive is made to ensure that the data can be modified within the function. 
When using calldata, the data is immutable, and any attempt to modify it would result in a compilation error.

**Comment by RensR** [comment]
ccipReceive is also virtual, so if you need a calldata version, simply override that function
