### ISSUE TITLE
[SMRT] Duplicate IERC677Receiver interfaces

### ISSUE THREAD

**Issue by CodeSandwich** [smartcontractkit/chainlink#11226]
**Description**
There are 2 copies of `IERC677Receiver` among v0.8 contracts: one under [shared/token/ERC677](https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/shared/token/ERC677/IERC677Receiver.sol) and another one under [shared/interfaces](https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/shared/interfaces/IERC677Receiver.sol).

**Basic Information**
This will cause problems, because for Solidity these are 2 unrelated, incompatible interfaces. Please consider removing one of them and migrating fully to the other one.

**Steps to Reproduce**
Don't.

**Additional Information**
No.

**Comment by RensR** [comment]
fixed in #11227
