### ISSUE TITLE
[NODE] Chainlink install from source code will not work on Ubuntu 22.04

### ISSUE THREAD

**Issue by WilsonBillkia** [smartcontractkit/chainlink#11740]
**Description**
The Gnu Makefile is not working when used by ansible / automated. Chainlink builds fine from bash interactively on the same system with the  same global environment variables.  The error is 'go not found' But the correct version is in place and the PATH works.

**Basic Information**

- Network: goerli
- Blockchain Client: geth
- Go Version: v1.21.5
- Operating System: Ubuntu Server 22.04
- Commit: ?
- Hosting Provider: self-hosted
- Startup Command: make install (building chainlink from source)

**Environment Variables**
SHELL=/bin/bash
PWD=/home/john/go/bin
LOGNAME=john
HOME=/home/john
LANG=C.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:.tar=01;31:.tgz=01;31:.arc=01;31:.arj=01;31:.taz=01;31:.lha=01;31:.lz4=01;31:.lzh=01;31:.lzma=01;31:.tlz=01;31:.txz=01;31:.tzo=01;31:.t7z=01;31:.zip=01;31:.z=01;31:.dz=01;31:.gz=01;31:.lrz=01;31:.lz=01;31:.lzo=01;31:.xz=01;31:.zst=01;31:.tzst=01;31:.bz2=01;31:.bz=01;31:.tbz=01;31:.tbz2=01;31:.tz=01;31:.deb=01;31:.rpm=01;31:.jar=01;31:.war=01;31:.ear=01;31:.sar=01;31:.rar=01;31:.alz=01;31:.ace=01;31:.zoo=01;31:.cpio=01;31:.7z=01;31:.rz=01;31:.cab=01;31:.wim=01;31:.swm=01;31:.dwm=01;31:.esd=01;31:.jpg=01;35:.jpeg=01;35:.mjpg=01;35:.mjpeg=01;35:.gif=01;35:.bmp=01;35:.pbm=01;35:.pgm=01;35:.ppm=01;35:.tga=01;35:.xbm=01;35:.xpm=01;35:.tif=01;35:.tiff=01;35:.png=01;35:.svg=01;35:.svgz=01;35:.mng=01;35:.pcx=01;35:.mov=01;35:.mpg=01;35:.mpeg=01;35:.m2v=01;35:.mkv=01;35:.webm=01;35:.webp=01;35:.ogm=01;35:.mp4=01;35:.m4v=01;35:.mp4v=01;35:.vob=01;35:.qt=01;35:.nuv=01;35:.wmv=01;35:.asf=01;35:.rm=01;35:.rmvb=01;35:.flc=01;35:.avi=01;35:.fli=01;35:.flv=01;35:.gl=01;35:.dl=01;35:.xcf=01;35:.xwd=01;35:.yuv=01;35:.cgm=01;35:.emf=01;35:.ogv=01;35:.ogx=01;35:.aac=00;36:.au=00;36:.flac=00;36:.m4a=00;36:.mid=00;36:.midi=00;36:.mka=00;36:.mp3=00;36:.mpc=00;36:.ogg=00;36:.ra=00;36:.wav=00;36:.oga=00;36:.opus=00;36:.spx=00;36:.xspf=00;36:
SSH_CONNECTION=192.168.1.109 59112 192.168.1.235 22
LESSCLOSE=/usr/bin/lesspipe %s %s
TERM=xterm-256color
LESSOPEN=| /usr/bin/lesspipe %s
USER=john
SHLVL=1
SSH_CLIENT=192.168.1.109 59112 22
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/home/john/go/bin:/usr/local/bin/node-v16.14.2-linux-x64/bin
MAIL=/var/mail/john
SSH_TTY=/dev/pts/0
_=/usr/bin/env
OLDPWD=/home/john/chainlink

**Steps to Reproduce**
Not a trivial effort - You can reproduce this with the repo here https://github.com/WilsonBillkia/bane. TBH reproducing is alot of effort. The hope is to identify issue with a minor debug of the makefile and associated config files that chainlink source code uses to build?

**Additional Information**
I think the chainlink code is the issue because I have already fixed the path (global env variables were incorrect for a while) 
I saw the version of go in  shell.nix that comes with chainlink is set to 1.19. This looks like a bug? I changed it to 1.21 but same error.

**Comment by cecuabin** [comment]
Tuv.-R^3/rad arcos270º = Fuv . mf /dt3 +-Hvu^-2dmt^-nA^logN^(n-3) // - G@(21334321!34556) . sv Gngcº91!216594832 ...*.dmb
apo)m =(FfR)d"cI" . se^2epid2t2,1.12^2/3 + k5uvsh /-grr + FR . cs (SOkadtm) + intv ^3 drSMmn*.rsc
mvt . At^2/ ic + KPR sh-R^2^1/2 = dd723^-4/3 r^8 / Gc . drT^ds1t2s2 SO3PM*.int
Lim Eo-Eodt = 2/3 shch/ I^2*.lk
v/s^5 = ac^1/2 . E^2/1cc*.zip
g4.5 = bst^3 / 2 - dts^-1/2 +c^2Fuv
gmu + av = FR^-2/1 + OHCdrr
Dz(4)334(k) = (SO) . YM^2oOpi543234
V^2 = Ceff -drs^1/2 /dttpp (FR^e+)
mu / M^2o = dsz(4) . FR^1/2^2213
K(a)To = 2pxvo . 3vt2 / AHebb^-7/2*
gu^2(vo) / N2^-37/1 = sGv^-98/1

**Comment by WilsonBillkia** [comment]
???

**Comment by cecuabin** [comment]
> ???

Mu^drt2/to-dt1s' = 3.134gak1v . at^2
8/2ab^b'c|ax| / qt3E(pn) . Thd( = QoV
1/2TcsGv(KN) . V(He) / Od(CO2) . Od(He) = g08ru'imy^-eish/at^2
Oc|mx| = ad^2 || MGg·Kfu/^(-e^2).+eK.piu'
Kt(a) . dgid(ntciby) = ucvg /e.(d^2)gv(a)
Ort . g01pi = chmg'p|y| / (x)out
Kpc(a) = 10/4 Ecv / 4/2 Ecb
C(n+1)^(e-e+)^2 = At1^2/-(D(n+1)ts)^2

**Comment by WilsonBillkia** [comment]
Terrific, Chainlink. Thanks.

**Comment by WilsonBillkia** [comment]
Update: This is a bug with ansible that has now been fixed with a workaround.

**Comment by WilsonBillkia** [comment]
closed - this is an ansible bug. Workaround is to apply the PATH directly to the ansible play for make install.
