### ISSUE TITLE
Upgrade contracts to solc v0.5.x

### ISSUE THREAD

**Issue by alsco77** [smartcontractkit/chainlink#1251]
## Description

Upgrade Solidity contracts to solc v 0.5.x, in order to keep up to date and patch a number of small security problems discovered recently. See [breaking changes](https://solidity.readthedocs.io/en/v0.5.0/050-breaking-changes.html) 

Why do I want this? Upgrading will allow us to continue developing/compiling our Chainlink oracle contracts in 0.5.x, keeping in line with the rest of our system, reducing development overhead and minimising error risk.

**Comment by thodges-gh** [comment]
Thanks @alsco77! We're looking into this.

**Comment by ejwessel** [comment]
@thodges-gh anything to share with regards to this update since last comment? I'm pretty excited for this upgrade.

**Comment by bneiluj** [comment]
I've been working on Upgrading Chainlink Solidity contracts to solc v 0.5.2 in our Prediction market project. 
<img width="1368" alt="Screenshot 2019-08-08 at 12 30 02" src="https://user-images.githubusercontent.com/3680497/62696368-8e1f4800-b9d8-11e9-8e00-4b9d364dcfc1.png">
Is there any official Chainlink ETA for upgrading contracts to solc v0.5.x?

**Comment by thodges-gh** [comment]
We had just recently merged in https://github.com/smartcontractkit/chainlink/pull/1521, which is currently in the develop branch.

**Comment by kseniya292** [comment]
@thodges-gh When will this be merged into master?

**Comment by thodges-gh** [comment]
@kseniya292 It's in master now, yes. One important step is you can access the v0.5 contracts in the [Chainlink NPM package](https://www.npmjs.com/package/chainlink) already. I'll close this issue when our Box is converted over to Solidity 5. In the mean time, I've made [this repo](https://github.com/thodges-gh/chainlink-solidity-5) which uses the Solidity 5 contracts by default.

**Comment by kseniya292** [comment]
@thodges-gh ah, thank you!

**Comment by bneiluj** [comment]
dope 🔥

**Comment by leovigna** [comment]
I think I may have done a good amount to upgrade the `Oracle.sol` contract. Let me know of your thoughts. I made it compatible with the OpenZeppelin Proxy architecture. I had to debug the event logging process which was causing issues due to padding and how Chainlink nodes parse the data.

https://github.com/leovigna/upgradeable-oracle
