### ISSUE TITLE
bad status when running chainlink node

### ISSUE THREAD

**Issue by sylvainlecoy** [smartcontractkit/chainlink#127]
Hi there,

I am on MacOS High Sierra 10.13.3 with Go 1.10 (last version from today)

I successfully installed the required dependencies and make install the node;

Unfortunately I could not locate the executable so I manually ran the main.go file.

Here is the fatal error I got:

EtherBook:chainlink sylvain$ go run main.go node
{"level":"info","ts":1520104145.9259455,"caller":"logger/logger.go:71","msg":"Starting Chainlink Node 0.2.0 at commit unset"}
{"level":"fatal","ts":1520104145.932296,"caller":"logger/logger.go:119","msg":"bad status","stacktrace":"github.com/smartcontractkit/chainlink/logger.Fatal\n\t/usr/local/go/bin/src/github.com/smartcontractkit/chainlink/logger/logger.go:119\ngithub.com/smartcontractkit/chainlink/store.NewStore\n\t/usr/local/go/bin/src/github.com/smartcontractkit/chainlink/store/store.go:41\ngithub.com/smartcontractkit/chainlink/services.NewApplication\n\t/usr/local/go/bin/src/github.com/smartcontractkit/chainlink/services/application.go:31\ngithub.com/smartcontractkit/chainlink/cmd.ChainlinkAppFactory.NewApplication\n\t/usr/local/go/bin/src/github.com/smartcontractkit/chainlink/cmd/client.go:121\ngithub.com/smartcontractkit/chainlink/cmd.(*Client).RunNode\n\t/usr/local/go/bin/src/github.com/smartcontractkit/chainlink/cmd/client.go:37\ngithub.com/smartcontractkit/chainlink/cmd.(*Client).RunNode-fm\n\t/usr/local/go/bin/src/github.com/smartcontractkit/chainlink/main.go:46\ngithub.com/smartcontractkit/chainlink/vendor/github.com/urfave/cli.HandleAction\n\t/usr/local/go/bin/src/github.com/smartcontractkit/chainlink/vendor/github.com/urfave/cli/app.go:490\ngithub.com/smartcontractkit/chainlink/vendor/github.com/urfave/cli.Command.Run\n\t/usr/local/go/bin/src/github.com/smartcontractkit/chainlink/vendor/github.com/urfave/cli/command.go:210\ngithub.com/smartcontractkit/chainlink/vendor/github.com/urfave/cli.(*App).Run\n\t/usr/local/go/bin/src/github.com/smartcontractkit/chainlink/vendor/github.com/urfave/cli/app.go:255\nmain.Run\n\t/usr/local/go/bin/src/github.com/smartcontractkit/chainlink/main.go:61\nmain.main\n\t/usr/local/go/bin/src/github.com/smartcontractkit/chainlink/main.go:12\nruntime.main\n\t/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:198"}
exit status 1

**Comment by thodges-gh** [comment]
Hi @sylvainlecoy, do you have an Ethereum client running with an open websocket connection saved to the `ETH_URL` environment variable?

**Comment by sylvainlecoy** [comment]
I have an ethereum client running (parity --light) but no ETH_URL and I don't know for websocket, how do I configure that ?

**Comment by sylvainlecoy** [comment]
Is there a support channel like discord to discuss this or you are all on slack ?

**Comment by thodges-gh** [comment]
We are on Slack and Gitter. For local development, I would suggest looking at using our included Devnet image. We have instructions on how to use that [here](https://github.com/smartcontractkit/chainlink/wiki/Development-Tips#devnetcldev). We actually use Parity in that Docker image, so that config file will probably be useful to you for running Parity locally yourself.

**Comment by thodges-gh** [comment]
Also the "Starting Chainlink Node 0.2.0 at commit unset" message is a little worrying to me. That "unset" should be a hash of your store, which would be created even before attempting to connect to an Ethereum instance. Can you see if anything exists in your `~/.chainlink` directory?

**Comment by sylvainlecoy** [comment]
Yes exactly, I could not locate the chainlink binary on MacOS, so I ran the main.go node directly.

Where is the output ?

**Comment by sylvainlecoy** [comment]
BTW I tried to install on a Debian 9, but failed so that's why I switched on my Mac buti'm not used to development on OSX...

**Comment by thodges-gh** [comment]
Issue was with Go's paths in local environment.
