### ISSUE TITLE
[FEAT] hard-pinned versioning makes for poor libraries

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/chainlink#13615]
**Description**
Right now, there are several smart contracts with strict versioning types, [for example](https://github.com/smartcontractkit/chainlink/blob/b0a48d6951ca408e3f2a08eafcd22ef07100644e/contracts/src/v0.8/vrf/dev/SubscriptionAPI.sol#L2) in the VRF `SubscriptionAPI`:

```javascript
pragma solidity 0.8.19;
```

This is an issue because it's the way the [documentation instructs users interface with VRF](https://docs.chain.link/vrf/v2-5/subscription/get-a-random-number#analyzing-the-contract) however, it means that all smart contracts that interact with Chainlink VRF _must_ use solidity version `0.8.19`.  This of course is very restrictive for developers. 

**The Request**
Please _always_ make smart contracts intended to be used as libraries with loose solidity versioning, for example `^0.8.19`, otherwise people with different solidity versions will have a harder time working with these packages.

**Comment by rishabhRsinghvi** [comment]
@PatrickAlphaC I can do this, please assign it to me, and I think this could be labelled as Good First Issue.

**Comment by rishabhRsinghvi** [comment]
#14824 

I have solved this one.

**Comment by RensR** [comment]
This has been resolved in https://github.com/smartcontractkit/chainlink/pull/13600

We agree that client facing contracts should not have strict versioning.
