### ISSUE TITLE
add job creation command to CLI

### ISSUE THREAD

**Issue by se3000** [smartcontractkit/chainlink#140]
`chainlink create {...}` should create a new job spec with the parameters passed in

**Comment by whatsadebugger** [comment]
I'm interested in taking this one on. I did some looking at urfave/cli

**Comment by se3000** [comment]
@whatsadebugger Excellent! I think it would make sense to pass in JSON directly or to pass in the path to a file that contains the JSON. Open to other suggestions too, but feel free to tackle whichever you prefer.

**Comment by Jeiwan** [comment]
I can take that one too. @whatsadebugger Let me know, please, if you decide to not do it.

**Comment by whatsadebugger** [comment]
I have started this one as of yesterday.

**Comment by se3000** [comment]
Closed by #150.

Thanks @whatsadebugger!

**Comment by whatsadebugger** [comment]
no problem!
