### ISSUE TITLE
Gethnet account unlock with HTTP forbidden

### ISSUE THREAD

**Issue by tylerferrara** [smartcontractkit/chainlink#1494]
Geth no longer allows an account to be unlocked through http (https://github.com/ethereum/go-ethereum/pull/17037) unless `--allow-insecure-unlock` flag is set.

### Error
`Fatal: Account unlock with HTTP access is forbidden!`

### System Information

- Network (Main net, Ropsten, etc.): Ropsten
- Ethereum client (Geth/Parity) and version: 1.9.0-stable
- Go version: 1.12.7
- Host OS: OSX
- Commit (INFO line when starting the node): 

### Environment Variables

LOG_LEVEL                    Default: "info"
ROOT                         Default: "~/.chainlink"
CHAINLINK_PORT               Default: "6688"
GUI_PORT                     Default: "6689"
USERNAME                     Default: "chainlink"
PASSWORD                     Default: "twochains"
ETH_URL                      Default: "ws://localhost:8546"
ETH_CHAIN_ID                 Default: "0"
CLIENT_NODE_URL              Default: "http://localhost:6688"
MIN_INCOMING_CONFIRMATIONS   Default: "0"
MIN_OUTGOING_CONFIRMATIONS   Default: "12"
ETH_GAS_BUMP_THRESHOLD       Default: "12"
ETH_GAS_BUMP_WEI             Default: "5000000000"
ETH_GAS_PRICE_DEFAULT        Default: "20000000000"
LINK_CONTRACT_ADDRESS        Default: "0x514910771AF9Ca656af840dff83E8264EcF986CA"
MINIMUM_CONTRACT_PAYMENT     Default: "1000000000000000000"
ORACLE_CONTRACT_ADDRESS      Default: ""
DATABASE_POLL_INTERVAL       Default: "500ms"

**Comment by se3000** [comment]
When are you seeing this error? The Chainlink node manages its own keys. Are you using our `devnet` or `gethnet` commands?

**Comment by tylerferrara** [comment]
This is only for gethnet due to the latest version of geth. I am working to upgrade go-ethereum #1500 and add the required flag.

**Comment by se3000** [comment]
Closing this. Thanks again for the PR @tylerferrara!
