### ISSUE TITLE
[DEVEL]  VRFCoordinatorV2_5Mock not returning random values, always deterministic

### ISSUE THREAD

**Issue by REPTILEHAUS** [smartcontractkit/chainlink#15298]
**Description**
I have a contract which after the last ticket is bought a VRF call is made, and then random words returned. The whole flow works as expected however the values are not random and are deterministic on every single test. I am expecting a different word from the mock coordinator each time it is called, or at least that was my assumption

**Your Environment**
OSX using hardhat 

**Basic Information**
locally using hardhat to deploy VRFCoordinatorV2_5Mock and interacting with it via my own smart contract

**Steps to Reproduce**
deploy contracts in my tests then fund, add subscription etc and proceed to call the functions necessary to generate a random word

**Comment by Galaxysurfer2034** [comment]
Ok thank u.
