### ISSUE TITLE
DB limit open connections

### ISSUE THREAD

**Issue by Legogris** [smartcontractkit/chainlink#1557]
When using Postgresql as a database, we see that despite very low activity, new connections keep getting opened and are left idle.

I see that open connections are already limited for Sqlite: https://github.com/smartcontractkit/chainlink/blob/12a0352d3eb64259a75e9e9a994ba4ca3a0432e4/core/store/dbutil/dbutil.go#L43

I see a couple of options here:

* Do the same (but maybe with a higher value, say 5-10?) for Postgres
* Limiting `SetMaxIdleCons` for Postgres (some discussion here https://github.com/jinzhu/gorm/issues/246)
* Expose these as env variables (more flexible, but maybe overkill at this point)

**Comment by se3000** [comment]
@Legogris we believe this has been fixed now. We have improved the database locking logic. Are you still seeing this error?

**Comment by se3000** [comment]
No response. We believe this is fixed with the new Postgres locking strategy. Please reopen if you continue to run into the issue.
