### ISSUE TITLE
Validate that a job spec has at least one initiator and one task on creation

### ISSUE THREAD

**Issue by se3000** [smartcontractkit/chainlink#158]
A job spec needs at least one initiator to start, and at least one task to do anything useful. On creation, validate that a job spec has at least one initiator and at least one task.

There is already [some precedent for how to do validation](https://github.com/smartcontractkit/chainlink/blob/master/services/validators.go#L16).

**Comment by whatsadebugger** [comment]
ill take a look at this @se3000

**Comment by whatsadebugger** [comment]
you can update this to in progress
