### ISSUE TITLE
Ensure that multiple Bridge Types with the same name are not created

### ISSUE THREAD

**Issue by se3000** [smartcontractkit/chainlink#159]
Bridge Types are how a node operator defines the custom task types, bridging a task to an separate service, known as an External Adapter. Bridge Types can be created via a POST to the API `/bridge_types`. On creation, make sure that the new bridge type name does not collide with any other adapter, including [the core adapters](https://github.com/smartcontractkit/chainlink/wiki/Adapters).

There is already [some precedent for how to handle validation](https://github.com/smartcontractkit/chainlink/blob/master/services/validators.go#L16).

**Comment by jleeh** [comment]
I'll pick this one up.

**Comment by se3000** [comment]
Finished by #180.
