### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by samphilipd** [smartcontractkit/chainlink#1612]
Hi! I'd like to get started helping out with chainlink development. Is there a list of easy issues/bugs to tackle?

**Comment by thodges-gh** [comment]
Hey @samphilipd, you can take a look at our [public project tracker](https://www.pivotaltracker.com/n/projects/2129823) to see what we're currently working on and have in our backlog. We try to use the **help-wanted** tag for stories that we feel would be easier for newcomers to the project to tackle.
