### ISSUE TITLE
Underscore not allowed in Bridge URL

### ISSUE THREAD

**Issue by boxhock** [smartcontractkit/chainlink#1699]
Currently it is not possible to create bridges with an underscore <kbd>_</kbd> in the domain name. Error given with domain `http://chainlink_cmc-adapter_1:8080`:
```json
{"errors":[{"detail":"Invalid URL format"}]}
```

In Go, `net/url`'s `url.Parse(s)` does not give an error on this domain format.
Underscores in domain names is common practice when working with docker-compose networks.

**Comment by thodges-gh** [comment]
Created [#168685731](https://www.pivotaltracker.com/story/show/168685731) for this.

**Comment by Alkhara** [comment]
Underscores in the root hostname of a DNS address do not allow underscore per RFC-952 (https://tools.ietf.org/html/rfc952). They are only allowed in subdomains.

**Comment by boxhock** [comment]
@Alkhara I understand underscores are not necessarily "legal" in domain names, but since this restriction blocks Docker Compose setups, it does not make sense to have it in place.

It also does not make sense to put too much validation in place for something like a bridge URL. As long as it can reach it, that should be good enough. This URL format is perfectly fine for e.g. `DATABASE_URL`.

**Comment by Alkhara** [comment]
@boxhock I guess my concern is by allowing it, it would enable an HTTP request to an invalid hostname that would fail. But I suppose there is nothing stopping someone from putting a valid syntax URL that is a dead end as well.

**Comment by whatsadebugger** [comment]
WIP

**Comment by boxhock** [comment]
Fixed by #1824. Thanks @whatsadebugger!
