### ISSUE TITLE
go mod

### ISSUE THREAD

**Issue by whatsadebugger** [smartcontractkit/chainlink#1722]
to clean up import paths and make the code a little nicer. I recommend using chainlink as the module name to prevent long import paths like `github.com/smartcontrackit/chainlink/pkg/web`. You can move to just chainlink.

```
import (
chainlink/web
chainlink/core
)
```

If you like this I can make it happen.

**Comment by se3000** [comment]
Saw a PR open and close. What was the specific holdup on with the build?

**Comment by whatsadebugger** [comment]
wasn't sure if the change was warranted or not. i'd prefer to keep old imports for now to make sure not to disrupt anyone. open to work on something else though.
