### ISSUE TITLE
Make Install Error

### ISSUE THREAD

**Issue by jeremyjonas867** [smartcontractkit/chainlink#1773]
Hello. My chainlink build fails with bunch of the following errors.

<details>
<summary>
TypeError: Failed exporting HTML
</summary>
  TypeError: Failed exporting HTML for URL config (src/pages/config.js): Cannot read property 'createElement' of undefined
  
  - static-app.js:28945 createElement
    /home/Jery/Desktop/chainlink/operator_ui/artifacts/static-app.js:28945:26
  
  - react-dom-server.node.development.js:3090 processChild
    [chainlink]/[react-dom]/cjs/react-dom-server.node.development.js:3090:14
  
  - react-dom-server.node.development.js:3013 resolve
    [chainlink]/[react-dom]/cjs/react-dom-server.node.development.js:3013:5
  
  - react-dom-server.node.development.js:3436 ReactDOMServerRenderer.render
    [chainlink]/[react-dom]/cjs/react-dom-server.node.development.js:3436:22
  
  - react-dom-server.node.development.js:3395 ReactDOMServerRenderer.read
    [chainlink]/[react-dom]/cjs/react-dom-server.node.development.js:3395:29
  
  - react-dom-server.node.development.js:3954 renderToString
    [chainlink]/[react-dom]/cjs/react-dom-server.node.development.js:3954:27
  
  - exportRoute.js:127 renderToStringAndExtract
    [chainlink]/[react-static]/src/static/exportRoute.js:127:21
  
  - exportRoute.js:191 renderToStringAndExtract
    [chainlink]/[react-static]/src/static/exportRoute.js:191:15
  
  - runtime.js:45 tryCatch
    [chainlink]/[regenerator-runtime]/runtime.js:45:40
  
  - runtime.js:271 Generator.invoke [as _invoke]
    [chainlink]/[regenerator-runtime]/runtime.js:271:22
  
  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [chainlink]/[regenerator-runtime]/runtime.js:97:21
  
  - exportRoute.js:51 asyncGeneratorStep
    [chainlink]/[react-static]/lib/static/exportRoute.js:51:103
  
  - exportRoute.js:53 _next
    [chainlink]/[react-static]/lib/static/exportRoute.js:53:194
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7

</details>

- Network (Main net, Ropsten, etc.): Main net
- Go version: 1.13.1
- Host OS: Debian
- Commit (INFO line when starting the node): a07c27916aa5e523474c84af9b274a6b9143c7bd

**Comment by thodges-gh** [comment]
Hey @jeremyjonas867, a few questions:
- What version of Yarn do you have? (Mine is `1.19.1`)
- What version of Node.js do you have? (Mine is `v10.15.3`)

I'm also on Debian with Go 1.13.1 so I'm suspecting the issue is one of those.

**Comment by jeremyjonas867** [comment]
> Hey @jeremyjonas867, a few questions:
> 
>     * What version of Yarn do you have? (Mine is `1.19.1`)
> 
>     * What version of Node.js do you have? (Mine is `v10.15.3`)
> 
> 
> I'm also on Debian with Go 1.13.1 so I'm suspecting the issue is one of those.

I resolved this by reinstalling yarn
