### ISSUE TITLE
Fail with error 'Must use LINK token'

### ISSUE THREAD

**Issue by Leocn** [smartcontractkit/chainlink#1848]
I tested chainlink truffle.
https://www.trufflesuite.com/blog/using-truffle-to-interact-with-chainlink-smart-contracts 
I failed when i created  request.
`npx truffle exec scripts/request-data.js --network ropsten`

result 
![image](https://user-images.githubusercontent.com/3895136/68111505-37b79c00-ff2a-11e9-9b65-96875d42de3a.png)
truffle.config.json

```
    ropsten: {
      provider: function() {
        return new HDWalletProvider(mnemonic, "https://ropsten.infura.io/v3/2032a53632414443821272f70fe9e912")
      },
      network_id: 3,
      networkCheckTimeout:5000
      // Necessary due to https://github.com/trufflesuite/truffle/issues/1971
      // Should be fixed in Truffle 5.0.17
      //skipDryRun: true,
    }

```
My address 0xd34294fFfb9B10aD5E3BE3030D8CA0a5E544fa72
Contract address 0x7f5C843C86aBbCbf933676dEbC8DFe5e3f5750b4

Everytime i tried, same error happened.
![image](https://user-images.githubusercontent.com/3895136/68111862-14d9b780-ff2b-11e9-92f2-343edde4b279.png)

My address did not have token Links?
![image](https://user-images.githubusercontent.com/3895136/68111899-23c06a00-ff2b-11e9-9f4b-e2c10865fa33.png)

I tried this link several times. https://rinkeby.chain.link/
But the amount showed by MetaMask is still 0.

**Comment by thodges-gh** [comment]
@Leocn It looks like you changed the contract address for the LINK token to [0xdce2fde702e20c35fd690affca05df63efdf7de4](https://ropsten.etherscan.io/address/0xdce2fde702e20c35fd690affca05df63efdf7de4). The given scripts in the Truffle box expect the same LINK token to be used on the Ropsten network.

**Comment by Leocn** [comment]
@thodges-gh 
Thx.
![image](https://user-images.githubusercontent.com/3895136/68152004-bee22f80-ff7d-11e9-9afd-8fab07f15db6.png)
My address (0xd34294fFfb9B10aD5E3BE3030D8CA0a5E544fa72) have two types Link token. 
![image](https://user-images.githubusercontent.com/3895136/68152108-f5b84580-ff7d-11e9-977a-4cbd7ec025db.png)
But MetaMask shows nothing, it my two type Link tokens are wrong? So whats the address of the Link on MetaMask.

And i use the default setting when i funded contract, where can find the token setting .

**Comment by thodges-gh** [comment]
What token address did you add to Metamask? When you [deployed your contract](https://ropsten.etherscan.io/address/0x7f5c843c86abbcbf933676debc8dfe5e3f5750b4#code), you specified the LinkToken address that you created as the constructor argument. You should be using [0x20fE562d797A42Dcb3399062AE9546cd06f63280](https://ropsten.etherscan.io/address/0x20fe562d797a42dcb3399062ae9546cd06f63280) on Ropsten. I can see [you currently have a balance](https://ropsten.etherscan.io/address/0xd34294fffb9b10ad5e3be3030d8ca0a5e544fa72) of 400 Ropsten LINK. So if you added the correct contract address to Metamask and it still doesn't display correctly, that's an issue with Metamask reading Ropsten's state correctly.

**Comment by Leocn** [comment]
@thodges-gh 
 I downloaded the project and deployed again.
It succeed, thx.

**Comment by se3000** [comment]
Looks like this has been resolved. Going to close it for now, feel free to reopen @Leocn. Thanks for reporting.
