### ISSUE TITLE
TestServices_ApplicationSignalShutdown test fails on Windows environment

### ISSUE THREAD

**Issue by aklintsevich** [smartcontractkit/chainlink#194]
Failure:

github.com/smartcontractkit/chainlink/services_test
services\application_test.go:22:2: undefined: syscall.Kill
--- FAIL: ExampleRun (0.00s)

Cause:

syscall.Kill(syscall.Getpid(), syscall.SIGTERM)

**Comment by dimroc** [comment]
Similar to https://github.com/go-godo/godo/issues/42. Will investigate.

**Comment by benber86** [comment]
I don't think `syscall.Kill' nor `SIGTERM` will be supported on Windows. If you don't mind having os specific test files you could use `syscall.TerminateProcess` (which will work on Windows but not on Unix systems).
