### ISSUE TITLE
TestIntegration_RunLog fails

### ISSUE THREAD

**Issue by aklintsevich** [smartcontractkit/chainlink#203]
git fetch
git reset --hard origin/master
go test ./...

{"level":"warn","ts":1522402636.138564,"caller":"logger/logger.go:71","msg":"Unable to update latest block header","err":"EthMock: Method eth_getBlockByNumber not registered"}
{"level":"info","ts":1522402636.1555693,"caller":"logger/logger.go:61","msg":"Web request","method":"POST","status":200,"path":"/v2/specs","query":"","body":"{\r\n  \"initiators\": [{ \"type\": \"web\" }],\r\n  \"tasks\": [\r\n    { \"type\": \"HttpGet\", \"url\": \"https://bitstamp.net/api/ticker/\" },\r\n    { \"type\": \"JsonParse\", \"path\": [\"last\"] },\r\n    { \"type\": \"EthBytes32\" },\r\n    {\r\n      \"type\": \"EthTx\",\r\n      \"address\": \"0x356a04bce728ba4c62a30294a55e6a8600a320b3\",\r\n      \"functionSelector\": \"0x609ff1bd\"\r\n    }\r\n  ]\r\n}\r\n","clientIP":"127.0.0.1","comment":"","servedAt":"2018/03/30 - 02:37:16","latency":"9.5024ms"}
{"level":"info","ts":1522402636.1575668,"caller":"logger/logger.go:61","msg":"Web request","method":"POST","status":200,"path":"/v2/specs/0b8ed3251eb644af815ec3b1954a290f/runs","query":"","body":"","clientIP":"127.0.0.1","comment":"","servedAt":"2018/03/30 - 02:37:16","latency":"0s"}
{"level":"info","ts":1522402636.1675646,"caller":"logger/logger.go:61","msg":"Starting job","job":"0b8ed3251eb644af815ec3b1954a290f","run":"f222724624a445f980ef010474dcb568","status":"in progress"}
{"level":"info","ts":1522402636.960366,"caller":"logger/logger.go:61","msg":"Finished current job run execution","job":"0b8ed3251eb644af815ec3b1954a290f","run":"f222724624a445f980ef010474dcb568","status":"pending_external"}
{"level":"info","ts":1522402637.000395,"caller":"logger/logger.go:61","msg":"Starting job","job":"0b8ed3251eb644af815ec3b1954a290f","run":"f222724624a445f980ef010474dcb568","status":"in progress"}
{"level":"info","ts":1522402637.0078933,"caller":"logger/logger.go:61","msg":"Bumping gas to 25000000000 for transaction 0xa08c9a66509581074abe162d68386fcabcb9f1a2381c2b6c2b7cdf853b02343c","txat":{"Hash":"0xa08c9a66509581074abe162d68386fcabcb9f1a2381c2b6c2b7cdf853b02343c","TxID":1,"GasPrice":25000000000,"Confirmed":false,"Hex":"0xf88b8201008505d21dba008307a12094356a04bce728ba4c62a30294a55e6a8600a320b380a4609ff1bd31303538332e37350000000000000000000000000000000000000000000000002aa04a26a6f79c846d29d9f9617d5bf05930202fd9280733322f640f08efd0725bfaa021e06980788e2be9215b39f220e894f6ae84a1486f0f1d8a0a9ba720ec0ed751","SentAt":23459}}
{"level":"info","ts":1522402637.0158913,"caller":"logger/logger.go:61","msg":"Finished current job run execution","job":"0b8ed3251eb644af815ec3b1954a290f","run":"f222724624a445f980ef010474dcb568","status":"pending_external"}
{"level":"info","ts":1522402637.0469034,"caller":"logger/logger.go:61","msg":"Starting job","job":"0b8ed3251eb644af815ec3b1954a290f","run":"f222724624a445f980ef010474dcb568","status":"in progress"}
{"level":"info","ts":1522402637.055407,"caller":"logger/logger.go:61","msg":"Finished current job run execution","job":"0b8ed3251eb644af815ec3b1954a290f","run":"f222724624a445f980ef010474dcb568","status":"pending_external"}
{"level":"info","ts":1522402637.0784159,"caller":"logger/logger.go:61","msg":"Starting job","job":"0b8ed3251eb644af815ec3b1954a290f","run":"f222724624a445f980ef010474dcb568","status":"in progress"}
{"level":"info","ts":1522402637.0904086,"caller":"logger/logger.go:61","msg":"Bumping gas to 30000000000 for transaction 0x978fea8979bd837e81dd7e6387d058ebc86c14ffa2493b8dd8ea089943a37b8a","txat":{"Hash":"0x978fea8979bd837e81dd7e6387d058ebc86c14ffa2493b8dd8ea089943a37b8a","TxID":1,"GasPrice":30000000000,"Confirmed":false,"Hex":"0xf88b8201008506fc23ac008307a12094356a04bce728ba4c62a30294a55e6a8600a320b380a4609ff1bd31303538332e37350000000000000000000000000000000000000000000000002aa02b643f9c0641d4b3bb1d712da28ebba523faf5e0afd6fa5f5f11585983bf4039a036f4e6ff8487413c2b77fa4c91d78de7bda9c0ffe1b80cd16d23e5133e4dbc54","SentAt":23466}}
{"level":"info","ts":1522402637.1011639,"caller":"logger/logger.go:61","msg":"Confirmed tx 0xb7862c896a6ba2711bccc0410184e46d793ea83b3e05470f1d359ea276d16bb5","txat":{"Hash":"0xb7862c896a6ba2711bccc0410184e46d793ea83b3e05470f1d359ea276d16bb5","TxID":1,"GasPrice":20000000000,"Confirmed":true,"Hex":"0xf88b8201008504a817c8008307a12094356a04bce728ba4c62a30294a55e6a8600a320b380a4609ff1bd31303538332e373500000000000000000000000000000000000000000000000029a053ccecb237a486eea77b0c16445a9fca8ec5805ca27ad2801c9e0c9db83faa7ea075b68922e8b925d63762aee1ebdef15fa0fe08c70ca31e319d6e3847fc480471","SentAt":23456},"receipt":{"blockNumber":"0x5ba4","transactionHash":"0xb7862c896a6ba2711bccc0410184e46d793ea83b3e05470f1d359ea276d16bb5"}}
{"level":"info","ts":1522402637.1091592,"caller":"logger/logger.go:61","msg":"Finished current job run execution","job":"0b8ed3251eb644af815ec3b1954a290f","run":"f222724624a445f980ef010474dcb568","status":"completed"}
{"level":"info","ts":1522402637.125895,"caller":"logger/logger.go:87","msg":"Gracefully exiting..."}
{"level":"warn","ts":1522402637.2403963,"caller":"logger/logger.go:71","msg":"Unable to update latest block header","err":"EthMock: Method eth_getBlockByNumber not registered"}
{"level":"info","ts":1522402637.2563999,"caller":"logger/logger.go:61","msg":"Listening for runlog from block #0 (0x0) for address [all] for job a1d3b09672594a3d9eef020ed19bb731"}
{"level":"info","ts":1522402637.2563999,"caller":"logger/logger.go:61","msg":"Web request","method":"POST","status":200,"path":"/v2/specs","query":"","body":"{\r\n  \"initiators\": [{\"type\": \"runLog\"}],\r\n  \"tasks\": [{\"type\": \"NoOp\",\"confirmations\": 100}]\r\n}\r\n","clientIP":"127.0.0.1","comment":"","servedAt":"2018/03/30 - 02:37:17","latency":"8.505ms"}
{"level":"info","ts":1522402637.2729003,"caller":"logger/logger.go:61","msg":"Starting job","job":"a1d3b09672594a3d9eef020ed19bb731","run":"f7795ac87ccc4606b1a52424b8d37037","status":"in progress"}
{"level":"info","ts":1522402637.2798994,"caller":"logger/logger.go:61","msg":"Finished current job run execution","job":"a1d3b09672594a3d9eef020ed19bb731","run":"f7795ac87ccc4606b1a52424b8d37037","status":"pending_confirmations"}
{"level":"info","ts":1522402637.3078997,"caller":"logger/logger.go:61","msg":"Starting job","job":"a1d3b09672594a3d9eef020ed19bb731","run":"f7795ac87ccc4606b1a52424b8d37037","status":"in progress"}
{"level":"info","ts":1522402637.3103962,"caller":"logger/logger.go:87","msg":"Gracefully exiting..."}
{"level":"info","ts":1522402637.3143966,"caller":"logger/logger.go:61","msg":"Finished current job run execution","job":"a1d3b09672594a3d9eef020ed19bb731","run":"f7795ac87ccc4606b1a52424b8d37037","status":"pending_confirmations"}
--- FAIL: TestIntegration_RunLog (0.19s)
        testing_t_support.go:22:
                        C:/GoPath/src/github.com/smartcontractkit/chainlink/vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go:154 +0x6f8
                github.com/smartcontractkit/chainlink/vendor/github.com/onsi/gomega/internal/asyncassertion.(*AsyncAssertion).Should(0xc042454600, 0xd34700, 0xc0421a9250, 0x0, 0x0, 0x0, 0xd31a80)
                        C:/GoPath/src/github.com/smartcontractkit/chainlink/vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go:48 +0x69
                github.com/smartcontractkit/chainlink/internal/cltest.JobRunStays(0xc04224aff0, 0xc042102f00, 0xc052359940, 0x20, 0xc052359980, 0x20, 0x0, 0x0, 0x5, 0xc0523c2f18, ...)
                        C:/GoPath/src/github.com/smartcontractkit/chainlink/internal/cltest/cltest.go:472 +0x223
                github.com/smartcontractkit/chainlink/internal/cltest.JobRunStaysPendingConfirmations(0xc04224aff0, 0xc042102f00, 0xc052359940, 0x20, 0xc052359980, 0x20, 0x0, 0x0, 0x5, 0xc0523c2f18, ...)
                        C:/GoPath/src/github.com/smartcontractkit/chainlink/internal/cltest/cltest.go:481 +0xb4
                github.com/smartcontractkit/chainlink/web_test.TestIntegration_RunLog(0xc04224aff0)
                        C:/GoPath/src/github.com/smartcontractkit/chainlink/web/integration_test.go:182 +0x6c4
                testing.tRunner(0xc04224aff0, 0xcbec80)
                        C:/Go/src/testing/testing.go:777 +0xd7
                created by testing.(*T).Run
                        C:/Go/src/testing/testing.go:824 +0x2e7
Failed after 0.021s.
                Expected
                    <models.RunStatus>: in progress
                to equal
                    <models.RunStatus>: pending_confirmations

**Comment by aklintsevich** [comment]
:+1:

**Comment by se3000** [comment]
Hopefully closed by #204. Let's reopen if this persists.

**Comment by aklintsevich** [comment]
Repro-ed consistently before, and didn't encounter it today, so it's probably fixed
