### ISSUE TITLE
# [DEVEL] Solidity ^5.0.0 compatibility issue, Log Data Parsing Ignores Datalength

### ISSUE THREAD

**Issue by leovigna** [smartcontractkit/chainlink#2175]
**Description**
I have been working on an implementation of the `Oracle.sol` contract that uses OpenZeppelin's Proxy upgradeability features. I therefore used Solidity ^0.5.0 to port it to the Proxy architecture.

**Your Environment**
Docker. `Chainlink Node 0.7.0 at commit 85aef95191b9c39efb2c9fb7dd1eb697b51b8db7`

**Basic Information**
Log Events with padded zeroes created CBOR Parsing errors.
```
[ERROR] Error parsing CBOR: cbor decode error ...
```

**Steps to Reproduce**
Deploy an `Oracle.sol` contract compiled with Solidity ^0.5.0. 
Emit OracleRequests using `oracleRequest()`.
You will see that event logs are padded with zeroes to the nearest 32bytes. This causes CBOR parsing issues from the Chainlink node which is then unable parse the request.

Example Transaction: https://ropsten.etherscan.io/tx/0x44c1385e98df50c1da2d99af38669d6c591be39521d1bc8cb69b28d639baea4f#eventlog
```
000000000000000000000000ccda67e03404e28b610bbc4ba5aecd4b6e5ce55e
242dad663b8a55a4129519abb7120775d25d9a6dde8d65872d7835649b5dd603
0000000000000000000000000000000000000000000000000de0b6b3a7640000
000000000000000000000000ccda67e03404e28b610bbc4ba5aecd4b6e5ce55e
92cdaaf300000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000005e20b22a
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000100
0000000000000000000000000000000000000000000000000000000000000056
63676574783f68747470733a2f2f6d696e2d6170692e63727970746f636f6d70
6172652e636f6d2f646174612f70726963653f6673796d3d455448267473796d
733d5553446470617468635553446574696d6573186400000000000000000000
```
Added padding `00000000000000000000` creates CBOR parsing issue.

Compare this to the same request but to a Solidity ^0.4.24 Oracle with no Proxy delegate.

https://ropsten.etherscan.io/tx/0x765fa34cc39cf63f36a89ca765e55d35dd1c52f83680c6b056ef8a4ee4ea9d19
```
000000000000000000000000650c346f84248abc27e716ea3c6de20f7fbbdb79
e947f54ec4d3cab0588684217b029cd9421ea25c59f3309bef6e8fb0d75ff531
0000000000000000000000000000000000000000000000000de0b6b3a7640000
000000000000000000000000650c346f84248abc27e716ea3c6de20f7fbbdb79
92cdaaf300000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000005e1b7f6b
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000100
0000000000000000000000000000000000000000000000000000000000000056
63676574783f68747470733a2f2f6d696e2d6170692e63727970746f636f6d70
6172652e636f6d2f646174612f70726963653f6673796d3d455448267473796d
733d5553446470617468635553446574696d65731864
```

**On-chain Backwards Compatible Workaround**
Right now I have managed to make my `UpgradeableOracle.sol` backwards compatible with the Chainlink node by using a low-level `log()` call instead of `emit OracleRequest()` as this gives more control on the encoding of the log data and makes it possible to avoid the padding.

Example Transaction: https://ropsten.etherscan.io/tx/0xf13145932b5ff7407e8cc2d09d421ae15e122254a32d4386e14325fe9baae773#eventlog
```
000000000000000000000000ccda67e03404e28b610bbc4ba5aecd4b6e5ce55e
501994ca86afe12d82390be2b35c153c4980119bb5289d38d63c19112d73d375
0000000000000000000000000000000000000000000000000de0b6b3a7640000
000000000000000000000000ccda67e03404e28b610bbc4ba5aecd4b6e5ce55e
92cdaaf300000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000005e219d98
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000100
0000000000000000000000000000000000000000000000000000000000000056
63676574783f68747470733a2f2f6d696e2d6170692e63727970746f636f6d70
6172652e636f6d2f646174612f70726963653f6673796d3d455448267473796d
733d5553446470617468635553446574696d65731864
```
Padding removed thanks to assembly `log()` call.
You'll also notice that both the 1st and 3rd transactions are from the address `0xB4D58a6071564b456e37FeDC5bD48f73Ffee0CfC`. After finding the `log()` workaround, all I had to do was upgrade the implementation.

**Potential Long-term Solution**
I believe the code in question below creates the issue as the encoding becomes invalid with padded zeroes.
```
expirationEnd := idStart + idSize + paymentSize + callbackAddrSize + callbackFuncSize + expirationSize
	cborStart := expirationEnd + versionSize + dataLocationSize + dataLengthSize
	js, err := ParseCBOR(data[cborStart:])
```
The long-term solution would be to leverage the data length info that is present in the log data and is currently just ignored (and therefore ignores padding).
This would entail computing `data[cborStart:cborEnd]`.

**Comment by thodges-gh** [comment]
Thank you @leovigna! We have a story for this in our tracker [here](https://www.pivotaltracker.com/story/show/170394633).

**Comment by leovigna** [comment]
Forgot to add this. My solution.
https://github.com/leovigna/upgradeable-oracle

**Comment by thodges-gh** [comment]
@leovigna I think the solution to this will be to update the core node to allow for parsing the updated CBOR, rather than making more contract changes. Also, I don't like the idea of proxy contracts with the oracle contract. A malicious oracle could deploy a valid oracle contract, then later swap that out with a modified oracle contract without a requester knowing. There's too much benefit with security in forcing the node operator to deploy a new oracle contract to a new address when a change is made.

**Comment by leovigna** [comment]
I understand that there is additional counterparty risk with the proxy but that risk is no different than the risk of the backend node that will fulfill the request.

**Comment by leovigna** [comment]
Updating core is the right move. I found this workaround to be quite elegant in preserving backwards compatibility short term.
