### ISSUE TITLE
[FEAT] Make JobIds deterministic

### ISSUE THREAD

**Issue by leovigna** [smartcontractkit/chainlink#2176]
**Description**
Make JobIds (optionally) deterministic. Such as for example `keccak256(JobSpec)`.

**Motivation**
Many nodes provided the same standard HTTP Get, Post jobs but users must rely on explorers not only to find Oracles but also find the right JobId for each Oracle.

**Justification**
Deterministically computed JobIds enable more standardization across Oracles and for simpler user adoption.

**Comment by leovigna** [comment]
Maybe this is better resolved by ENS and therefore a resolver for Chainlink jobs might be interesting.

**Comment by thodges-gh** [comment]
Hi @leovigna, I've had some discussions about this in the past, but one problem is how the node listens to requests. The RunLog initiator listens to a specific log topic, where the data contains the Job ID. If the node operator hasn't added the "address" param to their job spec, which allows the node to ignore requests from any other oracle contract than their own, a malicious user could create a request to their own oracle contract with the same Job ID and get the target oracle to respond to it, allowing the malicious oracle contract owner the ability to withdraw payment.

The long-term solution to this is ultimately service agreements, where the individual Job IDs of each node isn't important, but the Service Agreement ID (SAID) is what requesters would use to initiate a request to multiple nodes. You can read about this protocol [here](https://github.com/smartcontractkit/chainlink/wiki/Protocol-Information#service-agreements).
