### ISSUE TITLE
[FEAT] the new JSON attributes in response.

### ISSUE THREAD

**Issue by ponchik69** [smartcontractkit/chainlink#2193]
**Description**
Add the new attributes about runs state (completed and errored) for API JSON response to http://localhost:6688/v2/runs?jobSpecId=:SpecID 

**Motivation**
There is no single endpoint for obtaining the number of completed and errored tasks.

**Justification**
This will make it easier to monitor the status of tasks. (For example, using Prometheus)
Now you need to go through all the pages and count the number completed and errored tasks. In the same time, API JSON already returns total runs count for current job.

**Additional Information**
I mean something like this:

`http://localhost:6688/v2/runs?jobSpecId=:SpecID`

`{
  "data": [
    {
      "type": "runs",
      "id": "91388f11e0fc4123870bda7128ce78a9",
      "attributes": {
          ...
      }
    },
    {
      "type": "runs",
      "id": "91388f11e0fc4123870bda7128asds21",
      "attributes": {
          ...
      }
    }
  ],
  "meta": {
    "count": 2
    "completed": 1
    "errored": 1
  }
}`

**Comment by PatrickAlphaC** [comment]
Thanks for this issue! Looks like it shouldn't be that hard. This would be a great issue for someone to work on if they'd like to be apart of the community.

**Comment by cds95** [comment]
Hi, I'd like to try work on this as a first issue but don't see a ticket for it in Pivotal Tracker.  Is there a way for me to create a new one?

**Comment by PatrickAlphaC** [comment]
Feel free to not use Pivotal tracker for this one.

**Comment by samsondav** [comment]
No longer applicable since we dropped pipeline v1.
