### ISSUE TITLE
[FEAT] JS SDK available?

### ISSUE THREAD

**Issue by roccomuso** [smartcontractkit/chainlink#2222]
**Description**

Is there a Javascript/Node.js SDK available?

**Motivation**

To easily develop atomic fns, generate address from privateKey and create/send txs.

**Comment by thodges-gh** [comment]
@roccomuso This can be used to help test your Chainlink contracts: https://www.npmjs.com/package/chainlink

**Comment by roccomuso** [comment]
I'm not looking into contracts.
I would just like to generate a valid LINK address given a PK with a JS SDK (if any).

**Comment by thodges-gh** [comment]
I'm sorry, that's not what our project does. We use existing Etherum tools, like web3.js or ethers.js, to deploy contracts, manage accounts, etc.

**Comment by samlaf** [comment]
I agree that it would be nice to have a chainlink sdk, so that we don't need to manually copy the ABI and contract address (and maintain these when they change!) of the chainlink contracts.
