### ISSUE TITLE
[FEAT] Make `basePath` in web app configurable AND/OR Fork the web app.

### ISSUE THREAD

**Issue by leovigna** [smartcontractkit/chainlink#2349]
**Description**
Currently, the docker image for chainlink builds the webapp on the root for all static web resources. This makes it impossible to setup a proxy/kubernetes cluster to serve the webapp on `/chainlink` for example. While security considerations make it bad practice to serve the dashboard publicly, I still would like to be able to tunnel to my kubernetes cluster and access all my services from one endpoint. Note that serving chainlink on `/chainlink` works for the api, just not for the static web content.

**Motivation**
Enable multi-service architectures that can serve different services from 1 domain and different endpoints.

**Justification**
Node operators should have flexibility regarding what endpoint they serve their chainlink dashboard from.

**Additional Information**
@rrpprr has offered some pointers in the Discord on what would have to be changed. Ideally, this could be achieved with an environment variable such as `REACT_BASEPATH`. 
https://github.com/react-static/react-static/blob/master/docs/config.md#basepath
https://github.com/smartcontractkit/chainlink/blob/develop/operator_ui/static.config.js

Ideally, in the long run, I think it could be favorable to fork the dashboard into its separate docker-image enabling a user to run the chainlink node with one image, and the dashboard with another.

**Comment by thodges-gh** [comment]
Thanks for the request @leovigna! Story for tracking: https://www.pivotaltracker.com/story/show/171420794

**Comment by jakedamon** [comment]
@se3000 is this still a valid issue?

**Comment by pappas999** [comment]
thanks for re-raising @jakedamon , let me check with the team on this and get back to you

**Comment by PatrickAlphaC** [comment]
Closing due to no movement. Adding `needs votes` if people feel it's important or they want to re-open.
