### ISSUE TITLE
[NODE] adminUI Job Continuous deletion is not possible

### ISSUE THREAD

**Issue by nodebreaker0-0** [smartcontractkit/chainlink#2662]
In version 0.8.1, when creating a job, it can be archived only once for the first time, and it is impossible to archive JOBs created afterwards.

Or, even if the node is restarted, it is confirmed that it can be deleted only once after the restart.

Seems like a bug, please check

**Comment by se3000** [comment]
Thanks @nodebreaker0-0. We'll investigate.

**Comment by se3000** [comment]
This has been fixed as of `0.8.4`.

**Comment by se3000** [comment]
Closing. Thanks for reporting.
