### ISSUE TITLE
Using JSONParse with bridge types returns "non string value" 

### ISSUE THREAD

**Issue by jleeh** [smartcontractkit/chainlink#284]
I've been testing on Ropsten with my own node so I can re-deploy the contracts and use my own specs, one of them being using the assetPrice external adaptor.

Here's the job spec:
```json
{
   "initiators":[
      {
         "type":"runlog",
         "address": ""
      }
   ],
   "tasks":[
      {
         "type":"assetPrice"
      },
      {
         "type":"jsonParse"
      },
      {
         "type":"ethuint256"
      },
      {
         "type":"ethtx"
      }
   ]
}
```

Consumer contract:
```
pragma solidity ^0.4.23;

import "../Chainlinked.sol";
import "../lib/strings.sol";
import "openzeppelin-solidity/contracts/ownership/Ownable.sol";

contract AssetPriceConsumer is Chainlinked, Ownable {
  bytes32 internal jobId;
 
  mapping(bytes32 => uint256) public assetPrices;
  mapping(bytes32 => bytes32) public requests;

  using strings for string;
  using strings for strings.slice;

  event RequestFulfilled(
    bytes32 indexed requestId,
    uint256 indexed price
  );

  constructor(address _link, address _oracle, bytes32 _jobId) public {
    setLinkToken(_link);
    setOracle(_oracle);
    jobId = _jobId;
  }

  function getAssetPrice(string base, string quote) public {
    ChainlinkLib.Run memory run = newRun(jobId, this, "fulfill(bytes32,bytes32)");
    run.add("base", base);
    run.add("quote", quote);
    string[] memory path = new string[](1);
    path[0] = "price";
    run.addStringArray("path", path);
    bytes32 requestId = chainlinkRequest(run, LINK(1));
    requests[requestId] = keccak256(base, quote);
  }

  function cancelRequest(uint256 _requestId)
    public
    onlyOwner
  {
    oracle.cancel(_requestId);
  }

  function fulfill(bytes32 _requestId, uint256 _price)
    public
    onlyOracle
    checkRequestId(_requestId)
  {
    emit RequestFulfilled(_requestId, _price);
    assetPrices[requests[_requestId]] = _price;
  }

  modifier checkRequestId(bytes32 _requestId) {
    require(requests[_requestId] != keccak256(0));
    _;
  }

}
```

When I fire off a tx for `getAssetPrice`, I can see the node starting to execute the tasks:
```
2018-05-06T14:27:08Z [INFO] Starting job services/job_runner.go:94 job=7077c72ac18e4de58621245800ccf999 run=46a2a9f361d1498f9f846e46a9be56d3 status=in_progress
2018-05-06T14:27:09Z [DEBUG] Produced task run services/job_runner.go:132 taskRun=TaskRun(c84fc923819e48d184592dc53ba7c89a,assetpricenew,completed,)
```

Logs from the bridge type:
```
06/May/2018:14:27:08 +000 200 351630μs "POST /price HTTP/1.1" - "Go-http-client/1.1"
```

JSON from the assetPrice bridge type:
```
{
  "jobRunId": "1234",
  "data": {
    "base": "LINK",
    "quote": "ETH",
    "id": "LINK-ETH",
    "price": "0.00067659",
    "volume": "760207",
    "exchanges": [
      "Binance"
    ]
  },
  "status": "",
  "error": null,
  "pending": false
}
```

Error from JSONParse:
```
2018-05-06T14:27:09Z [DEBUG] Task jsonparse services/job_runner.go:133 task=1 type=jsonparse params=
{
    "address": "0xF790026Adf478AAE540c36c2De6f3DF7A4f1c7a8",
    "base": "LINK",
    "dataPrefix": "0x0000000000000000000000000000000000000000000000000000000000000009",
    "functionSelector": "76005c26",
    "path": [
        "price"
    ],
    "quote": "ETH",
    "type": "jsonParse"
}
taskrun=b54529fedc2847b89625fe4e2f1beccf result=non string value
```

Originally when I was getting this, the bridge type was returning the price as a float value and on refactoring so it returns a string, got the same error.

It was my understanding that anything within `data` in the JSON is merged throughout the tasks so it's persisted through to the end, but it seems it's not being included here?

**Comment by se3000** [comment]
Your understanding about merging data is correct. I believe that what's going wrong here is that the `jsonparse` adapter looks for stringified JSON in the `value` key of the input data. It looks like you are already passing parsed JSON object in, so you probably don't need the `jsonparse` adapter. But, I don't think that change alone will achieve what you're looking for.

The `ethuint256` adapter looks up the `value` key in the input. `value` is a key that all of the core adapters use as the conventional field off of which to pull the input's data. To make this available, I see two options:
1) change your external adapter to rename the `price` key as `value`.
2) create a "map" adapter that takes the input and copies one key/value pair to another key. E.g. it would be configured with `{"price": "value"}`, and for your input,  `{"base": "LINK","quote": "ETH","id": "LINK-ETH","price": "0.00067659","volume": "760207","exchanges": ["Binance"]}` would turn into `{"value":"0.00067659","base": "LINK","quote": "ETH","id": "LINK-ETH","price": "0.00067659","volume": "760207","exchanges": ["Binance"]}`. Then the other adapters can continue to pull data off of the field they expect it to be written into.

I personally like option 2, but if you need to get this working immediately you can go with option 1. I've definitely talked about option 2 with some folks, but we have gone with the shorter term solution in the past. Might be a good time to bite the bullet and build the map adapter. Thoughts?

**Comment by se3000** [comment]
Also, you're going to need to use a `multiply` adapter before passing a decimal value into `ethuint256`, because it truncates decimals.

**Comment by jleeh** [comment]
I like option two also, with implementing that, I could also allow the end-user to specify what value they'd like to parse from the adaptor with say a `map` param that's passed into the `getAssetPrice` function. They could pick to pull the volume then rather than just the price.

How about a third option of setting the JSON object returned from `httpGet` to the `data` object? Then the JSON parser could look for values to parse within the `data` obj, rather than using a JSON string.

With this way, you could still use JSONParse for both HttpGet and any bridge types, meaning no new core adaptor would have to be created, and the way of parsing values is the same for both. 

Obviously you know far more than me around this, but I feel this wouldn't have that much opportunity for any regressions to pop-up, as everything is still encompassed within `data` it'd just be the way it's parsed is different.

**Comment by jleeh** [comment]
I'll work on creating a map adaptor @se3000 , was giving more thought and was against my own idea when I thought about parsing arrays at the base level etc, seems a big change for not much.

Thanks for the suggestion!

**Comment by se3000** [comment]
Handled with #307. Thanks again @jleeh!
