### ISSUE TITLE
Inappropriate ioctl for device

### ISSUE THREAD

**Issue by danielimkk** [smartcontractkit/chainlink#2875]
**Description**
I am trying to insert my credentials using EOF into an input field for the following command: `chainlink admin login`. But I receive a "Inappropriate ioctl for device" error.
Could you please tell me if there is a way to pass my credentails for `chainlink admin login` command autmatically? Thank you!

**Basic Information**
Node is launched using docker image

**Steps to Reproduce**
a) chainlink admin login < credentials-file
b) printf 'email\npassword\n' | chainlink admin login

**Comment by tyrion70** [comment]
Please try `chainlink admin login -f credentials-file`. That should work with your credentials in the credentials file with email and password on two lines.

**Comment by danielimkk** [comment]
Thank you very much, that helps
