### ISSUE TITLE
[SMRT] <SafeMath Inheritance Bug in VRF Contract>

### ISSUE THREAD

**Issue by pynchmeister** [smartcontractkit/chainlink#3153]
**Description**
While trying to deploy an instance of the Chainlink VRF contract otherwise known as VRFTestnetD20 I have been experiencing a recent issue on the line:

```using SafeMath for uint;```

The error returned is as follows:

```DeclarationError: Identifier not found or not unique.```

**Comment by pynchmeister** [comment]
A solution would be to change the import line:

```import "https://raw.githubusercontent.com/smartcontractkit/chainlink/develop/evm-contracts/src/v0.6/VRFConsumerBase.sol";```

to:

```import "https://raw.githubusercontent.com/smartcontractkit/chainlink/evm-contracts/src/v0.6/VRFConsumerBase.sol";```

excluding the develop directory as that is no longer present in this repo.

Unfortunately this brings the following bug:

``` ParserError: Expected pragma, import directive or contract/interface/library/struct/enum definition.
404: Not Found
^-^```

which seems to have something to do with the code here: https://github.com/smartcontractkit/chainlink/blob/feature/173501514-Add-Last-updated-to-the-feed-card/evm-contracts/src/v0.6/VRFConsumerBase.sol

**Comment by PatrickAlphaC** [comment]
Adding `import "https://github.com/smartcontractkit/chainlink/evm-contracts/src/v0.6/vendor/SafeMath.sol";` to your remix file will fix it for now.

You could also change using `SafeMath for uint;` -> `using SafeMath_Chainlink for uint;`

Looks like it's an issue with this commit:
https://github.com/smartcontractkit/chainlink/commit/dba918e13f2ee096af6548e21e9c755ccd541ea8#diff-47b27e5193ce0494d6a8a9903245b7d1

**Comment by pynchmeister** [comment]
Still needs fixing in the source code, but the contract compiles on my end. Will do PR if I can discover the bug.
