### ISSUE TITLE
[DEVEL] LINK variable naming collision in VRFConsumerBase and ChainlinkClient contracts

### ISSUE THREAD

**Issue by skyfly200** [smartcontractkit/chainlink#3175]
**Description**
When inheriting both VRFConsumerBase and ChainlinkClient into a contract a compiler error is thrown

**Your Environment**
Solidity Compiler Version 0.6.8
Chainlink v0.6 Contracts
Compiling with oz CLI tools on Windows 10 using a WSL Debian terminal with latest node and npm

**Basic Information**
The LINK identifier is being used in both contracts, both with different types and purposes.
In VRFConsumerBase it is storing the interface to the LINK token, meanwhile, in ChainlinkClient it represents the value of one whole link token aka 10**18.

**Steps to Reproduce**
Import and inherit both VRFConsumerBase and ChainlinkClient into a single contract, either directly or indirectly through inheritance.
Compile the contracts.

**Additional Information**
Here is an image of the error message on compile
![image](https://user-images.githubusercontent.com/2071514/87576079-151b7c80-c68e-11ea-9e6d-8c289cafb661.png)

I edited the variable name LINK in ChainlinkClient to ONE_LINK to prevent the naming collision.
I am using the LINK token interface defined in VRFConsumerBase in my code that inherits it. So I wanted to keep that the same and it seems more logically fitting of the name.

**Comment by skyfly200** [comment]
I realize its probably cleaner to change the name over in VRF as it's not finalized yet.
Just sharing how I fixed it in case someone else runs into this issue.

**Comment by therealsphinx** [comment]
@skyfly200 Got the same error. Is it a security issue?

**Comment by skyfly200** [comment]
No, just a naming collision conflict with a dependency used in more than one contract you're inheriting from.

**Comment by PatrickAlphaC** [comment]
Thanks for this issue, it's been added as a bug!

**Comment by PatrickAlphaC** [comment]
Closing due to PR merged.
