### ISSUE TITLE
[NODE] Simplify Add Job Experience

### ISSUE THREAD

**Issue by GMSteuart** [smartcontractkit/chainlink#3256]
**Description**
As a user, I want to be able to add jobs to my operator in a quick and informative way.

**Initial Criteria**
Currently, adding a job requires a user to insert the JSON required to create a job. Determining the proper JSON when reading the documentation also adds uncertainty to whether or not the JSON inserted is correct and will achieve the result desired. Ideally the user interface would have the following tentative features:

- Quick job templates that will automatically populate the newly designed form with the job the user wants to add or modify from the base (e.g. Adding an alarm job).
- The form will have a checkbox to toggle whether a job will be locked to a single address or open to all.
  - If locked to a single address, there will be a place to input the address and a warning will be displayed if the contract does not exist.
- The form will display an empty task to be configured with input fields dynamically being created based off the adapters specification.
- Each task fieldset will have at the minimum, a dropdown list to select from the Core adapters.
- The form will allow adding a task to the end of the task list with a "+ Add Task" button or some other similar and intuitively designed component.
- The form will allow a user to enter an input to simulate job runs at the top and see the resulting transformation every task has on that input and the final outcome.
- The form will clearly display the sequential transformation (e.g. an arrow pointing to the next task).
- The form will allow a user to reorder tasks via drag and drop.
- The form will display in an error state when the job defined would could not logically be executed.
- The form will allow a user to view the resulting JSON by interacting with a recognizable UI element.
- The form will allow a user to switch to a JSON input mode still allowing user's to input JSON as is the status quo.

**Remarks**
The new form experience described above is by no means an MVP implementation, but it is a starting point for discussion if this is a feature that is desirable. This issue also does not describe in detail how the task input fields will be handled and is meant to be a general overview of what would likely be the core features of adding a job.

**Comment by TrevorBenson** [comment]
I whole heatedly support this proposal. The described interface and job simulation I feel would speed up adoption for both oracle operators and new chainlink developers alike. I'd love to see this available in a branch for testing purposes which could then garner more comments/feedback to improve the implementation.

**Comment by PatrickAlphaC** [comment]
This feels like it might actually be a decent first issue... Should I label it as such?

**Comment by PatrickAlphaC** [comment]
This probably needs to be updated for 2022 with all the new changes... I'm going to close for now.
