### ISSUE TITLE
Vulnerability in the code

### ISSUE THREAD

**Issue by Corsairs** [smartcontractkit/chainlink#3258]
Hello, where can I write about the vulnerability to get a fee?

**Comment by Corsairs** [comment]
is there anyone alive?

**Comment by Corsairs** [comment]
Your project costs millions of dollars and you don't even have support on the official website, are you serious?
Even the cheapest hosting provider has support when buying hosting.
You have 10 people working there or something, you can hire people it's not serious.

**Comment by mawi13** [comment]
May check this out https://gitcoin.co/blog/gitcoin-chainlink-bug-bounty-program/

**Comment by coventry** [comment]
https://gitcoin.co/issue/smartcontractkit/chainlink/3239/100023497

Happy hunting!

> ### Program Rules
> * Email reports to [bounty@chain.link](mailto:bounty@chain.link)
> * Please provide detailed reports with reproducible steps. If the report is not detailed enough to reproduce the issue, the issue will not be eligible for a reward.
> * Submit one vulnerability per report, unless you need to chain vulnerabilities to provide impact.
