### ISSUE TITLE
Cannot get Ropsten Test Net Link

### ISSUE THREAD

**Issue by nurajc** [smartcontractkit/chainlink#3337]
I have tried few occasions to retrieve ropsten testnet LINK token to my address, it returns a transaction hash, but it is not a valid and is never included in the chain. So I am stuck without LINK tokens to try out the transactions. Can you help me with this ?

**Comment by PatrickAlphaC** [comment]
@nurajc Ropsten is down.

**Comment by alexroan** [comment]
Hey @nurajc , We've stopped supporting Ropsten since it had a multi-day reorg. [Here's a list of the networks we support](https://docs.chain.link/docs/link-token-contracts) and faucet details.
