### ISSUE TITLE
[NODE] How can I specify the topics for ethlog

### ISSUE THREAD

**Issue by eltNEG** [smartcontractkit/chainlink#3484]
**Description**
I would like to specify the topics that eth logs should listen to. The documentation is not clear about this and when I tried a similar format that I found in this codebase, I got an error.

**Basic Information**

- Network: Ethereum genache client
- Blockchain Client: genache
- Go Version: [e.g. v1.12]
- Operating System: mac os
- Commit: docker image with image id: bb2ca99b8935
- Hosting Provider:self hosted
- Startup Command: [e.g. `docker run smartcontract/chainlink local n`]

**Environment Variables**
[replace this line with the output of the environment variables when running the node in debug mode]

**Steps to Reproduce**
[replace this line with detailed steps to reproduce the issue you are experiencing]

**Additional Information**

JSON CONFIG
```
{
  "initiators": [
    {
      "type": "ethlog",
      "params": {
        "address": "0x6A7D7BcE0424F369082c4b85Bc3A72DB4Bf85e09",
        "topics": ["0xdeadbeefdeadbeedeadbeedeadbeefffdeadbeefdeadbeedeadbeedeadbeefff"]
      }
    }
  ],
  "tasks": [
    {
      "type": "NoOp"
    }
  ],
  "startAt": "2020-02-09T15:13:03Z",
  "endAt": null
}
```

<img width="1433" alt="Screenshot 2020-10-17 at 7 21 31 PM" src="https://user-images.githubusercontent.com/22221987/96351079-0f7c6b00-10b1-11eb-94aa-0722a61114ae.png">

**Comment by PatrickAlphaC** [comment]
Could you look at [this link](https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB#logs) per chance? It looks like it might have some information of what you're looking for?

**Comment by se3000** [comment]
Thanks for filing @eltNEG. Opening a bug for this.

**Comment by samsondav** [comment]
Closed since JSON jobs are no longer supported
