### ISSUE TITLE
The README file in this repo has a bad link

### ISSUE THREAD

**Issue by MrCull** [smartcontractkit/chainlink#3523]
The README file in this repo has a bad link

Status code [404:NotFound] - Link: https://github.com/smartcontractkit/chainlink/blob/docs/COMMUNITY.md

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by PatrickAlphaC** [comment]
Closing as this was fixed in https://github.com/smartcontractkit/chainlink/pull/3528.

Thanks for the issue!
