### ISSUE TITLE
[FEAT] Prometheus-like metrrics endpoint

### ISSUE THREAD

**Issue by willianpaixao** [smartcontractkit/chainlink#3613]
**Description**
Implement an endpoint that would summarize a few key metrics of the node.
Examples at [Geth](https://github.com/hunterlong/gethexporter) [Geth2](https://github.com/31z4/ethereum-prometheus-exporter).

**Motivation**
This would allow a monitoring tool to track usage, performance, cost of one or several nodes over time, giving greater knowledge by the node operator.

**Justification**
Node operations should use all available tools to assist the operator, being active rather than reactive.
If a node starts to misbehave, the operator can notice that early rather than later, losing tokens and getting his/her node reputation degraded due to outages in the node health.

**Comment by PatrickAlphaC** [comment]
Another great suggestion, we've added this as an enhancement.

**Comment by se3000** [comment]
We actually already expose a `/metrics` endpoint that exposes Prometheus data. Is there any specific metric you're hoping for?

**Comment by willianpaixao** [comment]
I'm sorry, you're right. For some reason, the `/metrics` endpoint returned `404` when I tried, so I opened this issue. Now it works fine.
