### ISSUE TITLE
[SMRT] SPDX Warning when using Solidity 0.7

### ISSUE THREAD

**Issue by drbullock** [smartcontractkit/chainlink#3623]
**Description**
I Get this Warning when using Chainlink aggregator in solidity 0.7

**Basic Information**
This is the warning
```
@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol: Warning: SPDX license 
identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information. 
``` 

**Steps to Reproduce**
Import  and Compile any Chainlink Smart Contracts in any solidity 0.7 Smart Contract

**Additional Information**
Truffle v5.1.52 (core: 5.1.52)
Solidity - 0.7.4 (solc-js)
Node v12.18.4
Web3.js v1.2.9

**Comment by PatrickAlphaC** [comment]
@drbullock thanks for submitting this issue.

You'll notice the rest of the warning reads `identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information. `

You can remove this warning on any smart contract that gets this by adding an SPDS License Identifier, ie:
```
// SPDX-License-Identifier: MIT
```

Would love to see a StackOverflow question on this so others won't run into the same issue. If you'd like to open up a StackOverflow or Stack Exchange ETH question with this content, I think that would greatly help the community that runs into the same question. Feel free to link it here.

**Comment by drbullock** [comment]
Hi @PatrickAlphaC , I will check to open a StackOverflow question for that. Hope you have on the list of adding Identifiers in the next release.

**Comment by PatrickAlphaC** [comment]
Good point. I've reopened the issue and marked it as a `good first issue` as this could be a layup PR for someone looking to get involved.

**Comment by BookmDan** [comment]
Hi Patrick,

I am seeing this error: 

Not sure what I am doing wrong here.

Thank you for your help. 
![Screen Shot 2021-09-14 at 1 47 07 PM (2)](https://user-images.githubusercontent.com/8926023/133331497-552f93dd-e276-45dc-9504-60c989adc141.png)

**Comment by Akinyosoye-Oluwatobiloba** [comment]
> @drbullock thanks for submitting this issue.
> 
> You'll notice the rest of the warning reads `identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information. `
> 
> You can remove this warning on any smart contract that gets this by adding an SPDS License Identifier, ie:
> 
> ```
> // SPDX-License-Identifier: MIT
> ```
> 
> Would love to see a StackOverflow question on this so others won't run into the same issue. If you'd like to open up a StackOverflow or Stack Exchange ETH question with this content, I think that would greatly help the community that runs into the same question. Feel free to link it here.

I have published the post
