### ISSUE TITLE
[FEAT] Implement Docker healthcheck

### ISSUE THREAD

**Issue by willianpaixao** [smartcontractkit/chainlink#3631]
**Description**
Add a simple `/healthcheck` endpoint that simply returns 200 in case no error has been reported. In case of error, a different return code and a JSON returns otherwise.

**Motivation**
To easily spot and automatically restart unresponsive containers.

**Justification**
Such a feature would improve the monitoring of the chainlink node, letting your monitoring tool quick know and restart a given container. [[1]](https://docs.docker.com/engine/reference/builder/#healthcheck)
Most modern orchestration tools (ECS, K8S, etc) can read this health status and automatically restart the service. [[2]](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request) [[3]](https://docs.docker.com/config/daemon/prometheus/)

**Additional Information**
If the application is still responsive (working normally), a `docker ps` would indicate the healthy status:
``` bash
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                   PORTS               NAMES
e2722770cc7f        smartcontract/chainlink:latest   "chainlink local node"   3 minutes ago       Up 3 minutes (healthy)                       chainlink
```

**Comment by hershkoy** [comment]
I want this too

**Comment by PatrickAlphaC** [comment]
Thanks for this issue @willianpaixao! Added it as an `enhancement` and `good first issue`

**Comment by samsondav** [comment]
Fixed in 1.x and up, we now have `/readyz` and `/health` endpoints.

**Comment by willianpaixao** [comment]
Hi @samsondav I'm glad to see this issue being addressed.

Out of curiosity, back in time [you said](https://github.com/smartcontractkit/chainlink/pull/3632#issuecomment-795899516) this would never be implemented and not everyone uses Docker, what has changed since?
