### ISSUE TITLE
[FEAT] Docker images tags

### ISSUE THREAD

**Issue by willianpaixao** [smartcontractkit/chainlink#3668]
**Description**
Change how the pipeline labels the newly deployed Docker image.
I propose the tag to be the ChainLink's semantic versioning (v0.9.4 at the time of writing).
Git commit hash, build date, branch, or any additional information can be easily added as labels, and there's a [standard](https://github.com/opencontainers/image-spec/blob/master/annotations.md) for that too.

**Motivation**
Currently, the label follows the pattern _[branch].[git commit hash]_ and although this enables traceability, it not human friendly and also requires a double check on which ChainLink version is that. In practice makes people mostly pull _latest_ and that's bad for production environments.

**Justification**
1. When pulling the Docker image, it's good to know exactly which ChainLink version you're using.
2. Git commit hashes are not human friendly, semantic versioning is.
3. Allows metadata to be inserted into the image and can be queried with standard tools.

**Additional Information**
Open Containers has standardized this process and many DevOps tools follow those guidelines. [[1]](https://github.com/opencontainers/image-spec/blob/master/annotations.md)

**Comment by PatrickAlphaC** [comment]
Thanks for this issue @willianpaixao. When pulling a new docker image, is `smartcontract/chainlink:0.9.4` not what you're looking for?

**Comment by willianpaixao** [comment]
@PatrickAlphaC I feel stupid, that day I scrolled like two pages and didn't see the `0.9.4` tag. So yeah, you're right.
But also my issue remains, pushing `branch.hash` to the official repo is not a good practice for a few reasons, but especially because it confuses people and induces them to use not stable builds.

Information like commit hash, build time, branch, and commit author can be embedded inside the Docker image using the technique described in my original comment above.

So my main take would be only pushing to hub.docker.com "more stable" releases, like candidate, v9.x.x, etc but not every push to develop branch.

**Comment by PatrickAlphaC** [comment]
No worries!

And ok, I see what you're saying. So the tags right now are a mix of releases and commits: https://hub.docker.com/r/smartcontract/chainlink/tags?page=1&ordering=last_updated

You're looking to get rid of the ones referencing commits?

**Comment by willianpaixao** [comment]
Yes, at some point in time this was fixed. Closing the issue.
