### ISSUE TITLE
[FEAT] Add Flux Monitor address label to Prometheus metrics

### ISSUE THREAD

**Issue by franono** [smartcontractkit/chainlink#3683]
**Description**
At the moment the flux_monitor metrics have a label called job_spec_id. My idea is to also add the job's respective flux monitor contract address.

Currently:
flux_monitor_reported_round{job_spec_id="0f9c2a2119a941a39d85e0ca2b1b5ce7"} 213
Proposed:
flux_monitor_reported_round{job_spec_id="0f9c2a2119a941a39d85e0ca2b1b5ce7",address="0x123..."} 213

**Motivation**
- Easy way to get a list of flux monitor addresses your node is interacting with, through the Prometheus endpoint
- Detect new fm contracts we're interacting with
- Very useful for comparing the Chainlink node's Prometheus metrics perspective to querying the FM contracts ABI separately
- Ability to monitor a node's participation in aggregator contracts from just the FM addresses, without the need to monitor the individual node address

**Justification**
Other ways include querying the Chainlink node using API and password, or querying Etherscan. Prometheus metrics are the safest and most efficient.

**Additional Information**
From my experience this will be helpful for having more efficient monitoring tools.

**Comment by PatrickAlphaC** [comment]
Thanks for this issue @franono. Sounds like a nice improvement. If someone wants to tackle it I think this looks like a pretty good first issue.

**Comment by swiftraptor** [comment]
hi @PatrickAlphaC 
I would be interested in giving this a crack (if possible)

**Comment by PatrickAlphaC** [comment]
@swiftraptor this appears to be only additive. The thing to consider is if we dump too much logging into that field. But I think this would be helpful. Yes would love to see your attempt.

**Comment by jakedamon** [comment]
@PatrickAlphaC Is this still a valid issue to tackle?

**Comment by pappas999** [comment]
Hi @jakedamon , my understanding is all the flux code associated with the flux aggregators is now deprecated due to OCR. I'll check with Patrick is the flux monitor metrics are still being used or not, and get back to you

**Comment by PatrickAlphaC** [comment]
Hi @franono is this still a valid issue?

**Comment by franono** [comment]
I don't think this is necessary anymore @PatrickAlphaC
