### ISSUE TITLE
[SMRT] Namespace conflicts of SafeMath methods

### ISSUE THREAD

**Issue by magamongo** [smartcontractkit/chainlink#3685]
**Description**
When I write an ERC20 contract inheriting `ChainlinkClient`, SafeMath methods (e.g. `sub`, `mul`) prevent the contract from being compiled because their names conflict with the methods' names in `ChainlinkClient  > SafeMathChainlink`.
It would be beneficial to consider fixing this issue because such use cases (i.e. Chainlink-connected ERC20 tokens) will possibly be more common.
As a workaround, I am now considering to clone `ChainlinkClient.sol` in my project and remove the inheritance of `SafeMathChainlink` from it.

**Basic Information**
- Dependencies
  - "@openzeppelin/contracts": "3.2.0",
  - "@chainlink/contracts": "0.0.11"
- Solidity compiler version: 0.6.12

**Steps to Reproduce**

The snippet below reproduces the issue.
`.mul()` throws: `TypeError: Member "mul" not unique after argument-dependent lookup in uint256.`

```
pragma solidity 0.6.12;

import "@openzeppelin/contracts/token/ERC20/ERC20Capped.sol";
import "@openzeppelin/contracts/proxy/Initializable.sol";
import "@chainlink/contracts/src/v0.6/ChainlinkClient.sol";

contract XToken is ERC20Capped, Initializable, ChainlinkClient {
    
    uint256 public aa;

    constructor(string memory _name,
    string memory _symbol,
    uint256 _salesCap
    ) ERC20(_name, _symbol) ERC20Capped(_salesCap) public {}

    function initialize(uint256 _a) initializer external {
        // TypeError: Member "mul" not unique after argument-dependent lookup in uint256.
        // aa = cap().mul(_a);
        aa = cap().mul(_a);
    }

}
```

**Comment by PatrickAlphaC** [comment]
Thanks for opening this. This is something that will be looked into.

**Comment by magamongo** [comment]
FYI: This workaround works for me.
>As a workaround, I am now considering to clone ChainlinkClient.sol in my project and remove the inheritance of SafeMathChainlink from it.

**Comment by alexroan** [comment]
I think your workaround @magamongo is more of a solution than a workaround. `SafeMathChainlink` can be used in inheriting contracts, but it doesn't account for other 3rd party libraries and the namespaces they use.

The solution here seems to be either:
- Create your own fork of `ChainlinkClient` and alter to use `SafeMath` from OpenZeppelin (your solution)
- Or create a fork of OpenZeppelin's `ERC20` and alter to use `SafeMathChainlink`.

**Comment by PatrickAlphaC** [comment]
Just to note, this is isn't an issue in 0.7
