### ISSUE TITLE
[FEAT] Open jobs in a new tab instead of in the same one

### ISSUE THREAD

**Issue by franono** [smartcontractkit/chainlink#3686]
**Description**
With the recent jobs page update, we lost the ability to open jobs in a new tab easily by middle clicking the IDs. My idea is to be able to middle click jobs and opening them in a new tab, or if not middle-clickable, they can instead just open in a new tab by default.

**Motivation**
Much easier to open many jobs at once and inspect their JSON / runs.

**Justification**
Not too big of a change for convenience.

**Additional Information**
[replace this line with any additional information you would like to provide, such as examples or screenshots of similar features]

**Comment by PatrickAlphaC** [comment]
Thanks for opening this, I think you bring up a great point.

**Comment by PatrickAlphaC** [comment]
Will be adding this to an upcoming release

**Comment by DeividasK** [comment]
@franono @PatrickAlphaC thanks for openings! Should be an easy fix, will try to get it in ASAP so it's available in the next release.

**Comment by franono** [comment]
Awesome, thanks @PatrickAlphaC and @DeividasK
