### ISSUE TITLE
Smartcontractkit doesn't unbox on Windows 10

### ISSUE THREAD

**Issue by conceptstom** [smartcontractkit/chainlink#3759]
Hello
When trying to unbox the Chainlink Smartcontractkit truffle unbox smartcontractkit/box
on a Windows 10 machine i get this result: 
Unbox failed!
Error: Command failed: bash unbox.sh && rm unbox.sh && npm install
'bash' is not recognized as an internal or external command,
operable program or batch file.
After this when trying to run: Npm test i get this result:> @chainlink/box@0.6.0 test D:\Chainlink
> NODE_ENV=test npx truffle test
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.

**Comment by PatrickAlphaC** [comment]
This is an issue with Windows not being able to run bash commands. Can you try `truffle init` first?

This may also help. 
https://stackoverflow.com/questions/1098786/run-bash-script-from-windows-powershell

And last but not least, if you can, installing a Linux VM is something to consider too.

**Comment by conceptstom** [comment]
Thank you for reply!

I did a truffle.init, with no owerwriting of contract, migration, test etc files.
Then i tried the advices in the post of stackoverflow to run a bash-script in a windows-powershell.
I do have the Git Bash installed and tried to add this to the windows env. path: C:\Program Files\git\bin\bash.
But when i try run the Git-bash: bash unbox.sh i get this result:
bash : The term 'bash' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
 spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ bash unbox.sh
This is strange because i've added the correct path to bash in the env. variable in Windows.

**Comment by PatrickAlphaC** [comment]
Hmm..... Yeah that's the answer. You'll need to figure out how to get bash to run on powershell. Not sure many are developing in a windows environment. 

If you want a workaround, you could just clone this repo: https://github.com/smartcontractkit/box

**Comment by conceptstom** [comment]
> Hmm..... Yeah that's the answer. You'll need to figure out how to get bash to run on powershell. Not sure many are developing in a windows environment.
> 
> If you want a workaround, you could just clone this repo: https://github.com/smartcontractkit/box

The soloution, workaround is to you use Git bash here(windows shell) in Git. From within this shell you can run the shell scripts properly after the cloning the repo you stated above :-)
The unbox and run test runs without failures.

**Comment by PatrickAlphaC** [comment]
ohhh!!! This is great to know!

Could you type the commands here so others can find them exactly?

**Comment by conceptstom** [comment]
> ohhh!!! This is great to know!
> 
> Could you type the commands here so others can find them exactly?

Yes! Just follow the instructions by Truffle Chainlink Box docs: [](https://www.trufflesuite.com/boxes/box)

**Comment by PatrickAlphaC** [comment]
What does the git  bash look like though?

**Comment by conceptstom** [comment]
> What does the git bash look like though?

Look here: https://gitforwindows.org/index.html
