### ISSUE TITLE
[SMRT] Easy to misconfigure VRFConsumers keyHash

### ISSUE THREAD

**Issue by transferAndCall** [smartcontractkit/chainlink#3785]
**Description**
When writing a contract which makes use of VRF on mainnet, there is no mainnet information available in the [VRF docs](https://docs.chain.link/docs/vrf-contracts). This forces users to find the VRFCoordinator on their own, along with the keyHash and fee amount to use. When doing so, it's very easy to mix up the keyHash and the jobID for a request.

This is because the jobID is indexed, but is 3rd in the list of event parameters.
![Screenshot_20201215_163916](https://user-images.githubusercontent.com/70107144/102281377-61e0d900-3ef4-11eb-86d2-b9ede624ed2b.png)

What happens on Etherscan is it will make the user think that the jobID is actually the keyHash, since it's the first thing they see when looking at the event parameters.
![Screenshot_20201215_164158](https://user-images.githubusercontent.com/70107144/102281450-905eb400-3ef4-11eb-87d5-4df2f76e0012.png)

At a glance, I map keyHash to the value in topic1 since that's what I see first in the list of parameters.

Typically it's the indexed parameters that are listed first with events. So the suggested solution to this would be to move the `bytes32 indexed jobID,` to be the first parameter, and adjust the usage of the RandomnessRequest event accordingly. It would also be great to list the mainnet information on the docs.

**Basic Information**
- [VRFCoordinator contract events](https://etherscan.io/address/0xf0d54349aDdcf704F77AE15b96510dEA15cb7952#events)
- [VRFCoordinator contract source](https://github.com/smartcontractkit/chainlink/blob/develop/evm-contracts/src/v0.6/VRFCoordinator.sol#L62)

**Comment by PatrickAlphaC** [comment]
Thanks @transferAndCall for this issue!

For VRF documentation, at the moment we are having projects reach out to vrf@chain.link to get that, as it's still a bit tricky to set up correctly. 

The second piece about the parameters not indexed correctly looks really important, I've added it to the [pivotal tracker](https://www.pivotaltracker.com/n/projects/2441917/stories/176189839) and marked it as a bug here.

**Comment by se3000** [comment]
Thanks for the feedback @transferAndCall! Re VRF event topic ordering: The method is used by consumers of data and the log event is intended to be used by a different role, producers of the data. I see why it could be confusing, especially if you're using the log to debug, but they are intended for different roles. (I believe consistent ordering would save a small amount of gas too.)

I think you're right that ideally we would have them match but having talked this over with the team, the migration to support both the old log type and your suggested ordering doesn't seem worth the time and effort compared to working on larger improvements. We plan to roll out more versions of VRF, and when we do we'll make a point of trying to keep the parameters symmetrical for all the different roles. Until then, I think it best to leave as is.

I'm going to close this for now, but feel free to reopen if you have other issues relating to this.
