### ISSUE TITLE
[DEVEL] Bumping @chainlink/contracts to incorporate latest prod-ready upstream changes

### ISSUE THREAD

**Issue by wbnns** [smartcontractkit/chainlink#3803]
**Description**
Since it's been a couple of months following the release of `0.0.11`, was hoping you all could please bump it to incorporate the latest upstream changes that are production-ready here on the repository.

**Additional Information**
:point_right: [@chainlink/contracts on npm](https://www.npmjs.com/package/@chainlink/contracts)

Thanks in advance and happy holidays!

**Comment by PatrickAlphaC** [comment]
Happy holidays to you too!

It looks like that link is already bumped to 0.0.11, are you looking for it bumped someplace else?

**Comment by wbnns** [comment]
@PatrickAlphaC 

Hey, thanks so much for the quick reply. Apologies, I meant prod-ready changes since `0.0.11` that have happened in the last couple of months. So in other words, a new point release for things since then.

**Comment by PatrickAlphaC** [comment]
Thanks for clarifying! Will add this to the list.

**Comment by wbnns** [comment]
Ok, cool. Thanks!

**Comment by se3000** [comment]
We bumped this and released a new package last week: https://www.npmjs.com/package/@chainlink/contracts

**Comment by wbnns** [comment]
@se3000 Thanks! Cheers.
