### ISSUE TITLE
[FEAT] No event fired when new Aggregator is set in proxy

### ISSUE THREAD

**Issue by benesjan** [smartcontractkit/chainlink#3855]
**Description**
There is no event fired when new Aggregator is set on the [AggregatorProxy.sol](https://github.com/smartcontractkit/chainlink/blob/develop/evm-contracts/src/v0.6/AggregatorProxy.sol).

**Motivation**
At Maple we want to aggregate prices in our subgraph. For that, we will use the AnswerUpdated event on the Aggregator contract. The issue we are facing is that if new Aggregator is set on the AggregatorProxy, we have no way how to automatically point our subgraph to that new Aggregator. Firing an event with the address of the new Aggregator deployment would solve it.

The event could for example have the following signature:
`AggregatorSet(indexed address)`

**Comment by PatrickAlphaC** [comment]
Interesting idea! I'll add it to the queue for review.

**Comment by alexroan** [comment]
Now that we use ENS to manage our Price Feed addresses, you can listen to `AddrChanged` events on your target feed. Read more about it here: https://docs.chain.link/docs/ens#listening-for-address-changes

**Comment by benesjan** [comment]
> Hey @benesjan, now that we use ENS to manage our Price Feed addresses, you can listen to `AddrChanged` events on your target feed. Read more about it here: https://docs.chain.link/docs/ens#listening-for-address-changes

That is a clever solution. Thank you
