### ISSUE TITLE
README incomprehensible sentence (?)

### ISSUE THREAD

**Issue by maxnth** [smartcontractkit/chainlink#3857]
Maybe this is caused by me not being a native speaker but the following sentence in the README under the section `Configure`  seems to be mixed up a bit.

`You can configure your node's behavior by setting environment variables which can be, along with default values that get used if no corresponding environment variable is found.`

**Comment by PatrickAlphaC** [comment]
Thanks for making this issue! You're right, the English is a little off, it should be a quick fix.

**Comment by sexylexy69** [comment]
Idk**

**Comment by PatrickAlphaC** [comment]
Addressed in https://github.com/smartcontractkit/chainlink/pull/3885
