### ISSUE TITLE
Relation"migrations" not found for German language

### ISSUE THREAD

**Issue by pabatribick** [smartcontractkit/chainlink#3876]
Hey,

I run in trouble with starting chainlink:

Unable to initialize ORM: pq: Relations >migrations< not found
error determining migrations count.

What happend here?
![grafik](https://user-images.githubusercontent.com/11978788/105045220-f4cae100-5a67-11eb-84b2-b65e36a7c1be.png)

**Comment by PatrickAlphaC** [comment]
It looks like something is wrong with your database. Could you create a new database?

And could you use version `0.9.4` of Chainlink?

**Comment by PatrickAlphaC** [comment]
After, could you leave a comment on this SO question? https://stackoverflow.com/questions/64380656/chainlink-node-how-might-i-approach-fixing-unable-to-lock-orm-errors

**Comment by pabatribick** [comment]
> 
> 
> It looks like something is wrong with your database. Could you create a new database?
> 
> And could you use version `0.9.4` of Chainlink?

New Database and user created and used version 0.9.4 of chainlink, doesn't work. I got the same errors like above.

Database was installed without Docker, because it throws much errors from docker and isn't useable with that. It was installed via apt-get on my Debian 10 OS.

Tried this since 3 Days, and I wasted so much of time to run that. Is that not possible, to create an ready to use Linux-Image ? That would help much users.

![grafik](https://user-images.githubusercontent.com/11978788/105065136-d2dc5900-5a7d-11eb-815f-ab03e5b335fe.png)

**Comment by PatrickAlphaC** [comment]
You shouldn't need docker to install the database. That issue "Relation migrations existiert nicht" after a quick google looks like you might not have permissions on the user you're using. 

https://github.com/concourse/concourse/issues/4689

Could you try making the user a superuser or admin?

**Comment by pabatribick** [comment]
Got it to work with the datbase now, thank! Iit was an permission problem. Now I got an HTTP status 401 Unauthorized errror after typing in my E-Mail:

![grafik](https://user-images.githubusercontent.com/11978788/105192117-15626c00-5b38-11eb-9d20-bf293a8a5877.png)

What ist that meaning now?

**Comment by pabatribick** [comment]
Thank you very much! It works and it was an permission problem. Now it outputs me some errors, but the program didn't cancel the process:

![grafik](https://user-images.githubusercontent.com/11978788/105194304-baca0f80-5b39-11eb-8290-825d03deb86d.png)

Can I ignore that or should I change somewhat?

**Comment by pabatribick** [comment]
Now I figured out, if i connect a remote database, the table "migrations" exists. If i connect it local on my Debian machine, its broken see (How to fix that), and its not a permission issue:

![grafik](https://user-images.githubusercontent.com/11978788/105217218-de01b880-5b53-11eb-8e3b-ee11f33db9ca.png)

If I export this online database and add this migration data into my local database, it will work then, however it shouldn't be.

**Comment by PatrickAlphaC** [comment]
Interesting... it looks like there might be a language issue. 

I think it's looking for the specific "relation *? does not exist"
https://github.com/smartcontractkit/chainlink/blob/49a8cbd0ee235d1c278d8c7fccb3fe0460324738/core/store/migrations/migrate.go#L545

Your online database is using English instead of German. While your local database is using German. 

Changing your language to English might fix for local use. I'll flag this to the team to see if we can make it more international. Thanks for the issue!

**Comment by archseer** [comment]
The migration system has been overhauled so this should no longer happen.
