### ISSUE TITLE
[DEVEL] Cannot name parameter "address" when using custom External Adapter

### ISSUE THREAD

**Issue by andrewhong5297** [smartcontractkit/chainlink#3933]
**Description**
I created an external adapter (https://github.com/andrewhong5297/openweathermap_cl_ea) where I named one of my `customParams` as `"address"` in the index.js file. I then passed this in to my query using `validator.data.address`, which after days of debugging found out this is reserved for the oracle address. 

To note, this works fine when testing EA in localhost but runs into issues when on a bridge and trying to access in solidity with `req.add("address",stringAddress)`. 

**Your Environment**
N/A

**Basic Information**
It is solved now after I changed my customParam to "dog", but wanted to note this to save other future headache. 

**Steps to Reproduce**
Replace customParams `"dog"` with `"address"`, and `validator.data.dog` to `validator.data.address` in index.js file of repo then host it on a bridge and try to request from solidity to reproduce.

**Comment by PatrickAlphaC** [comment]
Thanks Andrew! Will add this to the list.

**Comment by PatrickAlphaC** [comment]
To add some context:

If someone passes a parameter via `req.add("address", "0x9234....");` in solidity, it will be overwritten in the jobspec via:

```"initiators": [
    {
      "type": "runlog",
      "params": {
"address":"0x2342342..."
      }
    }```

When parameters are thrown like this, it creates these "silent" errors.

**Comment by pappas999** [comment]
I came across this one recently as well, took me a while to figure it out. If we can't avoid the issue, would be good if we can get the initiating transaction to the oracle contract to revert with a meaningful error "address parameter name reserved" etc. The main issue is that the contract doesn't know what type of job it is (HTTP, call to an EA etc), so would need to work out if this makes sense for all oracle requests.

**Comment by PatrickAlphaC** [comment]
Closing as this was part of the old JSON job spec
