### ISSUE TITLE
[NODE] Your node is operating close to its maximum capacity and may start to miss jobs

### ISSUE THREAD

**Issue by Inbell1s** [smartcontractkit/chainlink#3978]
Headtracker is dropping head, node is overloaded and is missing jobs.

**Basic Information**
While running my node is keep getting the error:
`2021-02-17T23:03:21Z [INFO]  HeadTracker: Head 19371117 is lagging behind, there are 3 more heads in the queue. Your node is operating close to its maximum capacity and may start to miss jobs. services/head_tracker.go:90
2021-02-17T23:03:21Z [ERROR] HeadTracker: dropping head 19371114 with hash 0x96e0c64722f821d146b53d5863115eecf4c0e1ebaac88676aa8ca563b9b9e526 because queue is full. WARNING: Your node is overloaded and may start missing jobs. logger/default.go:139   stacktrace=github.com/smartcontractkit/chainlink/core/logger.Error
        /chainlink/core/logger/default.go:117
github.com/smartcontractkit/chainlink/core/logger.Errorf
        /chainlink/core/logger/default.go:139
github.com/smartcontractkit/chainlink/core/services.(*headRingBuffer).run
        /chainlink/core/services/head_tracker.go:105`

- Network: Kovan
- Blockchain Client: Parity
- Operating System:  2 GB Memory / 50 GB Disk / AMS3 - Ubuntu 20.04 (LTS) x64
- Commit: Chainlink Node 0.8.18 at commit ca268bf041700811f14c55d1852ed6a8805bd7ab
- Hosting Provider: DigitalOcean
- Startup Command: cd ~/.chainlink-kovan && docker run -d --name chainlink -p 6688:6688 -v ~/.chainlink-kovan:/chainlink -it --env-file=.env smartcontract/chainlink local n

**Comment by PatrickAlphaC** [comment]
Can you try `0.9.4` and let us know if you get the same issue?

**Comment by Inbell1s** [comment]
Hi, tried with 0.9.10 same problem, PostgreSQL 12 running atm.
Could i be the workload of the eth client and node running on 1 instance?

**Comment by PatrickAlphaC** [comment]
Thanks for making this issue! Yes, we did a little digging and it looks like this happens when there is an issue with the connection to ETH 1 or too much latency between the postgres database and ETH 1 client. Will close this issue. 

Thanks again!
