### ISSUE TITLE
[FEAT] add a mechanism to ensure fulfillRandomnessRequest are called in order

### ISSUE THREAD

**Issue by wighawag** [smartcontractkit/chainlink#3989]
**Description**
From what I gathered looking at VRFCoordinator, there is no enforcement of order for call to `fulfillRandomnessRequest`

**Motivation**
Form a smart contract client perspective when requesting a random number from the VRFCoordinator, I would like to be able to guarantee that a request made first is fullfiled first.

**Justification**
In some case the random number is used to allocate a set of resources/assets/tokens randomly to users. If no ordering is guarantee, the system can be gamed by reordering the fullfil callbacks.

**Comment by PatrickAlphaC** [comment]
Thanks for flagging this! At the moment, if you want to enforce ordering, what you can do is save the `requestId` generated by the `requestrandomness` call in a mapping. In the fulfilrandomness function, you can check the mapping to make sure that the requestId of the fulfill function is correct and have them return in the right order.

**Comment by PatrickAlphaC** [comment]
This is something can be configured by the user. Closing.

**Comment by wighawag** [comment]
This will not achieve the same result as desired in most cases.

I want to perform action in the fulfill callback as it is intended, not wait until the right callback arrive to then ensure reorder.

if I cannot have the guarantee that they arrive in order and use your suggestion, it require yet another transaction to then  perform the necessary computation to ensure ordering.

I think ordering is a pretty important matter, that it should be tackled in the VRFCoordinator itself.

The current behaviour is also not expected and new user might not be aware of it.
If this is really something you do not want to support, it should in my opinion at least be documented.

**Comment by PatrickAlphaC** [comment]
I think you bring up a very valid point. It is currently documented in the source code: https://github.com/smartcontractkit/chainlink/blob/b5a5436ad/evm-contracts/src/v0.6/VRFConsumerBase.sol#L83-L87

But yes, we will add a tag to add this to the docs.chain.link as well. We think a "security considerations" makes sense to have for this. 

Thank you for bringing up this issue!

**Comment by alexroan** [comment]
"Security Considerations" callout added to [VRF developer documentation](https://docs.chain.link/docs/get-a-random-number#random-number-consumer) with this message.
