### ISSUE TITLE
Makefile:27: recipe for target 'godep' failed

### ISSUE THREAD

**Issue by tjbronx92** [smartcontractkit/chainlink#400]
Can't finish install.

RUN:
admin@LINKnode1:~/go/src/github.com/smartcontractkit/chainlink$ make install

RESULT:
dep ensure -vendor-only
make: dep: Command not found
Makefile:27: recipe for target 'godep' failed
make: *** [godep] Error 127

Go version = go1.10.3
HOST = Ubuntu 16.04.4
dep installed via brew

Hello and thank you for your interest in Chainlink!

This issue tracker may be used to submit bug reports and feature requests. If you have a question about running a node, feel free to ask us on [Gitter](https://gitter.im/smartcontractkit-chainlink/Lobby) first, and we'll be happy to assist you.

If you came across an error while running the node, be sure to look at our [Troubleshooting](https://github.com/smartcontractkit/chainlink/wiki/Troubleshooting) page first to make sure we don't already have a documented fix. If you don't see the error listed there, please fill out as much as possible below so that we can help.

### System Information

- Network (Main net, Ropsten, etc.): 
- Ethereum client (Geth/Parity) and version: 
- Go version: 
- Host OS: 
- Commit (INFO line when starting the node): 

### Environment Variables

(Paste the output of the environment variables when running the node in debug mode here)

### Additional Information

(Only what's applicable)

- Spec:

```JSON
{}
```

- Oracle contract address: 
- Transaction ID:

**Comment by thodges-gh** [comment]
Hi @tjbronx92, it looks like however brew installed `dep`, it's not in your path. You can check this by running `dep version` by itself and seeing if it gives you system information, or if it still can't find the `dep` command. If it still can't find the path, I would install it via `go get -u github.com/golang/dep/cmd/dep`.

**Comment by thodges-gh** [comment]
@tjbronx92 were you able to add `dep` to your path?

**Comment by se3000** [comment]
No movement for over a month. Closing, assuming this is resolved. Feel free to reopen with more info.
