### ISSUE TITLE
[NODE] Lower ETH_GAS_BUMP_WEI to accommodate side chains low gas fees

### ISSUE THREAD

**Issue by franono** [smartcontractkit/chainlink#4026]
**Description**
Currently the minimum gas bump is 5 GWEI. For chains like XDAI, MATIC and BSC, it would be beneficial to have it lower considering these chains most of the time accept transactions at 1 GWEI. 

**Basic Information**
This will enable different gas fee strategies on the side chains, for example increasing 1-2 gas per bump vs a steeper 5 GWEI. This will reduce costs by node operators in the long run.

**Environment Variables**
ETH_GAS_BUMP_WEI=5000000000

**Steps to Reproduce**
Setting ETH_GAS_BUMP_WEI=5000000000 anything lower than that value results in an error.

**Additional Information**
nothing to add

**Comment by PatrickAlphaC** [comment]
@franono, thanks for this! Could you please include the error you received on this?

**Comment by franono** [comment]
@PatrickAlphaC The error is the following: `ETH_GAS_BUMP_WEI of 3000000000 Wei may not be less than the minimum allowed value of 5 GWei`
