### ISSUE TITLE
At least three feeds have the wrong "description" property. 

### ISSUE THREAD

**Issue by ZakAyesh** [smartcontractkit/chainlink#4030]
**Description**
At least three feeds have the wrong "description" property. 

**Basic Information**
This was brought to my attention from the user "Jrms" on Discord. 
Currently some feeds display the wrong description property when description() is called.
The one's that were found to be wrong were BAL/ETH, PAX/ETH, and BNB/ETH.
I took a random sample of other feeds but didn't find any others.

**Steps to Reproduce**
Go to the links below on Etherscan, click "Contract", then "Read Contract", then "4. description":
https://etherscan.io/address/0xC1438AA3823A6Ba0C159CfA8D98dF5A994bA120b#readContract
https://etherscan.io/address/0xc546d2d06144F9DD42815b8bA46Ee7B8FcAFa4a2#readContract
https://etherscan.io/address/0x3a08ebBaB125224b7b6474384Ee39fBb247D2200#readContract

**Additional Information**
Prices were correct, just descriptions were wrong

**Comment by ZakAyesh** [comment]
To make things more clear I added what each contract is supposed to read.

Supposed to be BAL/ETH:
https://etherscan.io/address/0xC1438AA3823A6Ba0C159CfA8D98dF5A994bA120b#readContract

Supposed to be BNB/ETH:
https://etherscan.io/address/0xc546d2d06144F9DD42815b8bA46Ee7B8FcAFa4a2#readContract

Supposed to be PAX/ETH:
https://etherscan.io/address/0x3a08ebBaB125224b7b6474384Ee39fBb247D2200#readContract

**Comment by nzleet** [comment]
Hi @ZakAyesh 

We're aware of this issue and are planning to redeploy these 3 feeds with our next batch of OCR migrations. Thanks for being so diligent!
