### ISSUE TITLE
[NODE] Unable to create deviation checker

### ISSUE THREAD

**Issue by Inbell1s** [smartcontractkit/chainlink#4032]
While trying to create a Fluxmonitor Job on Chainlink 0.10.1, the Dashboard errors with: Unable to create deviation checker. The console outputs the following:

`2021-03-05T14:33:14Z [ERROR] factory unable to create checker: VM execution error. logger/default.go:141
stacktrace=github.com/smartcontractkit/chainlink/core/logger.ErrorIf /chainlink/core/logger/default.go:141`

Any suggestions on what could cause this problem?

**Comment by PatrickAlphaC** [comment]
Thanks for adding this! Could you please include your job spec?

**Comment by Inbell1s** [comment]
{
    "name": "",
    "initiators": [
        {
            "type": "fluxmonitor",
            "params": {
                "address": "",
                "requestData": {
                    "data": {
                        "from": "",
                        "to": ""
                    }
                },
                "feeds": [
                    {
                        "bridge": "cgea"
                    },
                    {
                        "bridge": "polygonea"
                    },
                    {
                        "bridge": "avea"
                    }
                ],
                "threshold": 1,
                "absoluteThreshold": 0,
                "precision": 18,
                "pollTimer": {
                    "period": "1m0s"
                },
                "idleTimer": {
                    "duration": "5m0s"
                }
            }
        }
    ],
    "tasks": [
        {
            "type": "copy",
            "params": {
                "path": [
                    "result"
                ]
            }
        },
        {
            "type": "multiply",
            "params": {
                "times": 1000000000
            }
        },
        {
            "type": "ethuint256"
        },
        {
            "type": "ethtx"
        }
    ]
}

**Comment by PatrickAlphaC** [comment]
```
"from": "",
"to": ""
```
It looks like your parameters there are blank. Could you test the external adapters with a web job? 

https://docs.chain.link/docs/node-operators#testing-external-adapters-and-bridges

**Comment by PatrickAlphaC** [comment]
I'm going to close this due to inactivity. Let me know if you feel otherwise.
