### ISSUE TITLE
[NODE] "error": "Error parsing CBOR: cbor: unexpected "break" code"

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/chainlink#4064]
**Description**
When adding a big `uint256` to the request object in a runlog job, like so

```
request.addUint("random_number", randomNumber);
```

Get this error on the node side:

```
{
  "id": "3dc728b45510447393f89a919261983f",
  "jobId": "6592206f9ffe45cdbe900f2e79d90b09",
  "result": {
    "data": {
    },
    "error": "Error parsing CBOR: cbor: unexpected "break" code"
  },
  "status": "errored",
  "taskRuns": [
  ],
  "createdAt": "2021-03-12T15:39:00.353174Z",
  "finishedAt": "2021-03-12T15:39:00.353183Z",
  "updatedAt": "2021-03-12T15:39:00.353174Z",
  "creationHeight": null,
  "observedHeight": null,
  "initiator": {
    "type": "runlog",
    "params": {
      "address": "0xaa1dc356dc4b18f30c347798fd5379f3d77abc5b"
    }
  },
  "type": "Direct request job run"
}
```

If replaced with a "simple" `uint256`, it works as expected:

```
request.addUint("random_number", 123);
```

**Basic Information**
- Network: Kovan
- Blockchain Client: Fiews 😁
- Go Version: idk
- Operating System: Ubuntu 18.04.4 LTS
- Commit: Starting Chainlink Node 0.9.8 at commit 8133319f04232bad44c589ae856841c365ed4d16
- Hosting Provider: GCP
- Startup Command: chainlink local n

**Steps to Reproduce**
EDITED:

1. Run the code in remix from this example:
https://docs.chain.link/docs/make-a-http-get-request

2. Change the line:
```
function requestVolumeData() public returns (bytes32 requestId) 
```
to
```
function requestVolumeData(uint256 massive_number) public returns (bytes32 requestId) 
```

3. Somewhere in the function add:

request.addUint("random_key", massive_number);

4. Change the oracle and jobid to one you are expecting so you can see it on your node

5. Make API call (deploy contract, fund contract, hit `requestVolumeData`

**Comment by PatrickAlphaC** [comment]
browser/gists/8a173a65099261582a652ba18b7d96c1/APIConsumer.sol:57:38: TypeError: Invalid type for argument in function call. Invalid implicit conversion from int_const 1234...(76 digits omitted)...1234 to int256 requested. request.addInt("random_key", 123456789012345678901234567890123456789012345678901234567890123456789012345678901234); ^----------------------------------------------------------------------------------^

Got it. Looks like we can't send stuff that's too big

**Comment by PatrickAlphaC** [comment]
Got it, looks like the `int` needs to be smaller than a certain size. If we have a variable set as the input, we can accidentally add a big number and the node gets confused.

**Comment by PatrickAlphaC** [comment]
The biggest `uint256` I got to work was this many decimals: `115792089237316191`

**Comment by PatrickAlphaC** [comment]
It also seems to "get stuck" and not process the next request.

**Comment by j16r** [comment]
This contract uses a version of CBOR that does not support encoding of "bignums" see here https://remix.ethereum.org/#version=soljson-v0.6.7+commit.b8d736ae.js&optimize=false&evmVersion=null&gist=8a173a65099261582a652ba18b7d96c1&runs=200

However v0.7 was updated to include this support, are you able to use that instead?

**Comment by boxhock** [comment]
Hey guys, any update on this? We just encountered this with v0.7.x Solidity contracts as well. The fix for us was to replace a very large uint256 with bytes.

**Comment by PatrickAlphaC** [comment]
FYI, I had a call with @j16r and we went over it, yes it's still there at the moment.

**Comment by aelmanaa** [comment]
Hello,

don't think we have an error with massive numbers with the new versions of the node but with precision. just tested it with node 1.2.1

Here is a smart contract that asks for the mean of 2 int256: [contract](https://remix.ethereum.org/#version=soljson-v0.8.7+commit.e28d00a7.js&optimize=false&runs=200&gist=09bc7bdf574d04991a136090b3166468&evmVersion=null) 

Here is the TOML job

```
type = "directrequest"
schemaVersion = 1
name = "Mean 2 numbers - (TOML)"
externalJobID = "811ec01f-068c-4641-9b5d-d88c67645458"
maxTaskDuration = "0s"
contractAddress = "0x74EcC8Bdeb76F2C6760eD2dc8A46ca5e581fA656"
minIncomingConfirmations = 0
observationSource = """
    decode_log   [type="ethabidecodelog"
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]

    decode_cbor  [type="cborparse" data="$(decode_log.data)"]
    mean [type="mean"
              values=<[ $(decode_cbor.number1), $(decode_cbor.number2)]>
              precision=2]

    encode_data  [type="ethabiencode" abi="(bytes32 requestId, int256 value)" data="{ \\"requestId\\": $(decode_log.requestId), \\"value\\": $(mean) }"]
    encode_tx    [type="ethabiencode"
                  abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes calldata data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\":   $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"
                  ]
    submit_tx    [type="ethtx" to="0x74EcC8Bdeb76F2C6760eD2dc8A46ca5e581fA656" data="$(encode_tx)"]

    decode_log -> decode_cbor -> mean -> encode_data -> encode_tx -> submit_tx
"""
```

Did a test requesting the mean of 2 massive numbers:

- 340282366920938463463374607431768211455 
- 340282366920938463463374607431768211450

got the answer:
- 340282366920938500000000000000000000000

the result is wrong. you will lose precision after some digits.

For instance:
- mean of 200000000000000000000 & 500000000000000000000 --> 350000000000000000000 (OK)
- mean of 200000000000000000020 & 200000000000000000050 --> 200000000000000000000 (NOK)

then I started to decrease the number of digits until:
- mean of 200000000000000020 & 200000000000000050 --> 200000000000000045 (NOK) ; I see in the node UI that it parsed 200000000000000060 instead of 200000000000000050

then got it right with 16 digits
- mean of 20000000000000020 & 20000000000000050 --> 20000000000000035 (OK)

**Comment by PatrickAlphaC** [comment]
Going to close this for now. Looks like the newer versions don't have this issue.
