### ISSUE TITLE
[FEAT] Add docker hub tags `stable` and `candidate`

### ISSUE THREAD

**Issue by yorickdowne** [smartcontractkit/chainlink#4099]
**Description**
As a Quality of Life change and easier automation, add two docker hub tags to CICD pipeline: `stable` and `candidate`, updated to the latest release and latest candidate release, respectively.

**Motivation**
This allows for easier automation with docker-compose or k8s/k3s, since the image tag does not change. Just pull a new image when desired and restart container(s).

**Comment by PatrickAlphaC** [comment]
We actually intentionally removed such a concept. We had `latest` as your `stable` and `dev` as your `candidate`. The thought is that running on the `latest` branch is only the `latest` branch if you always pull before you run. If you always pull before you run, you could hit some bumps in your process you didn't expect. 

For more information: https://vsupalov.com/docker-latest-tag/
