### ISSUE TITLE
[NODE] MINIMUM_CONTRACT_PAYMENT defaults to 1 LINK / Kovan nodes don't respond to job requests

### ISSUE THREAD

**Issue by Linkriver** [smartcontractkit/chainlink#4119]
**Description**
About one week ago, serveral independent node operators encountered issues with their Kovan nodes not responding to job requests without having changed any configs. The oracle smart contracts received the LINK payment as usual, but didn't initiate job runs and therefore didn't get any data off-chain data into the consumer smart contracts.

**Basic Information**
The node environmental file's variable MINIMUM_CONTRACT_PAYMENT used to be displayed as 
"1000000000000000000", equaling 1 LINK. It has now changed to "1.000000000000000000".

**Environment Variables**
Default value when initializaing the Chainlink node:
MINIMUM_CONTRACT_PAYMENT: "1.000000000000000000" (1 LINK)

Setting the value of the MINIMUM_CONTRACT_PAYMENT variable in the node's environmental file to "0.1" and restarting the deployment results in the following:

Initialization logs display: MINIMUM_CONTRACT_PAYMENT:  "0.100000000000000000" (0.1 LINK)
environmental file displays: MINIMUM_CONTRACT_PAYMENT: "0.1" (0.1 LINK)
GUI/configuration displays: MINIMUM_CONTRACT_PAYMENT: "1000000000000000000" (1 LINK)

it's misleading to use a decimal resulting in a correct .env and log entry not equaling the actual node's config

setting the value in the .env to "10000000000000000" (0.01 LINK):

Initialization logs: MINIMUM_CONTRACT_PAYMENT:  "0.010000000000000000" (0.01 LINK) 

environmental file: MINIMUM_CONTRACT_PAYMENT: "10000000000000000" (0.01 LINK)

GUI/configuration: MINIMUM_CONTRACT_PAYMENT: "10000000000000000" (0.01 LINK)

it should be avoided to use a "." for setting the value, otherwise the value defaults to 1 LINK and all job requests with an 
oracle payment <1 LINK won't be fulfilled by the node.

**Comment by vkomodey** [comment]
Maybe it is related to this, I don't know. I'm running chainlink node for the kovan testnet and my default MINIMUM_CONTRACT_PAYMENT equals to 1 LINK. So I tried to change it to 0.1 LINK(by setting MINIMUM_CONTRACT_PAYMENT=100000000000000000(10^17) and restarting the node) - and nothing happened. Node admin page shows me that MINIMUM_CONTRACT_PAYMENT equals 10^18

**Comment by PatrickAlphaC** [comment]
Thanks for this issue! We are investigating.

**Comment by karthedew** [comment]
Came here for the same issue as I was experiencing default 1 LINK fee on Kovan as well.

**Comment by samsondav** [comment]
Fixed in 1.1.x branch
