### ISSUE TITLE
[NODE] ORACLE_CONTRACT_ADDRESS shown in UI Configuration page

### ISSUE THREAD

**Issue by yorickdowne** [smartcontractkit/chainlink#4123]
**Description**
The Web UI configuration page shows an entry ORACLE_CONTRACT_ADDRESS, this should now be OPERATOR_CONTRACT_ADDRESS.

The node ignores an env variable named ORACLE_CONTRACT_ADDRESS and correctly accepts OPERATOR_CONTRACT_ADDRESS, the value of which will be displayed as ORACLE_CONTRACT_ADDRESS in UI.

I believe the name of the environment variable was changed (recently?), just the UI wasn't.

**Basic Information**

- Operating System: Ubuntu 20.04
- Commit: Chainlink Node 0.10.3 at commit 5dbbc21f13fa00ee724c439273156834c45ab93e

**Comment by PatrickAlphaC** [comment]
Thanks for making this issue! We are investigating.

**Comment by samsondav** [comment]
This env var no longer exists as of 1.1.x and up.
