### ISSUE TITLE
[NODE] `chainlink admin login` does not work when TLS is enabled

### ISSUE THREAD

**Issue by yorickdowne** [smartcontractkit/chainlink#4127]
**Description**
After `docker exec -it CONTAINERNAME /bin/bash`, executing `chainlink admin login -f /secrets/apicredentials.txt` fails on a TLS-enabled node with:

```
chainlink@0558505e8b86:/home/root$ chainlink admin login -f /secrets/apicredentials.txt
Post "https://localhost:6688/sessions": http: server gave HTTP response to HTTPS client
```

This is with `CHAINLINK_PORT=6688`, `CHAINLINK_TLS_PORT=8443` and `CHAINLINK_TLS_REDIRECT=true`

For testing purposes I set `CHAINLINK_PORT` to `8443`, and got the same exact error, still connecting to localhost:6688, suggesting that in addition, this command does not use CHAINLINK_PORT to determine what to connect to: 6688 might be hardcoded.

Expected behavior: Connects to `http://localhost:${CHAINLINK_PORT}` when TLS not enabled; and `https://localhost:${CHAINLINK_TLS_PORT}` when it is

**Basic Information**

- Operating System: Ubuntu 20.04 LTS
- Commit: Chainlink Node 0.10.3 at commit 5dbbc21f13fa00ee724c439273156834c45ab93e

**Environment Variables**

```
CHAINLINK_PORT=6688
TLS_KEY_PATH=/secrets/tls/server.key
CHAINLINK_TLS_REDIRECT=true
HOSTNAME=0558505e8b86
MINIMUM_CONTRACT_PAYMENT=100000000000000000
DOCKERIZE_VERSION=v0.6.1
DATABASE_TIMEOUT=0
CHAINLINK_TLS_PORT=8443
ETH_URL=wss://kovan.infura.io/ws/v3/ProjectID
LOG_LEVEL=info
MIN_OUTGOING_CONFIRMATIONS=2
ROOT=/var/lib/chainlink
PWD=/home/root
HOME=/home/chainlink
DEBIAN_FRONTEND=noninteractive
DATABASE_URL=postgresql://USER:PW@HOST:5432/chainlink?sslrootcert=/secrets/tls/pgsqlca.pem
OPERATOR_CONTRACT_ADDRESS=ANADDRESS
GAS_UPDATER_ENABLED=true
LINK_CONTRACT_ADDRESS=0xa36085F69e2889c224210F603D836748e7dC0088
TERM=xterm
ETH_SECONDARY_URLS=https://eth-kovan.alchemyapi.io/v2/ProjectID
ETH_CHAIN_ID=42
FEATURE_FLUX_MONITOR=true
SHLVL=1
ALLOW_ORIGINS=*
TLS_CERT_PATH=/secrets/tls/server.crt
```

**Comment by Linkriver** [comment]
In addition: It works with TLS scheme on lower Images. I tried it with 0.9.9 and it works normal also with with configured TLS_Port and TLS_Paths. It seems to be the creation of the directory /apicredentials inside of the container itself or the pointing to those credentials via the "chainlink admin login".

**Comment by PatrickAlphaC** [comment]
Thanks for this request! Asking to get some other eyes on this.

**Comment by j16r** [comment]
If you set the environment variable `CLIENT_NODE_URL` to `https://localhost:8443` (where localhost is your chainlink host) do you have any more success?

**Comment by j16r** [comment]
I am also seeing this problem with 0.9.9, the solution posted above works for that version as well.

**Comment by yorickdowne** [comment]
Hmm, that gets me rejected because the cert's not valid. Which, there is no way to get a valid cert (CloudFlare or Let's Encrypt) for localhost. The CLI needs to get a little chill about certs, and maybe try and connect to the TLS port if TLS is configured.

```
chainlink@7d1bc2735d0c:/home/root$ export CLIENT_NODE_URL=https://localhost:8443
chainlink@7d1bc2735d0c:/home/root$ chainlink admin login -f /secrets/apicredentials.txt
Post "https://localhost:8443/sessions": x509: certificate is valid for *.example.com, example.com, not localhost
```

**Comment by j16r** [comment]
It looks like it's actually connecting to the TLS port as configured from the above message, but you're right in that we may want to add an option to ignore certificates if you only support TLS on localhost.

**Comment by j16r** [comment]
In the short term, would it work to set the fully qualified domain name? e.g: `export CLIENT_NODE_URL=https://my.letsencrypt.hostname` which should allow cert validation to succeed.

**Comment by yorickdowne** [comment]
That bears testing. In my current setup it'd fail, because 8443 has been restricted to not be available "on the Internet" as per CL guidelines. I'll see how it behaves, this could be a workaround for the few times CLI may actually be needed / wanted.

**Comment by yorickdowne** [comment]
BTW could you clarify: Is `CLIENT_NODE_URL` used just by the CLI client, or does that impact how a web browser connects to the UI? My understanding is the former.

**Comment by j16r** [comment]
Actually I'm not sure, its being shown in the GUI, but I don't think it's used there which may be creating some confusion, I'l put something in for us to take a look at tomorrow.

**Comment by j16r** [comment]
Actually it does look like it's used in the GUI! It controls where the frontend app connects.
