### ISSUE TITLE
[FEAT] Websockets for `ETH_SECONDARY_URLS`

### ISSUE THREAD

**Issue by yorickdowne** [smartcontractkit/chainlink#4130]
**Description**
Change `ETH_SECONDARY_URLS` to support, or even require, websockets.

**Motivation**
Currently `ETH_URL` requires a websockets connection, and `ETH_SECONDARY_URLS` requires a http(s) connection. Setup could be simplified if all eth1 nodes ... primary and failover ... required or supported the same connection type.

**Comment by PatrickAlphaC** [comment]
Thanks for this request! Asking to get some other eyes on this.

**Comment by se3000** [comment]
Thanks for raising the question @yorickdowne. We're finding that HTTP is more resilient than websocket connections, and are actually starting to introduce falling back to HTTP in a couple ways. For now we're going to stick with HTTP here. That may change in the future, until then PRs welcome or feel free to reopen with more details if you think we're missing something.
