### ISSUE TITLE
[SMRT] VRF for Binance Smart Chain

### ISSUE THREAD

**Issue by fkirc** [smartcontractkit/chainlink#4166]
Hi,

I noticed that https://docs.chain.link/docs/vrf-contracts contains several addresses for testnets and other nets, but I cannot find Binance Smart Chain.
Is there an address missing in the docs, or is VRF not yet available on Binance Smart Chain?

**Comment by PatrickAlphaC** [comment]
VRF is not yet available on Binance Smart Chain - it's coming soon though!
