### ISSUE TITLE
[NODE] cannot login using 'chainlink admin login' in V10

### ISSUE THREAD

**Issue by daniellenarduzzi** [smartcontractkit/chainlink#4207]
**Description**
I'm trying to login in my node created using docker and passing api and keystore credentials in the command. `chainlink admin login` responses with the following output: `open /chainlink/apicredentials: no such file or directory`
The same steps works in V9

**Basic Information**
I'm trying to login in my node created using the following command `docker run --name chainlink -p 6688:6688 -v ~/.chainlink-rinkeby:/chainlink -it --network host --env-file=.env smartcontract/chainlink:0.10.3 local n -p /chainlink/.password -a /chainlink/.api` 
then `docker exec -it chainlink /bin/bash`
and finnaly: `chainlink admin login`
and receiving the following output: `open /chainlink/apicredentials: no such file or directory`
The same steps works in V9 (then I think it's not a problem of malformed .pasword or .api files)

- Network: Rinkeby
- Blockchain Client: Infura
- Go Version: go1.16.3 linux/amd64
- Operating System: Ubuntu 20.04
- Commit: 5dbbc21f13fa00ee724c439273156834c45ab93e
- Hosting Provider: self-hosted
- Startup Command: `docker run --name chainlink -p 6688:6688 -v ~/.chainlink-rinkeby:/chainlink -it --network host --env-file=.env smartcontract/chainlink:0.10.3 local n -p /chainlink/.password -a /chainlink/.api` 

**Environment Variables**
ROOT=/chainlink
LOG_LEVEL=debug
ETH_CHAIN_ID=4
MIN_OUTGOING_CONFIRMATIONS=2
LINK_CONTRACT_ADDRESS=0x01BE23585060835E02B77ef475b0Cc51aA1e0709
CHAINLINK_TLS_PORT=0
SECURE_COOKIES=true
GAS_UPDATER_ENABLED=true
ALLOW_ORIGINS=*
FEATURE_EXTERNAL_INITIATORS=true
ETH_URL=wss://rinkeby.infura.io/ws/v3/...........................
DATABASE_URL=postgresql://postgres:docker@localhost:5432/postgres?sslmode=disable

**Steps to Reproduce**
1) `docker run --rm   --name pg-docker -e POSTGRES_PASSWORD=docker -p 5432:5432 -v $HOME/docker/volumes/postgres:/var/lib/postgresql/data  postgres`
2) create a file `~/.chainlink-rinkeby/.env` and paste this content: 

```
ROOT=/chainlink
LOG_LEVEL=debug
ETH_CHAIN_ID=4
MIN_OUTGOING_CONFIRMATIONS=2
LINK_CONTRACT_ADDRESS=0x01BE23585060835E02B77ef475b0Cc51aA1e0709
CHAINLINK_TLS_PORT=0
SECURE_COOKIES=true
GAS_UPDATER_ENABLED=true
ALLOW_ORIGINS=*
FEATURE_EXTERNAL_INITIATORS=true
ETH_URL=wss://rinkeby.infura.io/ws/v3/adc8fd4190fb4c46961721df19ef4231
 DATABASE_URL=postgresql://postgres:docker@localhost:5432/postgres?sslmode=disable
```

3) `docker run --name chainlink -p 6688:6688 -v ~/.chainlink-rinkeby:/chainlink -it --network host --env-file=.env smartcontract/chainlink:0.10.3 local n -p /chainlink/.password -a /chainlink/.api` 
4) `docker exec -it chainlink /bin/bash`
5) `chainlink admin login`

**Additional Information**

![Screenshot from 2021-04-13 06-44-27](https://user-images.githubusercontent.com/30243386/114539337-c86bce80-9c2a-11eb-8648-c528f77ec7d9.png)

**Comment by PatrickAlphaC** [comment]
Please don't post sensitive information like your infura project key in public spaces!

But that you for making this. What version of the chainlink node are you working on?

**Comment by daniellenarduzzi** [comment]
Ups, thanks for the headsup. Already deleted the keys in infura. I tried to work with V10, and this is where I got the problem. V9 works, with the same config

**Comment by PatrickAlphaC** [comment]
I get the same issue. Thanks for making this. Flagging.

**Comment by j16r** [comment]
This issue should be fixed in 0.10.4.

**Comment by yorickdowne** [comment]
This continues in 0.10.5 if TLS is configured. The CLI client tries to connect on the http port, instead of on the https port.

```
chainlink@7d1bc2735d0c:/home/root$ chainlink admin login
Enter email: tbehrens@outlook.com
Post "https://localhost:6688/sessions": http: server gave HTTP response to HTTPS client

CHAINLINK_TLS_REDIRECT=true
CHAINLINK_PORT=6688
CHAINLINK_TLS_PORT=8443
```

**Comment by samsondav** [comment]
This has been fixed, closing.
