### ISSUE TITLE
[NODE] Mumbai EthTx never goes past "Pending Outgoing Confirmations"

### ISSUE THREAD

**Issue by GalloDaSballo** [smartcontractkit/chainlink#4220]
**Description**
When using Mumbai Testnet any EthTx Job will never end and it will remain stuck at "Pending Outgoing Confirmations"
<img width="1476" alt="Screenshot 2021-04-14 at 16 39 14" src="https://user-images.githubusercontent.com/13383782/114729097-f68f0280-9d3f-11eb-8211-58117658dae1.png">

**Basic Information**
I'm using Docker (latest image)
docker run -p 6688:6688 -v chainlink -it --env-file=.env smartcontract/chainlink:0.10.4
<img width="1472" alt="Screenshot 2021-04-14 at 16 36 26" src="https://user-images.githubusercontent.com/13383782/114728645-9009e480-9d3f-11eb-8d09-932fd3b6760d.png">

- Network: 80001
- Blockchain Client: Hosted BlockVigil Nodehttps://blockvigil.com/
- Go Version: From Docker
- Operating System: Using Docker
- Commit: 0.10.4
- Hosting Provider: Locally hosted Docker Image
- Startup Command: docker run -p 6688:6688 -v chainlink -it --env-file=.env smartcontract/chainlink:0.10.4

**Environment Variables**
ROOT=/chainlink
LOG_LEVEL=debug
ETH_CHAIN_ID=80001
MIN_OUTGOING_CONFIRMATIONS=2
LINK_CONTRACT_ADDRESS=0x326C977E6efc84E512bB9C30f76E30c160eD06FB
CHAINLINK_TLS_PORT=0
SECURE_COOKIES=false
GAS_UPDATER_ENABLED=true
ALLOW_ORIGINS=*
ETH_URL= // Websocket from BlockVigil
DATABASE_URL= // PG from ElephantSQL
DATABASE_TIMEOUT=0
MINIMUM_CONTRACT_PAYMENT=100000000000000000

**Steps to Reproduce**
Set ETH_CHAIN_ID to 8001 then run a Job with the EthTx Adapter.

**Additional Information**
This issue seems to make it so that the node keeps checking on these jobs, making it more likely the node job queue become full, causing it to lag behind or not being responsive

Transactions for my node have settled properly:
<img width="1346" alt="Screenshot 2021-04-14 at 16 36 57" src="https://user-images.githubusercontent.com/13383782/114728757-ae6fe000-9d3f-11eb-8fba-7c196704cb5e.png">

Job Runs are stuck at pending in my Node Admin Panel
<img width="984" alt="Screenshot 2021-04-14 at 16 37 26" src="https://user-images.githubusercontent.com/13383782/114728785-b465c100-9d3f-11eb-9fd7-2107c03af0fe.png">

My Node Address (Mumbai):
https://explorer-mumbai.maticvigil.com/address/0xeB8f024BA189B276E6DbBa95CEb05BAc8695281a/transactions

Oracle: 
0x6bF79E7DB8E5dFCE785B607Dd4aDfe83389AE0C8

Contract using the oracle (transactions are working and going through properly):
0x3cA939BBD4B0442B0bE9E87965cF81C023cc2a03

**Comment by PatrickAlphaC** [comment]
Hi there! Thanks for this issue. Have you read this? https://stackoverflow.com/questions/62639935/chainlink-node-what-to-do-when-transactions-are-pending#:~:text=For%20pending%20Outgoing%20Confirmations%3A,gets%20set%20to%20a%20default)

**Comment by PatrickAlphaC** [comment]
Closing for now. Let us know if that doesn't solve your issue.
