### ISSUE TITLE
[DEVEL] invariant violation, expected models.Head but got <nil>

### ISSUE THREAD

**Issue by aphyr** [smartcontractkit/chainlink#4257]
**Description**

With Chainlink b8c934cf2744736a497b5ace651fd3f43df09470 and Geth 1.9.22-c71a7e26, running one bootstrap and 8 oracles in a Jepsen test environment, Chainlink nodes spontaneously crash with the following message:

```
panic: invariant violation, expected models.Head but got <nil>

goroutine 232 [running]:
github.com/smartcontractkit/chainlink/core/services/gasupdater.(*gasUpdater).runLoop(0xc0003827e0)
        /opt/chainlink/chainlink-build/core/services/gasupdater/gas_updater.go:157 +0x3ff
created by github.com/smartcontractkit/chainlink/core/services/gasupdater.(*gasUpdater).Start
        /opt/chainlink/chainlink-build/core/services/gasupdater/gas_updater.go:133 +0x29b
```

Right now, I've observed this crash running with a single Keeper job, where three upkeeps are linked to the same registry. With Jepsen performing 200 writes to Geth per second, crashes can occur in as little as seven seconds of activity, or after as long as 400 seconds. I suspect a race condition, but it's not entirely clear that this is contention-driven--raising and lowering the transaction rate doesn't necessarily raise or lower the frequency of crashes. It's reproducible at 100 geth writes/sec. It *doesn't* appear that this happens at low transaction rates--say 2/s.

**Your Environment**

All nodes in this cluster are LXC containers running Debian Buster, using Go 1.16.3 and Geth 1.9.22-c71a7e26. Geth is running in dev mode. Here's the full Chainlink env we're using:

```clj
{:datasource-latency 0,
 :prototype-version "f5495d1c8e568d9bba44229388672648d074033e",
 :chainlink-versions "b8c934cf2744736a497b5ace651fd3f43df09470",
 :env {"FEATURE_OFFCHAIN_REPORTING" "true",
       "ETH_GAS_BUMP_WEI" "5000000000",
       "SECURE_COOKIES" "false",
       "CHAINLINK_TLS_HOST" "",
       "ETH_GAS_BUMP_THRESHOLD" "12",
       "P2P_LISTEN_PORT" 12000,
       "ROOT" "./clroot",
       "JOB_PIPELINE_PARALLELISM" 16,
       "REAPER_EXPIRATION" "240h0m0s",
       "CHAINLINK_TLS_PORT" "0",
       "DATABASE_TIMEOUT" "",
       "CLIENT_NODE_URL" "http://localhost:6688",
       "DATABASE_URL" "postgresql://chainlink:chainlinkpw@localhost:5432/chainlinkdb?sslmode=disable",
       "LOG_LEVEL" "debug",
       "LOG_SQL_MIGRATIONS" "false",
       "EXPLORER_URL" "",
       "ETH_CHAIN_ID" 1337,
       "GAS_UPDATER_ENABLED" "true",
       "CHAINLINK_TX_ATTEMPT_LIMIT" "10",
       "MINIMUM_REQUEST_EXPIRATION" "300",
       "ALLOW_ORIGINS" "*",
       "ENABLE_BULLETPROOF_TX_MANAGER" "true",
       "MAX_RPC_CALLS_PER_SECOND" "500",
       "P2P_ANNOUNCE_PORT" 12000,
       "ORM_MAX_OPEN_CONNS" 20,
       "CHAINLINK_DEV" "true",
       "SESSION_TIMEOUT" "1h0m0s",
       "P2P_ANNOUNCE_IP" "192.168.122.110",
       "LOG_TO_DISK" "false",
       "DEFAULT_HTTP_ALLOW_UNRESTRICTED_NETWORK_ACCESS" "true",
       "ETH_URL" "ws://n1:8546/",
       "JSON_CONSOLE" "false",
       "LINK_CONTRACT_ADDRESS" "0xda2d1bd7db5d6d9f7a2e41a19b654be6cb48c0a7",
       "CHAINLINK_PORT" 6688,
       "LOG_SQL" "false",
       "CHAINLINK_TLS_REDIRECT" "false",
       "MIN_INCOMING_CONFIRMATIONS" "0",
       "ETH_GAS_PRICE_DEFAULT" "4000000000",
       "P2P_PEERSTORE_WRITE_INTERVAL" "2s",
       "MINIMUM_CONTRACT_PAYMENT" "0",
       "MIN_OUTGOING_CONFIRMATIONS" "2"},
 :contract nil}
```

**Steps to Reproduce**

You can reproduce this using the Chainlink Jepsen test, at version aeb566262ec308e9b6204582820b2ea6d80dfeb9, by running:

```
lein run test --nodes-file ~/nodes -w keeper --leave-db-running --read-rate 100 --write-rate 100 --concurrency 6n --time-limit 100
```

**Additional Information**

You can find a full set of node logs here: https://jepsen.io.s3.amazonaws.com/analyses/chainlink-2021/20210420T162029.000-0400.zip

**Comment by PatrickAlphaC** [comment]
Thanks for making this! Will look into it deeper.

**Comment by samsondav** [comment]
Fixed in https://github.com/smartcontractkit/chainlink/pull/4368
