### ISSUE TITLE
[DEVEL] "node" incompatible Expected version "^12.0.0". Got "14.16.0"

### ISSUE THREAD

**Issue by 0xcd21** [smartcontractkit/chainlink#4264]
Hi
I'm installing  Chainlink on Opensuse.
at make install phase I have the following error:

The engine "node" is incompatible with this module. Expected version "^12.0.0". Got "14.16.0"

Full log when running : make install

yarn install --frozen-lockfile
yarn install v1.22.4
[1/5] Validating package.json...
error @: The engine "node" is incompatible with this module. Expected version "^12.0.0". Got "14.16.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make: *** [GNUmakefile:41: yarndep] Error 1

You'll excuse me if I'm raising an issue that was previously flagged but I didn't find a reference to it.

Best regards

**Comment by PatrickAlphaC** [comment]
You need to use node v12.18

```
nvm use 12.18
```

See:
https://github.com/smartcontractkit/chainlink#install

**Comment by 0xcd21** [comment]
indeed, this fixed the issue.
Thank you!
