### ISSUE TITLE
[NODE] `id` parameter no longer present on datasource requests on 0.10.5

### ISSUE THREAD

**Issue by ngauthier** [smartcontractkit/chainlink#4286]
**Description**
Upon upgrading to 0.10.5 the `id` parameter is no longer present in datasource requests (requests from the node to our datasource).

**Basic Information**

We are not running the official adapter, we wrote our own adapter that traces all request parameters including the `id`, and it started erroring because the `id` was no longer present. Presumably this is a required parameter because according to the docs it should be returned as the `jobRunID`:
https://docs.chain.link/docs/developers#returning-data

This was our trace from our custom adapter:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/beeline/trace.py", line 71, in __call__
    yield span
  File "/opt/node/adapter/app.py", line 25, in adapt_prices
    job_id = request.json["id"]
KeyError: 'id'
```

We fixed this on our adapter by no longer requiring the `id` parameter to be present.

This error occurred upon the upgrade to 0.10.5 and was not present in 0.10.4.

- Commit: `0fee9cbc43903a1555ad81185a5befc9954651f7`

**Comment by samsondav** [comment]
Fixed.
