### ISSUE TITLE
[DEVEL] Dockerhub Latest Tag Outdated

### ISSUE THREAD

**Issue by GMSteuart** [smartcontractkit/chainlink#4428]
**Description**
When pulling the chainlink image from dockerhub, the image that is pulled with `smartcontractkit/chainlink:latest` is not the latest chainlink image.

**Your Environment**
Not applicable. Here are [the chainlink images tagged with latest chainlink on dockerhub](https://hub.docker.com/r/smartcontract/chainlink/tags?page=1&ordering=last_updated&name=latest).

**Basic Information**
Using `smartcontractkit/chainlink:latest` in docker (compose or files) or via CLI with a pull does not return the latest.  

**Steps to Reproduce**
```sh
docker pull smartcontractkit/chainlink:latest
docker pull smartcontractkit/chainlink:0.10.6
docker image ls | grep chainlink
```

Example output:
```sh
$ docker image ls | grep chainlink                                                                                                                                                              
smartcontract/chainlink                 0.10.6    e70109690f70   6 days ago     214MB
smartcontract/chainlink                 latest    2a89c59b6622   7 months ago   146MB
```

**Comment by ZakAyesh** [comment]
Thanks for making this issue, it is being investigated!

**Comment by yorickdowne** [comment]
Possibly related to #4099  ?

**Comment by jjhesk** [comment]
does it have a docker build script for taking a look?

**Comment by PatrickAlphaC** [comment]
`latest` has been removed moving forward. Closing.
