### ISSUE TITLE
[FEAT] Oracle AddressProvider Contract

### ISSUE THREAD

**Issue by 0xfoobar** [smartcontractkit/chainlink#4449]
**Description**
Add a contract similar to Aave's AddressProvider or Uniswap's getPair() functionality.

**Motivation**
On-chain lookups of price oracles given the asset addresses.

**Justification**
String manipulation is difficult and expensive in Solidity, and you usually work with the token address, not its string name.

**Comment by ZakAyesh** [comment]
Thanks for the feature request! This is definitely something to look into for an improved developer experience. This shouldn't be too difficult, so I'm marking this as a good first issue for now.

**Comment by dc3327** [comment]
Copy token sets and take send to oracle

**Comment by alexroan** [comment]
@0xfoobar have you seen Chainlink Feeds Registry? 😁 https://docs.chain.link/docs/feed-registry/

**Comment by mercush** [comment]
Hello, seeing as this issue is still open, I was wondering if I could work on it. I'm looking for a good first issue to work one and this one doesn't seem too tricky given that I have some experience writing smart contracts.

**Comment by pappas999** [comment]
Hi @mercush , thanks for the offer. Since this feature request was made, we now have the Chainlink Feeds Registry live. @0xfoobar , does this satisfy your original feature request? If so, we can close this issue. If we feel this is slightly different, then we can look into this

**Comment by PatrickAlphaC** [comment]
Closing for now, as the registry addresses this. https://docs.chain.link/docs/feed-registry/
