### ISSUE TITLE
[FEAT] Add EA API responses to OCR metrics/logs

### ISSUE THREAD

**Issue by yorickdowne** [smartcontractkit/chainlink#4479]
**Description**
Currently, INFO logs do not contain the actual response(s) from the EA APIs on a round, nor do metrics. Metrics contain how long a job took, but not what was returned to the job and what the ultimate answer was.

Adding this to either logs or metrics would be amazing for alerting.

**Motivation**
APIs do not always return reliable data. Even with a median, one large outlier can skew responses noticeably. It'd be great to be able to detect such outliers and alert on them.

Currently, this needs to be done outside the CL node, by adding cron jobs that poll the API, log, and then log parsing after to detect outliers.

Getting this information directly from the node, without needing a side process, would be great.

**Comment by pappas999** [comment]
Thanks for this. Sounds like a sensible feature. Will pass it on for consideration

**Comment by yorickdowne** [comment]
Less important now with metrics in the EA; outliers can be detected that way and then reported on.

**Comment by PatrickAlphaC** [comment]
Going to close this for now with the new metrics.
