### ISSUE TITLE
Chainlink node is ignoring https_proxy env variable

### ISSUE THREAD

**Issue by arodriguezbonmati** [smartcontractkit/chainlink#4502]
**Description**
Node is ignoring proxy variables and cannot make successful calls to _https://min-api.cryptocompare.com/_.

**Basic Information**
- Using Chainlink node **version 0.10.7**, with the Docker image from DockerHub.
- Oracle contract: standard contract on the tutorial.
```
pragma solidity 0.4.24;
import "https://github.com/smartcontractkit/chainlink/evm-contracts/src/v0.4/Oracle.sol";
```

- Network: Private network using IBFT 2.0.
- Blockchain Client: Hyperledger Besu
- Operating System: RHEL 7.9
- Commit: 
```
2021-06-02T08:56:40Z [INFO] Starting Chainlink Node 0.10.7 at commit 6604a647da8af2e0daafb652af13a420b7128f9c cmd/local_client.go:56 InstanceUUID=75f2c23f-3ab7-4eac-b935-b88152954feb SHA=6604a647da8af2e0daafb652af13a420b7128f9c Version=0.10.7 id=boot
```
- Hosting Provider: Azure
- Startup Command:
```
sudo docker run --network host -p 6688:6688 -v ~/.chainlink-rinkeby:/chainlink -it --env-file=.env smartcontract/chainlink:0.10.7 local n
```
**Environment Variables**
```
ROOT=/chainlinkk
LOG_LEVEL=debug
ETH_CHAIN_ID=<chainId>
MIN_OUTGOING_CONFIRMATIONS=0
LINK_CONTRACT_ADDRESS=<address>
CHAINLINK_TLS_PORT=0
SECURE_COOKIES=false
GAS_UPDATER_ENABLED=true
ALLOW_ORIGINS=*
ETH_URL=ws://<ip:port>
DATABASE_URL=<postgres_url>
HTTPS_PROXY=<proxy_url>
HTTP_PROXY=<proxy_url>
```

**Steps to Reproduce**
We have been following step by step your tutorial at _https://docs.chain.link/docs/fulfilling-requests/_. When asking for the ETH price, we get the following error:
```
Get "https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD": dial tcp: lookup min-api.cryptocompare.com on 180.49.40.18:53: no such host
```

**Comment by PatrickAlphaC** [comment]
Thanks for making this issue. I'm not sure this is related to the chainlink node itself. Can you curl the API from the same environment?
```
 curl -X GET -H "content-type:application/json" "https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD"
```

Or does that also fail? It works in my environment.

**Comment by arodriguezbonmati** [comment]
It works fine. Tried it from inside the Docker container and it works fine too. It only fails when executing the GET URL from the job.

**Comment by arodriguezbonmati** [comment]
Just to clarify, the VM where the Chainlink node is hosted does not have access to the Internet unless it is done via proxy, otherwise calls will always fail. Therefore, we believe the Chainlink node is not using the HTTPS_PROXY environment variable.

**Comment by PatrickAlphaC** [comment]
Ah ok, could you put the jobspec that you're using to test here? Have you tried a web job to test?

**Comment by pegartillo95** [comment]
The job that we are using is one from your guide on how to use chainlink. We first tested everything on Rinkeby and it all worked fine but now we are having that issue on the private network due to the proxy.
Here is the jobspec we are using:
```
{
  "name": "Get > Uint256",
  "initiators": [
    {
      "id": 3,
      "jobSpecId": "b3664877-7229-47cb-9593-9d882a9ccf50",
      "type": "runlog",
      "params": {
        "address": "0xf8445b33621aaa9cf9ee229fbf7ba977e7166edc"
      }
    }
  ],
  "tasks": [
    {
      "jobSpecId": "b3664877722947cb95939d882a9ccf50",
      "type": "httpget"
    },
    {
      "jobSpecId": "b3664877722947cb95939d882a9ccf50",
      "type": "jsonparse"
    },
    {
      "jobSpecId": "b3664877722947cb95939d882a9ccf50",
      "type": "multiply"
    },
    {
      "jobSpecId": "b3664877722947cb95939d882a9ccf50",
      "type": "ethuint256"
    },
    {
      "jobSpecId": "b3664877722947cb95939d882a9ccf50",
      "type": "ethtx"
    }
  ]
}
```

**Comment by PatrickAlphaC** [comment]
This doesn't seem to be an issue with the node, going to close for now. Looks like an issue with the environment.
