### ISSUE TITLE
Eslint included but unused?

### ISSUE THREAD

**Issue by NavyAdmiral** [smartcontractkit/chainlink#452]
[eslintrc](https://github.com/smartcontractkit/chainlink/blob/master/.eslintrc.js#L2 )
[package](https://github.com/smartcontractkit/chainlink/blob/master/package.json#L32)

Why is there no package.json script to eslint `chainlink/gui`?

**Comment by rupurt** [comment]
@NavyAdmiral we now use `standardjs` for linting and it the `eslintrc` file was never deleted on the switch. I've removed it in #472.

For `standardjs` to support some of the [experimental](https://standardjs.com/#how-do-i-use-experimental-javascript-es-next-features) features we require the `babel-eslint` package which has a dependency on `eslint`. There is no need to explicitly include it in `package.json`

**Comment by NavyAdmiral** [comment]
#472 resolves this 🎉
