### ISSUE TITLE
[FEAT] Encoding Core Adapter for strings larger than 32 bytes.

### ISSUE THREAD

**Issue by karthedew** [smartcontractkit/chainlink#4540]
**Description**
Add core adapter to compress strings longer than 32 characters to fit a 32byte type size without loosing data. 

You can compress the string data by only allowing characters with a max bit size of 6 and distribute that  across the 8bit, 32byte array size. Can either [1] return a new encoded string and then use the EthBytes32 core adapter or [2] incorporate the EthBytes32 feature within this core adapter. 

Going with option [1] seems like it would be preferable as it would be easier for user's to debug errors.

**Motivation**
Data coming from APIs can consist of data larger than 32 characters.

**Justification**
Multiple individuals have asked if there is a solution for this on the Discord channel. For data larger than 32 characters, currently you have to develop your own suppression method, or make multiple requests which increases the cost of the EA call.

**Comment by ZakAyesh** [comment]
Thanks for suggesting this! Opening up this feature for votes.

**Comment by garyng2000** [comment]
ideally, should allow bytes[] but that can be expensive so at least make it bytes32 x 4 so it can accommodate say ipfs hash value string(base58 or newer base36)

**Comment by PatrickAlphaC** [comment]
Large strings are now supported. https://docs.chain.link/docs/any-api/get-request/examples/large-responses/
