### ISSUE TITLE
[NODE] make install fails with error in orm.go

### ISSUE THREAD

**Issue by sreeharshar84** [smartcontractkit/chainlink#4542]
**Description**
make install fails with error in orm.go

Done in 105.41s.
Done in 106.01s.
CGO_ENABLED=0 go run packr/main.go "/root/chain/chainlink/core/services"
2021/06/11 01:58:48 /root/chain/chainlink/core/services/keeper/orm.go:14:24: missing ',' in argument list
exit status 1
GNUmakefile:62: recipe for target 'operator-ui' failed
make: *** [operator-ui] Error 1

**Basic Information**

- Network: [e.g. Ethereum Mainnet, Ropsten]
- Blockchain Client: [name and version of blockchain client e.g. Geth v1.9.6]
- Go Version: [e.g. v1.12]
- Operating System: Ubuntu 18.04 on digital ocean 
- Commit: [log INFO line when starting node]
- Hosting Provider: digital ocean 
- Startup Command: [e.g. `docker run smartcontract/chainlink local n`]

**Environment Variables**
[replace this line with the output of the environment variables when running the node in debug mode]

**Steps to Reproduce**
Run make install on ubuntu 18.04

**Additional Information**
[replace this line with any additional information you would like to provide, such as screenshots illustrating the issue]

**Comment by ZakAyesh** [comment]
Thanks for making this issue. It is being investigated!

**Comment by se3000** [comment]
@sreeharshar84 can you post the error you're seeing? What branch are you on? I can't repro the issue on develop or master. Also can you fill in environment variables you have set? Possibly sanitize them, but I suspect that is the issue, so even just saying which ones you have set would be helpful.

**Comment by sreeharshar84** [comment]
This is most probably an issue with GO version on my system. Please feel free to close this.
