### ISSUE TITLE
Large degradation of API performance with a high volume of GET /specs/:SpecID/runs requests

### ISSUE THREAD

**Issue by jleeh** [smartcontractkit/chainlink#463]
### System Information

- Network (Main net, Ropsten, etc.): Ropsten
- Ethereum client (Geth/Parity) and version: Parity//v1.11.7-stable-085035f-20180717/x86_64-linux-gnu/rustc1.27.1
- Go version: 1.10
- Host OS: Amazon Linux AMI release 2018.03
- Commit (INFO line when starting the node): 6e9f5429b6c421d9b71abfb901b68702b733e8cd

### Environment Variables

```
CHAINLINK_PORT: 6688
USERNAME: <redacted>
ETH_URL: ws://parity-ws.ropsten.linkpool.io
ETH_CHAIN_ID: 3
CLIENT_NODE_URL: http://localhost:6688
TX_MIN_CONFIRMATIONS: 12
TASK_MIN_CONFIRMATIONS: 0
ETH_GAS_BUMP_THRESHOLD: 12
ETH_GAS_BUMP_WEI: 5000000000
ETH_GAS_PRICE_DEFAULT: 20000000000
LINK_CONTRACT_ADDRESS: 0x514910771AF9Ca656af840dff83E8264EcF986CA
MINIMUM_CONTRACT_PAYMENT: 1000000000000000000
ORACLE_CONTRACT_ADDRESS:
DATABASE_POLL_INTERVAL: 500ms
ALLOW_ORIGINS: http://localhost:3000,http://localhost:6688
```

### Additional Information

To give some background, I've recently been working on a metrics gatherer for nodes allowing me to graph data and provide a WS api to our front-end.

Part of the metric gathering is to retrieve all the spec runs to collate all of the statuses, how many there's been and what adaptors are used. The service that gathers metrics fires each request in its own goroutine, resulting in 80+ API calls for each spec within 1s~. I understand this is very inefficient, but this is a good reason to create an API endpoint that outputs overall statistics, rather than needing to call each spec run individually to gather data. An example of the gathered data:
```
{
  "0xC491f0d6fB2b4F0853a2DE78aaCC91849729ebf4": {
    "totalSpecs": 41,
    "totalSpecRuns": 41,
    "totalBridges": 1,
    "address": "0xC491f0d6fB2b4F0853a2DE78aaCC91849729ebf4",
    "ethBalance": "3400000000000000000",
    "linkBalance": "0",
    "specTaskCounts": {
      "ethbytes32": 3,
      "ethint256": 1,
      "ethtx": 41,
      "ethuint256": 37,
      "httpget": 41,
      "jsonparse": 41,
      "multiply": 38,
      "sleep": 1
    },
    "specRunStatusCounts": {
      "errored": 41
    }
  }
}
```

Anyway, after firing all these requests off I'm seeing large degradation of performance, with response times often exceeding 1m. To give some examples:
```
[INFO] Web request web/router.go:143 clientIP=10.0.92.207 servedAt=2018/07/27 - 11:05:58 method=GET status=200 path=/v2/specs/ff9148d5597847e7b7f679ff01187a38/runs latency=1m3.307433551s
[INFO] Web request web/router.go:143 method=GET status=200 clientIP=10.0.92.207 path=/v2/specs/dc458dd7cc1f4cf98223d6bb770fa634/runs servedAt=2018/07/27 - 11:06:29 latency=1m18.816509244s
```
The highest I've seen is over 2m.

Meanwhile, the CPU/RAM usage of the node while responses are this high aren't extraordinarily high. Seeing averages of around 12% CPU, 3% RAM usage. Disk usage isn't the bottleneck either.

Maybe the node is waiting on bucket locks or something? If this is something that can be improved, I don't mind picking up the work for this.

**Comment by se3000** [comment]
Good find. Thanks for bringing this up, lots of possibilities to investigate here.

**Comment by jleeh** [comment]
I've upgraded the nodes to the later commit of 38088591, and I'm running new on-chain spec-runs every 15 minutes against all the nodes.

Once the spec runs start pilling up, I'll be able to test to see whether this still happens on the latest version.

**Comment by rupurt** [comment]
Hi @jleeh 

Can you provide a list of API endpoints that you need to hit per spec?

**Comment by jleeh** [comment]
Sorry for the delay in getting back, been side tracked on other work.

@rupurt The endpoints are:
```
/v2/account_balance
/v2/bridge_types
/v2/specs
/v2/specs/:specId/runs
```
The specs and spec run API pages are traversed through until it hits the last page.

I'm going to close this ticket, since updating the nodes and setting up a scheduled job to trigger new runs against them causing 180+ spec runs, they seem fine. No high latencies.

**Comment by rupurt** [comment]
@jleeh no worries. Thanks for the update.
