### ISSUE TITLE
[DEVEL] Files are missing in v0.4 contracts/src/interfaces directory

### ISSUE THREAD

**Issue by d0n-th** [smartcontractkit/chainlink#4677]
**Description**
In the source for v0.4, the imported files in Oracle.sol do not exist.

**Comment by pappas999** [comment]
Hi @d0n-th , are you getting an error because of this? Can you please share more info? I took a look here, and I can see all the files that exist that Oracle.sol here is importing https://github.com/smartcontractkit/chainlink/tree/develop/contracts/src/v0.4

**Comment by d0n-th** [comment]
Ah you're right. I just tried re-installing the npm package. Something weird must have happened from my side. Sorry

**Comment by pappas999** [comment]
great to hear you were able to resolve the issue @d0n-th !
