### ISSUE TITLE
[DEVEL] Add src/v0.6/tests/MockV3Aggregator.sol

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/chainlink#4698]
On the migration from evm-contracts, it looks like we missed a few mocks.

src/v0.6/tests/MockV3Aggregator.sol

Please add back

**Comment by alexroan** [comment]
Hey @PatrickAlphaC, Given the v0.6 Mocks weren't being used by the tests, we removed them.

The Mock you're referencing does exist in v0.7 though. Could you use that one?

**Comment by PatrickAlphaC** [comment]
I'd have to go back and refactor a number of projects. This is a pretty staple contract for mocking and running tests. Can we add it back in? Is there a large burden on adding it?

**Comment by PatrickAlphaC** [comment]
Can we publish this in a release?
