### ISSUE TITLE
[NODE] chainlink on private network for testing

### ISSUE THREAD

**Issue by garyng2000** [smartcontractkit/chainlink#4710]
I tried to find documentation of this but failed to find it.

All that I want to do is a run a 'private chainlink node on private network' for testing the code in our smart contracts. What smart contract(s) and/or adapters should I run in order to simulate the price feed contract that is on testnet/mainnet

Obviously, we can't do testing on mainnet due to the prohibited cost and nowadays, fauceting on kovan/rinkeby/goerli doesn't quite work.

Just wondering how do people do testing for chainlink integration nowadays.

I already have the basic running so I can do an http get but really want to simulate the price feed mechanism for say the one used in Liquity.

**Comment by PatrickAlphaC** [comment]
All you'd have to do is run a Chainlink node on your private network. You could follow the docs here; https://docs.chain.link/docs/running-a-chainlink-node/

Are they not enough for what you're looking to do? 

Closing for now, but feel free to follow up here.

**Comment by garyng2000** [comment]
I have my chainlink node(on private network) running. But in order to simulate the actual one out there(on testnet/mainnet), I for example need to have the equivalent price feed feature which is a contract by itself(or may be more as there is also the aggregator thing). I just want to know what I should deploy as well for that.

another thing is that the documentation(for node operator) seems to given example in v0.4(for the testing of request submission) and then the developer documentation seems to show things in v0.6. Which one I should use ?

**Comment by PatrickAlphaC** [comment]
You can deploy an `oracle.sol` contract as outlined in the chainlink node docs: https://docs.chain.link/docs/fulfilling-requests/

Is that what you're looking for?

**Comment by garyng2000** [comment]
I have already done that(and the LINK token). I meant specifically after my node is running and can serve request, what contract(s) or adaptor I have to run to simulate the price feed V3 feature.

**Comment by PatrickAlphaC** [comment]
aahhh I see. Basically that next part is more on-chain. You'd deploy an aggregator contract to aggregate the responses from the group of chainlink nodes

**Comment by garyng2000** [comment]
yes, that is what I am after for documentations. is there a 'standard' sol/adaptor file that is doing this for the price feed. I just want to be sure that our actual smart contracts would work when deployed to mainnet. The accuracy of data on our own private network doesn't really matter(I can even hard code it), but I have to make sure the interface(of our contracts) work as it should. can't really test it on mainnet(too expensive) or testnets(almost all faucet are down or gone)
