### ISSUE TITLE
This site can’t be reachedlocalhost refused to connect. on 6688

### ISSUE THREAD

**Issue by myrulezzz** [smartcontractkit/chainlink#4712]
**Description**
I have created a testing chainling node on google cloud and is configured to the kovan network However i start the container with port 6688 but in chrome i get refused to connect.
**Basic Information**
2021-07-19T09:05:58Z [DEBUG] eth.Client#EthSubscribe                            eth/client.go:288       mode=websocket nodeName=eth-primary-0 nodeTier=primary 
2021-07-19T09:05:58Z [DEBUG] Environment variables
ALLOW_ORIGINS: *\
BALANCE_MONITOR_ENABLED: true
BLOCK_BACKFILL_DEPTH: 10
BRIDGE_RESPONSE_URL: 
ETH_CHAIN_ID: 42
CLIENT_NODE_URL: http://localhost:6688
DATABASE_BACKUP_FREQUENCY: 1h0m0s
DATABASE_BACKUP_MODE: none
DATABASE_TIMEOUT: 
DATABASE_MAXIMUM_TX_DURATION: 30m0s
DEFAULT_HTTP_LIMIT: 32768
DEFAULT_HTTP_TIMEOUT: 15s

**Steps to Reproduce**
Followed the steps from chainlink manual for kovan testnet
**Additional Information**
It seems that i get the client_node_url but when i try to open it from chrome or safari i get connection refused.
For setting up goolge cloud i have created a vm, postgres db, added all information needed in .env file, created and linked an infura account to my setup

**Comment by PatrickAlphaC** [comment]
What's the error you got? Closing this for now as this is a pretty common issue. 

Happy to follow up though, could you please send the stack trace?
