### ISSUE TITLE
<Xinfin Network> websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by loks2cool** [smartcontractkit/chainlink#4727]
**Description**
While trying to launch chainlink node for the XinFin blockchain and trying to bootstrap with Mainnet of Xinfin, it is throwing websocket: close 1006 issue. Whereas it is working perfectly for Apothem(Test) network.

**Basic Information**
Overriden the basic environment variables such as 

export ETH_CHAIN_ID=1
export ETH_URL=ws://localhost:8555
export MIN_OUTGOING_CONFIRMATIONS=2
export CHAINLINK_TLS_PORT=0
export SECURE_COOKIES=false
export ALLOW_ORIGINS=*
export DATABASE_TIMEOUT=0
export FEATURE_EXTERNAL_INITIATORS=true
export CHAINLINK_DEV=true
export DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:5432/chainlink_db?sslmode=disable

- Network:Xinfin
- Blockchain Client: Xinfin Mainnet
- Go Version: 1.15
- Operating System: Ubuntu 20.04
- Commit: [log INFO line when starting node]
- Hosting Provider: AWS
- Startup Command: Chainlink node start

**Environment Variables**

export ETH_CHAIN_ID=1
export ETH_URL=ws://localhost:8555
export MIN_OUTGOING_CONFIRMATIONS=2
export CHAINLINK_TLS_PORT=0
export SECURE_COOKIES=false
export ALLOW_ORIGINS=*
export DATABASE_TIMEOUT=0
export FEATURE_EXTERNAL_INITIATORS=true
export CHAINLINK_DEV=true
export DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:5432/chainlink_db?sslmode=disable

**Steps to Reproduce**
Step1 - download chainlink node
Step2 - make sure pre-requisiteis such as go version, postgres etc are compatible
Step3 - override environment variable
step4 - run using chainlink node start

**Additional Information**
Localhost has to be replaced with IP address where the full node is running. for Security reason, I am not sharing here, but please do let me know if that is reuqired to debug.

**Comment by loks2cool** [comment]
Hi - any assistance or direction here would be of great help..

**Comment by ZakAyesh** [comment]
Hey @loks2cool looking into this, thanks!

**Comment by loks2cool** [comment]
Hi thanks for checking, actually we sorted this out. It happened, due to node from our end. Basically, it has to hit the master node which is responsble for block generation. But I was pointing full node websocket.. that's the reason it errored out.

this issue can be closed.

**Comment by ZakAyesh** [comment]
Great thanks for updating! Closing the issue.
