### ISSUE TITLE
[NODE] Root folder permissions gets rewritten every time Chainlink docker container restarts

### ISSUE THREAD

**Issue by ArseniiPetrovich** [smartcontractkit/chainlink#4743]
**Description**
We are using `log.jsonl` file to ingest the logs to our centralized logging server. We noticed that after each time Chainlink container restarts the folder defined via the `ROOT` variable gets the 700 (rwx------) permission, which prevents the agent of our logging system to collect data from the folder. Is there a way to alter this behavior somehow?

**Basic Information**
Running on Docker version 20.10.4, build d3cb89e

- Network: Mainnet
- Blockchain Client: Geth v1.10.6 
- Go Version: v1.16
- Operating System: Amazon Linux 2
- Commit: 
```
{"level":"info","ts":1627300044.9035575,"caller":"cmd/local_client.go:62","msg":"Starting Chainlink Node 0.10.9 at commit bb2564be5e0e295699bb1f23b0b2ae3e0bfa2cd8","id":"boot","Version":"0.10.9","SHA":"bb2564be5e0e295699bb1f23b0b2ae3e0bfa2cd8","InstanceUUID":"39794c27-8d53-4698-8881-1665ab77de47"}
```
- Hosting Provider: AWS
- Startup Command: chainlink local n -p /chainlink/.password -a /chainlink/.api

**Environment Variables**
```
# Chainlink Environment file
ROOT=/chainlink
LOG_LEVEL=debug
ETH_CHAIN_ID=1
ALLOW_ORIGINS=*
MINIMUM_CONTRACT_PAYMENT=100000000000000000
DEFAULT_HTTP_ALLOW_UNRESTRICTED_NETWORK_ACCESS=true

# OCR Variables
FEATURE_OFFCHAIN_REPORTING=true
OCR_TRACE_LOGGING=true 
# LISTENING_PORT AND/OR ANNOUNCE_PORT AND ANNOUNCE_IP
P2P_LISTEN_PORT=<REDACTED>
# Must Specify Both of Below OR LISTENING
P2P_ANNOUNCE_IP=<REDACTED>
P2P_ANNOUNCE_PORT=<REDACTED>

# Ethereum Mainnet Variables
MIN_OUTGOING_CONFIRMATIONS=2
MIN_INCOMING_CONFIRMATIONS=2
ETH_URL=<REDACTED>
ETH_SECONDARY_URL=<REDACTED>

# Database Values
DATABASE_URL=<REDACTED>
DATABASE_TIMEOUT=0

# Settings for HTTPS (enable these or the ones below for http)#
#CHAINLINK_TLS_PORT=6689
#SECURE_COOKIES=true
#TLS_CERT_PATH=/chainlink/tls/server.crt
#TLS_KEY_PATH=/chainlink/tls/server.key
# Setting for HTTP
CHAINLINK_TLS_PORT=0
SECURE_COOKIES=false

# Transaction Improvements
GAS_UPDATER_ENABLED=true
GAS_UPDATER_TRANSACTION_PERCENTILE=60
ETH_GAS_BUMP_THRESHOLD=9
ETH_GAS_BUMP_WEI=7000000000
ETH_BALANCE_MONITOR_BLOCK_DELAY=3
ENABLE_BULLETPROOF_TX_MANAGER=true
```

**Steps to Reproduce**
1. Run docker container with ROOT env variable configured to some volume on your local host and LOG_TO_DISK set to true
2. Change permissions on host to the ROOT folder.
3. Restart Chainlink container
4. Check file permissions

**Comment by ZakAyesh** [comment]
Thanks for making this, we are taking a deeper look.

**Comment by dzmitrykliapkou** [comment]
Hi @ZakAyesh ! Could you please let us know if you have any updates regarding this issue?

**Comment by samsondav** [comment]
This is not a bug, it's a feature :). We do this deliberately as a security measure.

It was introduced here: https://github.com/smartcontractkit/chainlink/commit/5cf590a31c0eba1f204c10d2cfb772d4ba2c6c26

Chainlink's root folder can contain passwords and other sensitive information, for this reason we force restrictive permissions.

I opened a PR that allows you to customise the output directory for logging.

LMK if that solves your problem.
