### ISSUE TITLE
[FAUC] Neither Ropsten nor Rinkeby function currently

### ISSUE THREAD

**Issue by XOCODE-OP** [smartcontractkit/chainlink#4749]
**Description**
Facuets seem to be down right now, but the front end is still up.
They provide non existing tx hashes.

**Basic Information**
The urls for the faucets are [https://rinkeby.chain.link/](https://rinkeby.chain.link/) and [https://ropsten.chain.link/](https://ropsten.chain.link/)
It will provide an rinkeby.etherscan.io/tx/ or ropsten link respectively and either one will result in the error
"Sorry, We are unable to locate this TxnHash". Even waiting does not fix the issue.
Here you can see one of the not existing transactions: [https://rinkeby.etherscan.io/tx/0xdd61c06d86dd6ba0630c980572ee7d8594c2f1231ebfcceac6b1ee15b82f2acf](https://rinkeby.etherscan.io/tx/0xdd61c06d86dd6ba0630c980572ee7d8594c2f1231ebfcceac6b1ee15b82f2acf)
I tried with multiple addresses, one that I use here is `0xb5171cdba8906364d295Fa6bb9a46ED90AB875E2`

**Steps to Reproduce**
Visit [https://rinkeby.chain.link/](https://rinkeby.chain.link/), use any address.

**Additional Information**
N/A

**Comment by pappas999** [comment]
thanks @XOCODE-OP , we're aware of this issue and looking into it

**Comment by pappas999** [comment]
Hi @XOCODE-OP , we believe the issue should be resolved on rinkeby now, can you try again and update the issue?

Also take note, we don't support Ropsten anymore. We recommend using Kovan or Rinkeby

**Comment by XOCODE-OP** [comment]
Seems to work now!
Also roger on Ropsten.
Thanks!
