### ISSUE TITLE
[NODE] GUI bug when creating TOML jobs containing a task having a JSON field

### ISSUE THREAD

**Issue by ferru97** [smartcontractkit/chainlink#4855]
**Description**
Creating a TOML job containing a task having a JSON field results in a blank job page

**Basic Information**
When creating a job that contains a task having a JSON field, such as *ethabiencode *, the task is successfully created but the job page is blank and reports the following error in the browser console:

```
Failed to load resource: the server responded with a status of 404 (Not Found) main.03fa9f5120fbcd295504.js:2
TypeError: Cannot read property '3' of null
    at B (main.03fa9f5120fbcd295504.js:2)
    at Ct (main.03fa9f5120fbcd295504.js:2)
    at At (main.03fa9f5120fbcd295504.js:2)
    at Lt (main.03fa9f5120fbcd295504.js:2)
    at Ot (main.03fa9f5120fbcd295504.js:2)
    at xt (main.03fa9f5120fbcd295504.js:2)
    at wt (main.03fa9f5120fbcd295504.js:2)
    at Et (main.03fa9f5120fbcd295504.js:2)
    at _t (main.03fa9f5120fbcd295504.js:2)
    at Object.parse (main.03fa9f5120fbcd295504.js:2)
hs @ main.03fa9f5120fbcd295504.js:2
```

Also, when introducing a JSON field in the input box during creation, the *Task list preview* becomes blank, no longer showing the job preview. There don't seem to be any problems when listing the jobs via CLI.

- Network: Rinkeby
- Blockchain Client: Geth v1.10.6
- Go Version:  v1.16
- Operating System: official docker container v0.10.11 tested on both windows and linux
- Startup Command: started via docker-compose with the following command *local" n -p /chainlink/.password -a /chainlink/.api*

**Environment Variables**
```
ROOT=/chainlink
ETH_URL=ws://geth:8546
LOG_LEVEL=debug
ETH_CHAIN_ID=4
MIN_OUTGOING_CONFIRMATIONS=2
LINK_CONTRACT_ADDRESS=0x01BE23585060835E02B77ef475b0Cc51aA1e0709
CHAINLINK_TLS_PORT=0
SECURE_COOKIES=false
GAS_UPDATER_ENABLED=true
ALLOW_ORIGINS=*
DATABASE_URL=postgresql://test:test123@postgres:5432/chainlink?sslmode=disable
PRIVATE_KEY_PASSWORD="Pdnsajojhdsoia@djsaoi!"
```

**Steps to Reproduce**
On the v0.10.10+ clients create the following TOML job via GUI:
```
type                = "directrequest"
schemaVersion       = 1
name                = "Get > Bytes32"
contractAddress     = "0x613a38AC1659769640aaE063C651F48E0250454C"
observationSource   = """
    fetch        [type=http method=get url="$(decode_cbor.url)"]
    parse        [type=jsonparse path="$(decode_cbor.path)"]
    encode_data  [type=ethabiencode abi="(uint256 value)" data=<{ "value": $(parse) }>]

    fetch -> parse -> encode_data 
"""
```

By removing *encode_data* everything will work. Also, you can use as test the first migration example available on the [official guide](https://docs.chain.link/docs/jobs/migration-v1-v2/)

**Comment by garyng2000** [comment]
saw the same error on the latest 'develop' branch pull. one thing I don't understand though without ethabiencode, how to specify the 'fulfill' data to the callback ?

**Comment by ferru97** [comment]
Don't know, I think it is necessary. Can you link me that pull?

**Comment by garyng2000** [comment]
oh, I meant I just clone this project and build from source where the default branch is the 'develop', i.e. latest they have merged in which is likely to be next version.

**Comment by Inbell1s** [comment]
Same issue on V0.10.11, error on the console states:
```
TypeError: Cannot read property '3' of null
    at B (main.03fa9f5120fbcd295504.js:2)
    at Ct (main.03fa9f5120fbcd295504.js:2)
    at At (main.03fa9f5120fbcd295504.js:2)
    at Lt (main.03fa9f5120fbcd295504.js:2)
    at Ot (main.03fa9f5120fbcd295504.js:2)
    at xt (main.03fa9f5120fbcd295504.js:2)
    at wt (main.03fa9f5120fbcd295504.js:2)
    at Et (main.03fa9f5120fbcd295504.js:2)
    at _t (main.03fa9f5120fbcd295504.js:2)
    at Object.parse (main.03fa9f5120fbcd295504.js:2)
```

**Comment by bamerrell** [comment]
I'm experiencing this bug as well using the docker image of 0.10.12.

My job definition is: 
`type="fluxmonitor"
schemaVersion=1
name="ETH/USD Fluxmonitor v3 0x75760dcde3dA82C2eA8e7A1ccD7d514BCb6DA33C"
contractAddress="0x75760dcde3dA82C2eA8e7A1ccD7d514BCb6DA33C"
externalJobID="0EEC7E1D-D0D2-476C-A1A8-72DFB6633F03"
threshold=0.5
absoluteThreshold=0.0
idleTimerPeriod="1s"
idleTimerDisabled=false
pollTimerPeriod="1m"
pollTimerDisabled=false
observationSource="""
    // data source 1
    ds1 [type="bridge" name="coingecko" requestData=<{"coin": "ETH", "market": "USD"}>]
    ds1_parse [type=jsonparse path="data,result"]
    
    // data source 2
    ds2 [type="bridge" name="coinpaprika" requestData=<{"from": "ETH", "to": "USD"}>]
    ds2_parse [type=jsonparse path="data,result"]

    ds1 -> ds1_parse -> medianized_answer
    ds2 -> ds2_parse -> medianized_answer

    medianized_answer [type=median]
"""`

**Comment by pappas999** [comment]
thanks @bamerrell and @ferru97 , we'll try re-create on our end

**Comment by nibty** [comment]
Any updates here? I see the same issue when using the documented bridge example on v0.10.14.
https://docs.chain.link/docs/jobs/task-types/bridge/

**Comment by micascheid** [comment]
@nibty check out ticket 4882. @vnavascues has provided a solution that is working for me.

**Comment by PatrickAlphaC** [comment]
This has been fixed, closing.
