### ISSUE TITLE
[FEAT] Add VRFCoordinatorMock for v0.8 solidity

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/chainlink#4937]
**Description**
https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.6/tests/VRFCoordinatorMock.sol

Can we get this for 0.8? This helps with building smart contracts.

**Motivation**
So I can test chainlink VRF in my applications.  This would go into @chainlink/contracts. Our [hardhat-starter-kit](https://github.com/smartcontractkit/hardhat-starter-kit) uses these to test and mock.

**Comment by igormorgado** [comment]
I second this! v0.8 has builtin safemath.

**Comment by PatrickAlphaC** [comment]
+1

**Comment by PatrickAlphaC** [comment]
@tzumby @stevepsharpe could you please thumb up the original comment? Thank you!
