### ISSUE TITLE
[DEVEL] Error when running a custom job with the V2 spec, fails at the decode_cbor task.

### ISSUE THREAD

**Issue by Cali93** [smartcontractkit/chainlink#4977]
**Description**
I'm trying to run a custom job with the V2 spec but it fails at the decode_cbor task.

**Your Environment**
WSL2

**Basic Information**
![image](https://user-images.githubusercontent.com/32299095/132434777-9d55c817-2166-4d58-bd3f-f1a988feeeb1.png)

**Steps to Reproduce**

Here's the toml
`
type = "directrequest"
schemaVersion = 1
name = "Break trough 2"
contractAddress = "0x6FDeC4519C8755035BC2E891234199bD41A3Aad1"
maxTaskDuration = "0s"
observationSource = """
// First, we parse the request log and the CBOR payload inside of it
decode_log [type=ethabidecodelog
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]

decode_cbor [type="cborparse"
             data="$(decode_log.data)"]

// Then, we use the decoded request parameters to make an HTTP fetch
fetch [type="http" method="post" url="someurl" requestData=<{ "did": $(decode_cbor.did), "questId": $(decode_cbor.questId) }>]
parse [type="jsonparse" path="$(decode_cbor.jsonPath)" data="$(fetch)"]

// Finally, we send a response on-chain
encode_response [type="ethabiencode"
                 abi="(bytes32 requestId, uint256 data)"
                 data=<{ "requestId": $(decode_log.requestId), "data": $(parse) }>]
 
encode_tx    [type="ethabiencode"
              abi="fulfillOracleRequest(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes32 data )"
              data=<{ "data": $(encode_response), "requestId": $(decode_log.requestId), "payment": $(decode_log.payment), "callbackAddress": $(decode_log.callbackAddr), "callbackFunctionId": $(decode_log.callbackFunctionId), "expiration": $(decode_log.cancelExpiration) }>]

submit_tx  [type=ethtx to="0x6FDeC4519C8755035BC2E891234199bD41A3Aad1" data="$(encode_tx)"]
`

**Comment by ZakAyesh** [comment]
This would make a great StackOverflow post. Could you make one and include the smart contract code making this request as well? It would be much appreciated so others can get help with this issue!
https://stackoverflow.com/questions/ask?tags=chainlink

**Comment by PatrickAlphaC** [comment]
Going to close, this looks like an issue with the implementation.
