### ISSUE TITLE
Error while compiling brownie

### ISSUE THREAD

**Issue by BookmDan** [smartcontractkit/chainlink#5008]
Hi Patrick,

I am seeing this error: 

Not sure what I am doing wrong here.

Thank you for your help. 
![Screen Shot 2021-09-14 at 1 47 07 PM (2)](https://user-images.githubusercontent.com/8926023/133331497-552f93dd-e276-45dc-9504-60c989adc141.png)

_Originally posted by @BookmDan in https://github.com/smartcontractkit/chainlink/issues/3623#issuecomment-919501007_

**Comment by PatrickAlphaC** [comment]
Can you remove the `-` from `remappings: -'@chainlink=smartcontract......'

Also please don't use images for creating issues, it's much easier if you copy paste code. Could you add your whole `brownie-config.yaml` here?

**Comment by BookmDan** [comment]
Yes here is my config: 
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:

dotenv: .env
networks:
  default: development
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: True
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}

brownie run scripts/deploy.py was working fine in the simple_storage. 

But since the fund_me portion of the project it has not been working properly. 

I have an import error in FundMe.sol for - 'import "@chainlink/...." '

Here is my FundMe.sol: 
// SPDX-License-Identifier: MIT

pragma solidity ^0.6.6;

import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";
import "@chainlink/contracts/src/v0.6/vendor/SafeMathChainlink.sol";

contract FundMe {
    using SafeMathChainlink for uint256;

    mapping(address => uint256) public addressToAmountFunded;
    address[] public funders;
    address public owner;
    AggregatorV3Interface public priceFeed;

    constructor(address _priceFeed) public {
        priceFeed = AggregatorV3Interface(_priceFeed);
        owner = msg.sender;
    }

    function fund() public payable {
        uint256 mimimumUSD = 50 * 10**18;
        require(
            getConversionRate(msg.value) >= mimimumUSD,
            "You need to spend more ETH!"
        );
        addressToAmountFunded[msg.sender] += msg.value;
        funders.push(msg.sender);
    }

    function getVersion() public view returns (uint256) {
        return priceFeed.version();
    }

    function getPrice() public view returns (uint256) {
        (, int256 answer, , , ) = priceFeed.latestRoundData();
        return uint256(answer * 10000000000);
    }

    // 1000000000
    function getConversionRate(uint256 ethAmount)
        public
        view
        returns (uint256)
    {
        uint256 ethPrice = getPrice();
        uint256 ethAmountInUsd = (ethPrice * ethAmount) / 1000000000000000000;
        return ethAmountInUsd;
    }

    function getEntranceFee() public view returns (uint256) {
        // mimimumUSD
        uint256 mimimumUSD = 50 * 10**18;
        uint256 price = getPrice();
        uint256 precision = 1 * 10**18;
        return (mimimumUSD * precision) / price;
    }

    modifier onlyOwner() {
        require(msg.sender == owner);
        _;
    }

    function withdraw() public payable onlyOwner {
        msg.sender.transfer(address(this).balance);

        for (
            uint256 funderIndex = 0;
            funderIndex < funders.length;
            funderIndex++
        ) {
            address funder = funders[funderIndex];
            addressToAmountFunded[funder] = 0;
        }
        funders = new address[](0);
    }
}

**Comment by BookmDan** [comment]
Ok, I was able to manually import the Aggregator and SafeMathChainlink files. 

Now I am getting a different error:
ImportError: cannot import name 'MockV3Aggregator' from 'brownie' (/Users/Daniel/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/brownie/__init__.py)

Import brownie could not be resolved Pylance, is the error I see for brownie in my deploy.py.

**Comment by PatrickAlphaC** [comment]
Is that just VSCode yelling at you and not an error in the terminal? If yes, you can safely ignore that. It's an issue with the solidity extension.

**Comment by BookmDan** [comment]
Okay, was able to use the config.yaml and it resolved the issue.

**Comment by rholderfield** [comment]
Make sure your MockV3Aggregator.sol is under the correct contracts folder.
