### ISSUE TITLE
[SMRT] Missing Contracts v0.8

### ISSUE THREAD

**Issue by dmitrydao** [smartcontractkit/chainlink#5031]
**Description**
Missing `Owned.sol` and `Ownable.sol` contracts in the [v0.8 contracts repository](https://github.com/smartcontractkit/chainlink/tree/master/contracts/src/v0.8).

**Basic Information**
The docs team wants to have code samples with the latest Solidity version (v0.8).
Currently  the absence of`Owned.sol` and `Ownable.sol` prevent from moving to v0.8

More details and context are in the [following issue](https://github.com/smartcontractkit/documentation/issues/196).

**Comment by alexroan** [comment]
The contracts have been replaced with `ConfirmedOwner.sol` and `ConfirmedOwnerWithProposal.sol`.

`ConfirmedOwner` is what you need.
