### ISSUE TITLE
Error with deploy_lottery.py

### ISSUE THREAD

**Issue by BookmDan** [smartcontractkit/chainlink#5040]
**Description**
I am receiving an error 

**Your Environment**
using a mac os 
vscode 

**Basic Information**
Working on trying to run the deploy_lottery.py. Having an error importing KeeperCompatibleInterface.sol

**Steps to Reproduce**
Run scripts/deploy_lottery.py

**Additional Information**CompilerError: solc returned the following errors:

This is the error I am seeing, once I run the deploy_lottery.py on brownie:

**contracts/Lottery.sol:4:1: 

ParserError: Source "/Users/Daniel/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.1/contracts/src/v0.8/KeeperCompatibleInterface.sol" not found: File not found.
import "@chainlink/contracts/src/v0.8/KeeperCompatibleInterface.sol";**

**Comment by BookmDan** [comment]
Now I am getting this error: 

Compiling contracts...
  Solc version: 0.6.12
  Optimizer: Enabled  Runs: 200
  EVM Version: Istanbul
CompilerError: solc returned the following errors:

contracts/Lottery.sol:38:1: ParserError: Expected pragma, import directive or contract/interface/library/struct/enum definition.
Solidity (Ethereum)
^------^

**Comment by PatrickAlphaC** [comment]
Hi @BookmDan, I think this was meant for another repo. Closing this for now. What repository are you running this code from?

**Comment by BookmDan** [comment]
Oh yes sorry. It was for the brownie lottery youtube example.

**Comment by PatrickAlphaC** [comment]
Thanks! Can you make the issue on that repo?
