### ISSUE TITLE
[DEVEL] Development Setup Guide suggests outdated NodeJS version

### ISSUE THREAD

**Issue by zxiiro** [smartcontractkit/chainlink#5091]
**Description**
The Development Setup Guide (https://github.com/smartcontractkit/chainlink/wiki/Development-Setup-Guide) says that one should install NodeJS v10.16 however this version of NodeJS does not pass `make install` when trying to build Chainlink. Rather than maintaining 2 pages that state versions of requirements and then forgetting too update one or the other I think it would be good for the wiki page to refer to repo README for requirements information.

**Your Environment**
Google Chrome

**Basic Information**
Instructions on https://github.com/smartcontractkit/chainlink/wiki/Development-Setup-Guide suggests to install outdated version of NodeJS.

**Steps to Reproduce**
Try to build chainlink following instructions on the Development Setup Guide wiki page (https://github.com/smartcontractkit/chainlink/wiki/Development-Setup-Guide).

**Additional Information**
N/A

**Comment by ZakAyesh** [comment]
Nice catch and suggestion, I'll see if we can make some changes to that wiki page for now and discuss moving everything to the readme.

**Comment by ZakAyesh** [comment]
The Wiki page should now be updated to reflect a NodeJS version that will allow `make install` to run.

**Comment by zxiiro** [comment]
> The Wiki page should now be updated to reflect a NodeJS version that will allow `make install` to run.

Confirmed the page has been updated. I assume we want to leave this open until moving instructions to readme so I won't close it.

**Comment by PatrickAlphaC** [comment]
>  I assume we want to leave this open until moving instructions to readme so I won't close it.

I'm not sure I follow, closing this for now. Thanks again!
