### ISSUE TITLE
[NODE] Requesting a job with 1 LINK results in `"rejecting job with payment 24 below minimum threshold (1000000000000000000)"`

### ISSUE THREAD

**Issue by hexcowboy** [smartcontractkit/chainlink#5096]
**Description**
The first transaction from a new Smart Contract results in a failure saying the payment was insufficient, even if the payment *was* sufficient. Following transactions do not result in an error.

**Basic Information**
[replace this line with basic information about the issue you are experiencing, including but not limited to all relevant logs and any other relevant information, such as if you are using a Docker container to run the node, job specification, oracle contract address, transaction IDs, etc.]

- Network: `Kovan`
- Blockchain Client: `Geth (Infura)`
- Go Version: Unknown
- Operating System: `Linux 577ac27d54c3 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 x86_64 x86_64 GNU/Linux`
- Commit: `8160d7726d778b5c425e4b56af30b76cbc6d222d`
- Hosting Provider: `Docker (self-hosted)`
- Startup Command:
```Dockerfile
ENTRYPOINT ["chainlink"]
CMD ["local", "node"]
```

**Environment Variables**
```bash
ETH_CHAIN_ID=42
LINK_CONTRACT_ADDRESS=0xa36085F69e2889c224210F603D836748e7dC0088
ROOT=/srv
LOG_LEVEL=debug
CHAINLINK_TLS_PORT=0
SECURE_COOKIES=false
ALLOW_ORIGINS=*
ETH_URL=wss://kovan.infura.io/ws/v3/<redacted>
DATABASE_URL=postgresql://<redacted>
```

**Steps to Reproduce**
Run a node with the above configuration, deploy an `Oracle.sol`, and deploy the [`TestnetConsumer.sol`](https://remix.ethereum.org/#url=https://docs.chain.link/samples/APIRequests/ATestnetConsumer.sol) file. Fund with LINK and the first transaction request will fail with the message:
```json
  "result": {
    "data": {
    },
    "error": "rejecting job 5d0ee14b3c7b4dc5afc76cc588a9de72 with payment 24 below minimum threshold (1000000000000000000)"
  },
```

**Additional Information**
This transaction shows that 1 LINK token was sent to the Oracle: https://kovan.etherscan.io/tx/0x5f55ab7b0aaadb9b921bec3042e68fcd05c3985f7d8aa4b2ed37a38a8788f951

Which resulted in the above error.

**Comment by ZakAyesh** [comment]
Thanks for making this issue. It is being investigated!

**Comment by PatrickAlphaC** [comment]
Closing, we need to remember to pay in JUELS. 24 JUELS is less than 1000000000000000000!
