### ISSUE TITLE
[FEAT] Make JSON log files roll over for easy ingestion by Splunk/Grafana/etc.

### ISSUE THREAD

**Issue by northwestnodes** [smartcontractkit/chainlink#5165]
**Description**
Please make it so that the log file can roll over to new files based on either a size limit, time limit, etc.

**Motivation**
Why? Because then we can more easily use JSON log exports to visualization tools such as Splunk, Grafana, etc.

**Justification**
Because cutting up the log files makes the data more easily ingestible by aforementioned visualization tools.

**Additional Information**
Any form of rollover would be appreciated, like maybe set a time limit and make each logfile reflect a timestamp.

**Comment by pappas999** [comment]
thanks for raising this @northwestnodes . Sounds like a sensible feature request. We can put it to vote

**Comment by northwestnodes** [comment]
> thanks for raising this @northwestnodes . Sounds like a sensible feature request. We can put it to vote.
> 
> The community can vote with a thumbs-up or down on the first post. I've started with a thumbsup

Thanks @pappas999! If we had any time we'd help with creating a pull request. Perhaps later this month :)

**Comment by PatrickAlphaC** [comment]
Closing, JSON logs are no longer supported.
