### ISSUE TITLE
[DEVEL] VRF toml file request

### ISSUE THREAD

**Issue by jjhesk** [smartcontractkit/chainlink#5204]
Since we have updated to V2 job spec formats. What is the VRF specific job in toml file that we have in repos now? #5204 
https://github.com/smartcontractkit/chainlink/issues/4964

version: 0.10.14

**Comment by jjhesk** [comment]
How do I generate the publickey for the Coordinator? https://github.com/smartcontractkit/chainlink/blob/e4b7f988085778fc919949b659dd8b49fef61f56/core/testdata/tomlspecs/vrf-spec.toml#L7

**Comment by PatrickAlphaC** [comment]
Thanks, added to investigating queue.
