### ISSUE TITLE
[NODE] For v2 jobs in TOML, HTTP tasks fail when methods are lowercase `get` instead of `GET`

### ISSUE THREAD

**Issue by dwightjl** [smartcontractkit/chainlink#5209]
**Description**
For v2 jobs in TOML, HTTP tasks fail when methods are lowercase `get` instead of `GET`. Some URLs handle `get` just fine. Others do not. The New Job interface doesn't check case on HTTP methods, so it led to hours of troubleshooting. The New Job interface should check these HTTP methods to make sure they are defined correctly, and warn the user when they have errors. Alternatively, the system could automatically change HTTP requests to uppercase.

Lowercase `get` examples:

**min-api.cryptocompare.com/**
`fetch [type=http method=get url="http://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD"]`

Returns: `error making http request: get "http://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD": net/http: HTTP/1.x transport connection broken: malformed HTTP response "<html>"`

Same result if I try `https://` for that URL.

**time.jsontest.com/**
`fetch [type=http method=get url="http://time.jsontest.com/"]`

Returns:
```
{
  "type": "http",
  "createdAt": "2021-10-11T05:55:47.831419Z",
  "finishedAt": "2021-10-11T05:55:47.899228Z",
  "output": ""{\n \"date\": \"10-11-2021\",\n \"milliseconds_since_epoch\": 1633931747869,\n \"time\": \"05:55:47 AM\"\n}\n"",
  "error": null,
  "dotId": "fetch",
  "status": "completed"
},
```

Uppercase `GET` examples:

**min-api.cryptocompare.com/**
`fetch [type=http method=GET url="http://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD"]`

Returns:
```
{
  "type": "http",
  "createdAt": "2021-10-11T15:51:16.468077Z",
  "finishedAt": "2021-10-11T15:51:17.802276Z",
  "output": ""{\"USD\":3596.37}"",
  "error": null,
  "dotId": "fetch",
  "status": "completed"
},
```

**Basic Information**

- Network: Rinkeby
- Blockchain Client: Geth 1.10.10 Docker ethereum/client-go:latest
- Go Version: go1.17.2
- Operating System: Ubuntu Server 21.10
- Commit: 1.0.0 at commit df6daf7
- Hosting Provider: Local KVM
- Startup Command: `chainlink node start`

**Environment Variables**
```
ALLOW_ORIGINS: http://localhost:3000,http://localhost:6688
BLOCK_BACKFILL_DEPTH: 10
BLOCK_HISTORY_ESTIMATOR_BLOCK_DELAY: 0
BLOCK_HISTORY_ESTIMATOR_BLOCK_HISTORY_SIZE: 0
BLOCK_HISTORY_ESTIMATOR_TRANSACTION_PERCENTILE: 0
BRIDGE_RESPONSE_URL: 
ETH_CHAIN_ID: 4
CLIENT_NODE_URL: http://localhost:6688
DATABASE_BACKUP_FREQUENCY: 1h0m0s
DATABASE_BACKUP_MODE: none
DATABASE_MAXIMUM_TX_DURATION: 30m0s
DATABASE_TIMEOUT: 
DEFAULT_HTTP_LIMIT: 32768
DEFAULT_HTTP_TIMEOUT: 15s
CHAINLINK_DEV: false
ETH_DISABLED: false
ETH_HTTP_URL: 
ETH_SECONDARY_URLS: []
ETH_URL: ws://172.17.0.2:8546
EXPLORER_URL: 
FM_DEFAULT_TRANSACTION_QUEUE_DEPTH: 1
FEATURE_EXTERNAL_INITIATORS: false
FEATURE_OFFCHAIN_REPORTING: false
GAS_ESTIMATOR_MODE: 
INSECURE_FAST_SCRYPT: false
JSON_CONSOLE: false
JOB_PIPELINE_REAPER_INTERVAL: 1h0m0s
JOB_PIPELINE_REAPER_THRESHOLD: 24h0m0s
KEEPER_DEFAULT_TRANSACTION_QUEUE_DEPTH: 1
KEEPER_MAXIMUM_GRACE_PERIOD: 0
KEEPER_MINIMUM_REQUIRED_CONFIRMATIONS: 0
KEEPER_REGISTRY_CHECK_GAS_OVERHEAD: 0
KEEPER_REGISTRY_PERFORM_GAS_OVERHEAD: 0
KEEPER_REGISTRY_SYNC_INTERVAL: 
LINK_CONTRACT_ADDRESS: 
FLAGS_CONTRACT_ADDRESS: 
LAYER_2_TYPE: 
LOG_LEVEL: debug
LOG_SQL_MIGRATIONS: true
LOG_SQL: false
LOG_TO_DISK: true
OCR_BOOTSTRAP_CHECK_INTERVAL: 20s
TRIGGER_FALLBACK_DB_POLL_INTERVAL: 30s
OCR_CONTRACT_TRANSMITTER_TRANSMIT_TIMEOUT: 10s
OCR_DATABASE_TIMEOUT: 10s
OCR_DEFAULT_TRANSACTION_QUEUE_DEPTH: 1
OCR_INCOMING_MESSAGE_BUFFER_SIZE: 10
P2P_BOOTSTRAP_PEERS: []
P2P_LISTEN_IP: 0.0.0.0
P2P_LISTEN_PORT: 
P2P_NETWORKING_STACK: V1
P2P_PEER_ID: 
P2PV2_ANNOUNCE_ADDRESSES: []
P2PV2_BOOTSTRAPPERS: []
P2PV2_DELTA_DIAL: 15s
P2PV2_DELTA_RECONCILE: 1m0s
P2PV2_LISTEN_ADDRESSES: []
OCR_OUTGOING_MESSAGE_BUFFER_SIZE: 10
OCR_NEW_STREAM_TIMEOUT: 10s
OCR_DHT_LOOKUP_INTERVAL: 10
OCR_TRACE_LOGGING: false
CHAINLINK_PORT: 6688
REAPER_EXPIRATION: 240h0m0s
REPLAY_FROM_BLOCK: -1
ROOT: /chainlink
SECURE_COOKIES: true
SESSION_TIMEOUT: 15m0s
TELEMETRY_INGRESS_LOGGING: false
TELEMETRY_INGRESS_SERVER_PUB_KEY: 
TELEMETRY_INGRESS_URL: 
CHAINLINK_TLS_HOST: 
CHAINLINK_TLS_PORT: 6689
CHAINLINK_TLS_REDIRECT: false
```

**Steps to Reproduce**

1. Add a v2 job in TOML format to a node and specify an HTTP task with `method=get` instead of `method=GET`.
2. Run the job and execute the HTTP task against a URL like [https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD](https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD). The task fails with an HTTP request error.
4. Try the task again but with [http://time.jsontest.com/](http://time.jsontest.com/) The task is successful.

To fix the issue, deploy the job again but use uppercase `method=GET`.

**Comment by prashantkumar1982** [comment]
Regarding the method being lower case vs upper case:
We followed the W3 spec here to maintain this as case sensitive: https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html#sec5.1.1

As the spec already says this method is case-sensitive, we cannot arbitrarily change casing.

In this case, we are doing the right thing, and the reporting the right error back, indicating that http server returned a malformed response.
