### ISSUE TITLE
[NODE] BUG - Chainlink node is unable to properly parse environment variables set in docker-compose.yml

### ISSUE THREAD

**Issue by northwestnodes** [smartcontractkit/chainlink#5243]
**Description**
Whenever I set an environment variable in the docker-compose.yml file, instead of the .env file, Chainlink crashes.

**Basic Information**
For example, setting an environment variable like so:
```
    environment:
      - ETH_URL="eth url here and such"
```
Will result in the following error:
```
chainlink_1  | 2021-10-17T22:08:13Z [INFO]  Starting Chainlink Node 0.10.15 at commit 788d0b9d8ba2c36d5d9e3f19e21deef3c611d8d9 cmd/local_client.go:63           InstanceUUID=8b69fa02-1aa1-49a7-aa79-125483eac9a9 SHA=788d0b9d8ba2c36d5d9e3f19e21deef3c611d8d9 Version=0.10.15 id=boot
chainlink_1  | creating application: parse "\"eth url here and such\"": invalid URI for request
chainlink_chainlink_1 exited with code 1
```
The same thing happens when I use single quotes.

It gets worse when I remove the quotes:
```
Recreating chainlink_chainlink_1 ... done
Attaching to chainlink_chainlink_1
chainlink_1  | panic: runtime error: invalid memory address or nil pointer dereference
chainlink_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8ba81e]
chainlink_1  |
chainlink_1  | goroutine 1 [running]:
chainlink_1  | github.com/smartcontractkit/chainlink/core/logger.SetLogger.func1()
chainlink_1  |  /chainlink/core/logger/default.go:47 +0x9e
chainlink_1  | github.com/smartcontractkit/chainlink/core/logger.SetLogger(0xc001471500)
chainlink_1  |  /chainlink/core/logger/default.go:57 +0x85
chainlink_1  | github.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode(0xc0001c2180, 0xc000bdc6e0, 0x0, 0x0)
chainlink_1  |  /chainlink/core/cmd/local_client.go:62 +0x215
chainlink_1  | github.com/urfave/cli.HandleAction(0x182eb20, 0xc000adda10, 0xc000bdc6e0, 0xc000bdc6e0, 0x0)
chainlink_1  |  /go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0x105
chainlink_1  | github.com/urfave/cli.Command.Run(0x1ae80ca, 0x5, 0x0, 0x0, 0xc0000a77a0, 0x2, 0x2, 0x1bda85a, 0x16, 0x0, ...)
chainlink_1  |  /go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x579
chainlink_1  | github.com/urfave/cli.(*App).RunAsSubcommand(0xc00026cc40, 0xc000bdc420, 0x0, 0x0)
chainlink_1  |  /go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405 +0x914
chainlink_1  | github.com/urfave/cli.Command.startApp(0x1ada0ce, 0x4, 0x0, 0x0, 0xc000addd00, 0x1, 0x1, 0x1c15831, 0x33, 0x0, ...)
chainlink_1  |  /go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372 +0x7ff
chainlink_1  | github.com/urfave/cli.Command.Run(0x1ada0ce, 0x4, 0x0, 0x0, 0xc000addd00, 0x1, 0x1, 0x1c15831, 0x33, 0x0, ...)
chainlink_1  |  /go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102 +0x9d4
chainlink_1  | github.com/urfave/cli.(*App).Run(0xc00026c540, 0xc00003c050, 0x5, 0x5, 0x0, 0x0)
chainlink_1  |  /go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x808
chainlink_1  | main.Run(0xc0001c2180, 0xc00003c050, 0x5, 0x5)
chainlink_1  |  /chainlink/core/main.go:20 +0x65
chainlink_1  | main.main()
chainlink_1  |  /chainlink/core/main.go:14 +0x4e
chainlink_chainlink_1 exited with code 2
```

- Network: Ethereum
- Blockchain Client: N/A
- Go Version: 1.17.2
- Operating System: Ubuntu 20.04 64x
- Commit: 788d0b9d8ba2c36d5d9e3f19e21deef3c611d8d9 (version 0.10.15)
- Hosting Provider: Microsoft Azure
- Startup Command: N/A

**Environment Variables**
N/A

**Steps to Reproduce**
Use the `environment:` option in Docker to set env vars.

**Additional Information**
When I terminate the string with a NULL character: `\0`, and use no quotes, it seems to pass the parsing, BUT, then when it needs to use the URL, the URL ends with `%5C0` :)

**Comment by prashantkumar1982** [comment]
I tried to locally repro this issue, but couldn't.

Firstly, please note that the error that this issue reports, this one:
node_1 | 2022-01-20T22:36:03Z [INFO] Starting Chainlink Node 1.0.1 at commit 03448cf24275227d69fe33bf2c4849dd64b56a89 cmd/local_client.go:60 InstanceUUID=e71d91ad-0639-4643-8ae9-28ec34d9464e SHA=03448cf24275227d69fe33bf2c4849dd64b56a89 Version=1.0.1 id=boot
node_1 | creating application: parse "wss": invalid URI for request
node2_node_1 exited with code 1

This error is correct.
If the ETH_URL parameter is not a valid URL, chainlink node will fail to start, and give an error, like it is giving already.

Secondly, I am not able to repro the crash in chainlink. It always throws the above error correctly(for quotes double/single, and without them too).

Here's my setup.
The docker.compose file I am using:

services:
node:
image: smartcontract/chainlink:1.0.1-nonroot
ports:
- 6688:6688
volumes:
- ./../../chainlink:/chainlink
environment:
ETH_URL: 'wss'

Command I used:
docker-compose up


Please feel free to open it again, with clear steps for how to repro this crash, if you still see this.

**Comment by pappas999** [comment]
Thanks @prashantkumar1982 , feel free to comment here again in the future if you ever are able to reproduce the issue. For now we will leave it closed if you can't
