### ISSUE TITLE
[FEAT] v2 toml based http task can't do interpolation of url ?

### ISSUE THREAD

**Issue by garyng2000** [smartcontractkit/chainlink#5270]
in the old v1 json based setup, it is possible to add query string and other info for a 'pre-defined url' in the job. the new one seems to be either hard coded in the job, or full url in the request.

Both are not ideal as it is a common usage that the url is fixed with some variation via query string or header. or have I missed something ? the Go code seems to indicate that it is the case, so is the documentation of TOML task

**Comment by PatrickAlphaC** [comment]
Sorry on the delay here. Yes, you should be able to add generic variables to jobs. Take a look at the direct request documentation: https://docs.chain.link/docs/jobs/types/direct-request/

**Comment by garyng2000** [comment]
??? what do you mean by generic variables ?

**Comment by PatrickAlphaC** [comment]
For example, if you added a variable in your solidity like "url"

```
req.add("jsonPath", "url");
```

You could access it in your jobspec like so:

```
parse [type="http" path="$(decode_cbor.url)" data="$(fetch)"]
```
