### ISSUE TITLE
Hackers stole my $60,000 digital currency , the transaction record involve the official address of chainlink

### ISSUE THREAD

**Issue by blockchainer2** [smartcontractkit/chainlink#5394]
Hackers stole my $60,000 digital currency , the transaction record involve the official address of chainlink, what should I do?

thodges-gh address: 0x87002564f1c7b8f51e96ca7d545e43402bf0b4ab
Send Kether to 0x350ef1c0342ac8d8649982960ee31bfd75a35dc7 as the subsequent transaction fee
0x350ef1c0342ac8d8649982960ee31bfd75a35dc7 sends Kether to the hacker‘s address 0x500000000973501dC823e04e9ad917157239e1Df as the subsequent transaction fee 

https://medium.com/@lucas9966/hackers-stole-my-60-000-digital-currency-the-transaction-record-involve-the-official-address-of-f128d6db8ed7

**Comment by pappas999** [comment]
hi @blockchainer2 , I've passed the details to the relevant internal team here, they'll reach out to you if they need to. Suggest updating your blog post to include a contact email address, thanks
