### ISSUE TITLE
Adding Job - CreateJobFailed: invalid db type: pg.Q

### ISSUE THREAD

**Issue by cryply** [smartcontractkit/chainlink#5494]
**Description**
I following official docs https://docs.chain.link/docs/fulfilling-requests/
but unable to create new job.

**Your Environment**
Recommended software, Ubuntu 20.
Node 14.17.4
PSQL 12.9
postgresql-12                                   12.9-0ubuntu0.20.04.1

**Basic Information**
Task is to create own oracle and upload job on own test node on Kovan testnet
[bug.log](https://github.com/smartcontractkit/chainlink/files/7580322/bug.log)

**Steps to Reproduce**
Follow creating job from https://docs.chain.link/docs/fulfilling-requests/

**Comment by pinebit** [comment]
This shall be fixed in https://github.com/smartcontractkit/chainlink/pull/5452

**Comment by PatrickAlphaC** [comment]
Great, closing. Thank you!
