### ISSUE TITLE
[NODE] Whitescreen after login to GUI + Job times increased by factor 30-40  

### ISSUE THREAD

**Issue by Tobias35** [smartcontractkit/chainlink#5535]
**Description**
whitescreen:
After login to the node operator gui it usually goes white/blank. 
Sometimes it remains working for a few clicks but goes blank again. 
This behavior has been observed in many previous issues also related to toml jobs.  

job times: 
on 0.10.15 the version we are currently using for our DON we observe job times of 1-3s. (according to the gui)
as we managed to test 1.0.1 with a few mainnet jobs it turns out the jobs now take 30-40s. (screenshot)
this is obviously not an option.  

**Basic Information**
dockerized cl node 
the setup is completely identical apart from the node version obviously 

- Network: Polygon POS 
![cl](https://user-images.githubusercontent.com/16675464/143673442-cf4f0ecc-e17a-4140-b6b4-6c8e2d4908ab.png)

**Steps to Reproduce**
install 1.0.1

**Additional Information**
Browser: tested on Chrome and Firefox
we are trying to upgrade our DON (8 nodes) past 0.10.15 but the new versions are no option due to white/blank screen bugs etc.

**Comment by PatrickAlphaC** [comment]
adding
