### ISSUE TITLE
Polygon BUIDL IT Hackathon Sponsor Prize

### ISSUE THREAD

**Issue by pappas999** [smartcontractkit/chainlink#5541]
# Polygon BUIDL IT: Chainlink Prizes #

## Prize Bounty🏅 
$6,000 in LINK to be given out to the best projects that utilize Chainlink as part of the [Polygon BUIDL IT](https://buidlit.polygon.technology/) Hackathon. Chainlink's decentralized oracle network provides reliable, tamper-proof inputs and outputs for complex smart contracts on any blockchain. [Get started with Chainlink and Solidity here!](https://docs.chain.link/docs/beginners-tutorial/). If more than 3 valid submissions are recieved, we will pick the 3 best submissions, and give them $2000 in LINK each. If less than 3 submissions are received, we will distribute the prize money among the valid submissions

## Challenge Description 📜 
Build something awesome using Chainlink! You must use Chainlink to make a state change on the blockchain to be eligible. Anything that came from the [Chainlink Documentation](https://docs.chain.link/) counts, using [Price Feeds](https://docs.chain.link/docs/using-chainlink-reference-contracts/), [VRF](https://docs.chain.link/docs/chainlink-vrf/), [Any-API](https://docs.chain.link/docs/request-and-receive-data/) or [Keepers](https://docs.chain.link/docs/chainlink-keepers/introduction/)

## Submission Requirements 📄 
You must use Chainlink to make a state change on the blockchain to be eligible. Anything that came from the [Chainlink Documentation](https://docs.chain.link/) counts. For example, you must successfully make a state change in a smart contract that's used Chainlink Price Feeds, Any-API, VRF or Keepers

## Judging Criteria 🧑‍⚖️ 
We will look at the following criteria:

- UI/UX/DX
How useable is your application? Is it visually appealing?
- Originality
How Creative is your project? Is it something we've never seen before? A new concept?
- Technicality
How technically challenging is your application?
- Practicality
Is this something people would actually use and want?
- Wow Factor
Anything not covered above! This is if you blow us away in some other way.

## Submission Deadline:  📆 
December 12th, 11:00 CEST

## Winner Announcement Date  🗓️ 
Judging will be completed at the end of the Hackathon on December 19th

**Comment by Tobias35** [comment]
Hello 
Is it possible for an exisiting project to apply ?

**Comment by pappas999** [comment]
Hi @Tobias35 , the code must be written as part of the hackathon. So you can take an existing project and build upon it, and you will be judged for the improvements done during the hackathon. But you can't just take an existing submission and submit it to this hackathon. Hope that makes sense

**Comment by Tobias35** [comment]
Hey okay thx

**Comment by pappas999** [comment]
prizes all paid out, Winners are the following:

2k USD in LINK
-  [Rupya](https://devfolio.co/submissions/rupya-776b)
- [dSIP](https://devfolio.co/submissions/dsip-4481)

1k USD in LINK
- [Netxtree](https://devfolio.co/submissions/netxtree-landlove-82c5): LandLove
- [DAOlaal](https://devfolio.co/submissions/daolaal-9296)
