### ISSUE TITLE
Cleanup Branches

### ISSUE THREAD

**Issue by NavyAdmiral** [smartcontractkit/chainlink#560]
Hi. There are 65 branches, most of which no loner serve any purpose. Why not clean them up?
![image](https://user-images.githubusercontent.com/40662484/45366839-cc846b00-b5ad-11e8-8c4d-83e325ad90f5.png)

**Comment by se3000** [comment]
We're down to 2 non-active branches, which we're keeping around for some work done on them. I'm going to close this out now, but feel free to reopen if it gets out of hand. Thanks for bringing it up.
