### ISSUE TITLE
Chainlink Node requestEthereumPrice() and currentPrice() doesnt work

### ISSUE THREAD

**Issue by GitCulture** [smartcontractkit/chainlink#5624]
**Description**
After Call requestEthereumPrice from  ATestnetConsumer 0xB28b4Bc029712353ddA7F5BE33C50209A568f45E in Remix IDE transaction is confirmed but currentPrice() still shows   "  0:  uint256: 0"
On Chainlink dashboard that is running on my localhost:6688 there is no jub runs after all. PLEASE HELP !
Tx_hash: 0xa51d28e1e8f4d3959857b84d99ef97ead2e4b653f6ac4ba8e0c7f89f0667bced
**Your Environment**
Docker and Infiura
Oracle.sol ("0x3Ae193D62Aa89E77eA0dF90C4E081b09D6fF7940")

**Basic Information**

    Network: Rinkeby
    Blockchain Client: Infura
    Go Version: Not sure
    Operating System: Ubuntu 20.04.3
    Commit: [log INFO line when starting node]
    Startup Command: cd ~/.chainlink-rinkeby && docker run -p 6688:6688 -v ~/.chainlink-kovan:/chainlink -it --env-file=.env --network host smartcontract/chainlink:1.0.0 local n

    Smart contract calling the oracle:
ATestnetConsumer.sol

**Steps to Reproduce**

step-by-step with : 
https://docs.chain.link/docs/fulfilling-requests/

**Comment by andrejrakic** [comment]
Hi @GitCulture would you be kind to tell me do you use Job v1 or v2?

**Comment by GitCulture** [comment]
`type = "directrequest"
schemaVersion = 1
name = "Get > Uint256"
contractAddress = "0x3Ae193D62Aa89E77eA0dF90C4E081b09D6fF7940"
maxTaskDuration = "0s"
observationSource = """
    decode_log   [type="ethabidecodelog"
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]

    decode_cbor  [type="cborparse" data="$(decode_log.data)"]
    fetch        [type="http" method=GET url="$(decode_cbor.get)"]
    parse        [type="jsonparse" path="$(decode_cbor.path)" data="$(fetch)"]
    multiply     [type="multiply" input="$(parse)" times=100]
    encode_data  [type="ethabiencode" abi="(uint256 value)" data="{ \\"value\\": $(multiply) }"]
    encode_tx    [type="ethabiencode"
                  abi="fulfillOracleRequest(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes32 data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"
                 ]
    submit_tx    [type="ethtx" to="0x3Ae193D62Aa89E77eA0dF90C4E081b09D6fF7940" data="$(encode_tx)"]

    decode_log -> decode_cbor -> fetch -> parse -> multiply -> encode_data -> encode_tx -> submit_tx
"""
externalJobID = "5d05b310-ff49-4978-a1d2-f8e5fe88b856"
`

V2

**Comment by GitCulture** [comment]
`
type = "directrequest"
schemaVersion = 1
name = "Get > Uint256"
contractAddress = "0x3Ae193D62Aa89E77eA0dF90C4E081b09D6fF7940"
maxTaskDuration = "0s"
observationSource = """
    decode_log   [type="ethabidecodelog"
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]

    decode_cbor  [type="cborparse" data="$(decode_log.data)"]
    fetch        [type="http" method=GET url="$(decode_cbor.get)"]
    parse        [type="jsonparse" path="$(decode_cbor.path)" data="$(fetch)"]
    multiply     [type="multiply" input="$(parse)" times=100]
    encode_data  [type="ethabiencode" abi="(uint256 value)" data="{ \\"value\\": $(multiply) }"]
    encode_tx    [type="ethabiencode"
                  abi="fulfillOracleRequest(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes32 data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"
                 ]
    submit_tx    [type="ethtx" to="0x3Ae193D62Aa89E77eA0dF90C4E081b09D6fF7940" data="$(encode_tx)"]

    decode_log -> decode_cbor -> fetch -> parse -> multiply -> encode_data -> encode_tx -> submit_tx
"""
externalJobID = "5d05b310-ff49-4978-a1d2-f8e5fe88b856"


`

**Comment by GitCulture** [comment]
''
type = "directrequest"
schemaVersion = 1
name = "Get > Uint256"
contractAddress = "0x3Ae193D62Aa89E77eA0dF90C4E081b09D6fF7940"
maxTaskDuration = "0s"
observationSource = """
    decode_log   [type="ethabidecodelog"
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]

    decode_cbor  [type="cborparse" data="$(decode_log.data)"]
    fetch        [type="http" method=GET url="$(decode_cbor.get)"]
    parse        [type="jsonparse" path="$(decode_cbor.path)" data="$(fetch)"]
    multiply     [type="multiply" input="$(parse)" times=100]
    encode_data  [type="ethabiencode" abi="(uint256 value)" data="{ \\"value\\": $(multiply) }"]
    encode_tx    [type="ethabiencode"
                  abi="fulfillOracleRequest(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes32 data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"
                 ]
    submit_tx    [type="ethtx" to="0x3Ae193D62Aa89E77eA0dF90C4E081b09D6fF7940" data="$(encode_tx)"]

    decode_log -> decode_cbor -> fetch -> parse -> multiply -> encode_data -> encode_tx -> submit_tx
"""
externalJobID = "5d05b310-ff49-4978-a1d2-f8e5fe88b856"
''

**Comment by GitCulture** [comment]
"""
type = "directrequest"
schemaVersion = 1
name = "Get > Uint256"
contractAddress = "0x3Ae193D62Aa89E77eA0dF90C4E081b09D6fF7940"
maxTaskDuration = "0s"
observationSource = """
    decode_log   [type="ethabidecodelog"
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]

    decode_cbor  [type="cborparse" data="$(decode_log.data)"]
    fetch        [type="http" method=GET url="$(decode_cbor.get)"]
    parse        [type="jsonparse" path="$(decode_cbor.path)" data="$(fetch)"]
    multiply     [type="multiply" input="$(parse)" times=100]
    encode_data  [type="ethabiencode" abi="(uint256 value)" data="{ \\"value\\": $(multiply) }"]
    encode_tx    [type="ethabiencode"
                  abi="fulfillOracleRequest(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes32 data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"
                 ]
    submit_tx    [type="ethtx" to="0x3Ae193D62Aa89E77eA0dF90C4E081b09D6fF7940" data="$(encode_tx)"]

    decode_log -> decode_cbor -> fetch -> parse -> multiply -> encode_data -> encode_tx -> submit_tx
"""
externalJobID = "5d05b310-ff49-4978-a1d2-f8e5fe88b856"

"""

**Comment by GitCulture** [comment]
There are no Job runs , Im sending 1 link to  ATestnetConsumer.sol and requestEthereumPrice with success, but after Im trying to use currentPrice function im getting    " 0:   uint256: 0  "   as output

**Comment by GitCulture** [comment]
'
ROOT=/chainlink
LOG_LEVEL=debug
ETH_CHAIN_ID=4
MIN_OUTGOING_CONFIRMATIONS=2
LINK_CONTRACT_ADDRESS=0x01BE23585060835E02B77ef475b0Cc51aA1e0709
CHAINLINK_TLS_PORT=0
SECURE_COOKIES=false
GAS_UPDATER_ENABLED=true
ALLOW_ORIGINS=*
ETH_URL=wss://rinkeby.infura.io/ws/v3/a7755bae70424b8683d5f5ea973fc637
DATABASE_URL=postgres://xgjmlxhcolzaab:bd47bde39eee08184fc726743991b4ec52782691d562a3b125392d62730cc194@ec2-54-74-60-70.eu-west-1.compute.amazonaws.com:5432/df7vqocgct7sf6
FEATURE_EXTERNAL_INITIATORS=true
DATABASE_TIMEOUT=0
'

**Comment by GitCulture** [comment]
ROOT=/chainlink
LOG_LEVEL=debug
ETH_CHAIN_ID=4
MIN_OUTGOING_CONFIRMATIONS=2
LINK_CONTRACT_ADDRESS=0x01BE23585060835E02B77ef475b0Cc51aA1e0709
CHAINLINK_TLS_PORT=0
SECURE_COOKIES=false
GAS_UPDATER_ENABLED=true
ALLOW_ORIGINS=*
ETH_URL=wss://rinkeby.infura.io/ws/v3/a7755bae70424b8683d5f5ea973fc637
DATABASE_URL=postgres://
FEATURE_EXTERNAL_INITIATORS=true
DATABASE_TIMEOUT=0

**Comment by GitCulture** [comment]
error from terminal 

`[ERROR] HeadTracker: got very old block with number 9786696 (highest seen was 13755357). This is a problem and either means a very deep re-org occurred, or the chain went backwards in block numbers. This node will not function correctly without manual intervention. headtracker/head_listener.go:147 `

**Comment by andrejrakic** [comment]
@GitCulture Should the startup command be 
```
cd ~/.chainlink-rinkeby && docker run -p 6688:6688 -v ~/.chainlink-rinkeby:/chainlink -it --env-file=.env smartcontract/chainlink:1.0.0 local n
``` 
instead of 
```
cd ~/.chainlink-rinkeby && docker run -p 6688:6688 -v ~/.chainlink-kovan:/chainlink -it --env-file=.env --network host smartcontract/chainlink:1.0.0 local n
```
?

**Comment by andrejrakic** [comment]
[Here](https://github.com/smartcontractkit/chainlink/issues/5624#issue-1072800630) you provided next startup command
```
cd ~/.chainlink-rinkeby && docker run -p 6688:6688 -v ~/.chainlink-kovan:/chainlink -it --env-file=.env --network host smartcontract/chainlink:1.0.0 local n
```

It should be 
```
cd ~/.chainlink-rinkeby && docker run -p 6688:6688 -v ~/.chainlink-rinkeby:/chainlink -it --env-file=.env smartcontract/chainlink:1.0.0 local n
```

**Comment by PatrickAlphaC** [comment]
Closing this for now, this is an issue with your ETH 1 connection.

```
[ERROR] HeadTracker: got very old block with number 9786696 (highest seen was 13755357). This is a problem and either means a very deep re-org occurred, or the chain went backwards in block numbers. This node will not function correctly without manual intervention. headtracker/head_listener.go:147
```
