### ISSUE TITLE
[SMRT] Typo in VRFConsumerBase.sol

### ISSUE THREAD

**Issue by AbdoSharaf7** [smartcontractkit/chainlink#5678]
**Description**

In the "contracts/src/v0.8/VRFConsumerBase.sol" there is typo in a commented line #36 "constuctor" instead of "constructor"

**Basic Information**

Version: 1.0.1
Location: contracts/src/v0.8/VRFConsumerBase.sol
Line#: 36
issue: Typo
Impact: Developers who use search methods like "CTRL+F" to find specific parts will miss the info provided
Current State: "constuctor" instead of "constructor"

**Comment by pappas999** [comment]
thanks so much for raising this @AbdoSharaf7 ! I will forward it onto the team and monitor their progress. Will keep this issue open until it's resolved
