### ISSUE TITLE
AggregatorV3Interface broken

### ISSUE THREAD

**Issue by dataforestLTD** [smartcontractkit/chainlink#5717]
"The called function should be payable if you send value and the value you send should be less than your current balance"

No way to avoid this error.

**Comment by pappas999** [comment]
Hi @dataforestLTD , thanks for raising. What are you trying to do with the AggregatorV3Interface? What function are you calling, and what parameters are you using?

**Comment by dataforestLTD** [comment]
I got it figured out, I was using a price feed from a different chain and getting gas errors, using the correct price feed address now and everything is working perfectly!
