### ISSUE TITLE
Runs stuck in `pending_confirmations` when there is a high volume of new job runs

### ISSUE THREAD

**Issue by jleeh** [smartcontractkit/chainlink#576]
### System Information

- Network (Main net, Ropsten, etc.): Ropsten
- Ethereum client (Geth/Parity) and version: Parity 1.11.10
- Go version: 1.10
- Host OS: Amazon Linux
- Commit (INFO line when starting the node): aa0a1c61e1d7c679c7e67f278dc9cbb2e71dbe95 

### Environment Variables

```
LOG_LEVEL: debug
ROOT: <redacted>
CHAINLINK_PORT: 6688
ETH_URL: <redacted>
ETH_CHAIN_ID: 3
CLIENT_NODE_URL: http://localhost:6688
TX_MIN_CONFIRMATIONS: 12
TASK_MIN_CONFIRMATIONS: 0
ETH_GAS_BUMP_THRESHOLD: 12
ETH_GAS_BUMP_WEI: 5000000000
ETH_GAS_PRICE_DEFAULT: 20000000000
LINK_CONTRACT_ADDRESS: 0x514910771AF9Ca656af840dff83E8264EcF986CA
MINIMUM_CONTRACT_PAYMENT: 1000000000000000000
ORACLE_CONTRACT_ADDRESS:
DATABASE_POLL_INTERVAL: 500ms
ALLOW_ORIGINS: http://localhost:3000,http://localhost:6688
CHAINLINK_DEV: true
```

### Additional Information
The load I've been sending at the nodes on ropsten has been at a maximum of 20 an hour per node, I've recently doubled that and the maximum now can be 40 an hour. I'm sending 0-10 new runs to the node every 15 minutes.

To firstly show the graph of job run statuses, this has been over the last 3 days:
![image](https://user-images.githubusercontent.com/10528926/45686477-6e72fd00-bb44-11e8-813f-963e99f5bd2b.png)

As seen, the amount of jobs either `in_progress` or `pending_confirmations` steadily rises, then a huge amount are confirmed and then it rises again. With the gap in metrics over last night and this morning, the stats service couldn't scrape metrics as it was timing out at the load-balancer, which is set to a minute.

**Important to note:** This is only happening on one node, the other node in this period was completely fine.

On that one node which is seeing this issue, these errors are in the logs every minute or two:
```
2018-09-17T18:06:46Z [ERROR] Application Run Channel Executor: error executing run services/job_runner.go:128 status=in_progress error=ExecuteRun: Job#: id field must not be a zero value stacktrace=github.com/smartcontractkit/chainlink/logger.Errorw
2018-09-17T18:07:17Z [ERROR] Application Run Channel Executor: error finding run services/job_runner.go:122 error=not found stacktrace=github.com/smartcontractkit/chainlink/logger.Errorw
2018-09-17T18:07:17Z [ERROR] Application Run Channel Executor: error executing run services/job_runner.go:128 stacktrace=github.com/smartcontractkit/chainlink/logger.Errorw
/go/src/github.com/smartcontractkit/chainlink/services/job_runner.go:105 status=in_progress error=ExecuteRun: Job#: id field must not be a zero value
```

[node_in_progress_error.log](https://github.com/smartcontractkit/chainlink/files/2392634/node_in_progress_error.log)

I've also attached a subset of the logs from one of the jobs that is stuck in `pending_confirmations`. The logs is the output of a search of the run id `f314c9616c25432493aff486fcf88b3b`. When filtering this by the day, the subset of logs attached can be seen outputted all throughout the day, pretty much every minute.

I've double checked that our Parity instances on Ropsten haven't fallen out of sync, and they're fine and still syncing new blocks in sub 100ms on average.

During this time, there was also responses back from the node to the Oracle contract:
https://ropsten.etherscan.io/txs?a=0xd9675316cf0eb95000c0c57e003217199f19ec80&p=10

**Comment by thodges-gh** [comment]
@jleeh do you have the full logs from the Chainlink and Ethereum node during one of these problem points?

**Comment by jleeh** [comment]
Sure. Log dumps from the node and both Parity instances from 13:00-15:00 on the 17th.
[node.log](https://github.com/smartcontractkit/chainlink/files/2396440/node.log)
[parity-0.log](https://github.com/smartcontractkit/chainlink/files/2396441/parity-0.log)
[parity-1.log](https://github.com/smartcontractkit/chainlink/files/2396442/parity-1.log)

**Comment by dimroc** [comment]
Hey @jleeh, thanks for yet another great bug report. This PR may resolve the situation: https://github.com/smartcontractkit/chainlink/pull/591. To be completely thorough, we would need to investigate the parity node's block throughput. A stretch goal might be to plot the rate of new blocks against these job runs, since they're tied to confirmations.
