### ISSUE TITLE
[NODE] External adapter fulfilment call appears "stalled" until new job request appears

### ISSUE THREAD

**Issue by iangriggs** [smartcontractkit/chainlink#5766]
**Description**
Local chainlink node with Jobspec configured to call an external adapter (multi-params) via Operator.sol that seems to process all but the last request. On submitting another job the 'stalled' job appears to get fulfilled leaving that most recent job request stalled...etc.

**Basic Information**
Chainlink node is running locally on Docker on mac. Custom external adapter is a locally running express endpoint that returns multiple parameters to a ChainlinkClient contract that is configured for a Operator.sol contract instance.

Network: Avalanche Fuji
Blockchain Client: Moralis Speedy Node
Go Version: N/A
Operating System: Docker on Macbook following https://docs.chain.link/docs/running-a-chainlink-node/
Commit: 
Hosting Provider: self-hosted
Startup Command:
docker run -p 6688:6688 -v ~/.chainlink-fuji:/chainlink -it --env-file=.env smartcontract/chainlink:1.0.1 local n

**Environment Variables**
ALLOW_ORIGINS: *
BLOCK_BACKFILL_DEPTH: 10
BLOCK_HISTORY_ESTIMATOR_BLOCK_DELAY: 0
BLOCK_HISTORY_ESTIMATOR_BLOCK_HISTORY_SIZE: 0
BLOCK_HISTORY_ESTIMATOR_TRANSACTION_PERCENTILE: 0
BRIDGE_RESPONSE_URL:
ETH_CHAIN_ID: 43113
CLIENT_NODE_URL: http://localhost:6688
DATABASE_BACKUP_FREQUENCY: 1h0m0s
DATABASE_BACKUP_MODE: none
DATABASE_MAXIMUM_TX_DURATION: 30m0s
DATABASE_TIMEOUT:
DEFAULT_HTTP_LIMIT: 32768
DEFAULT_HTTP_TIMEOUT: 30m0s
CHAINLINK_DEV: false
ETH_DISABLED: false
ETH_HTTP_URL:
ETH_SECONDARY_URLS: []
ETH_URL: wss://speedy-nodes-nyc.moralis.io/.../avalanche/testnet/ws
EXPLORER_URL:
FM_DEFAULT_TRANSACTION_QUEUE_DEPTH: 1
FEATURE_EXTERNAL_INITIATORS: false
FEATURE_OFFCHAIN_REPORTING: false
GAS_ESTIMATOR_MODE:
INSECURE_FAST_SCRYPT: false
JSON_CONSOLE: false
JOB_PIPELINE_REAPER_INTERVAL: 1h0m0s
JOB_PIPELINE_REAPER_THRESHOLD: 24h0m0s
KEEPER_DEFAULT_TRANSACTION_QUEUE_DEPTH: 1
KEEPER_MAXIMUM_GRACE_PERIOD: 0
KEEPER_MINIMUM_REQUIRED_CONFIRMATIONS: 0
KEEPER_REGISTRY_CHECK_GAS_OVERHEAD: 0
KEEPER_REGISTRY_PERFORM_GAS_OVERHEAD: 0
KEEPER_REGISTRY_SYNC_INTERVAL:
LINK_CONTRACT_ADDRESS:
FLAGS_CONTRACT_ADDRESS:
LAYER_2_TYPE:
LOG_LEVEL: debug
LOG_SQL_MIGRATIONS: true
LOG_SQL: false
LOG_TO_DISK: true
OCR_BOOTSTRAP_CHECK_INTERVAL: 20s
TRIGGER_FALLBACK_DB_POLL_INTERVAL: 30s
OCR_CONTRACT_TRANSMITTER_TRANSMIT_TIMEOUT: 10s
OCR_DATABASE_TIMEOUT: 10s
OCR_DEFAULT_TRANSACTION_QUEUE_DEPTH: 1
OCR_INCOMING_MESSAGE_BUFFER_SIZE: 10
P2P_BOOTSTRAP_PEERS: []
P2P_LISTEN_IP: 0.0.0.0
P2P_LISTEN_PORT:
P2P_NETWORKING_STACK: V1
P2P_PEER_ID:
P2PV2_ANNOUNCE_ADDRESSES: []
P2PV2_BOOTSTRAPPERS: []
P2PV2_DELTA_DIAL: 15s
P2PV2_DELTA_RECONCILE: 1m0s
P2PV2_LISTEN_ADDRESSES: []
OCR_OUTGOING_MESSAGE_BUFFER_SIZE: 10
OCR_NEW_STREAM_TIMEOUT: 10s
OCR_DHT_LOOKUP_INTERVAL: 10
OCR_TRACE_LOGGING: false
CHAINLINK_PORT: 6688
REAPER_EXPIRATION: 240h0m0s
REPLAY_FROM_BLOCK: -1
ROOT: /chainlink
SECURE_COOKIES: false
SESSION_TIMEOUT: 15m0s
TELEMETRY_INGRESS_LOGGING: false
TELEMETRY_INGRESS_SERVER_PUB_KEY:
TELEMETRY_INGRESS_URL:
CHAINLINK_TLS_HOST:
CHAINLINK_TLS_PORT: 0
CHAINLINK_TLS_REDIRECT: false

**Steps to Reproduce**
Happy to create a full repro with minimal code if necessary to progress this. 

Just raising this issue in minimal form as I wondered if problem has already been seen before and fixed in some way for v1.1.0? 

**Additional Information**
Jobs I'm running are relatively long running...2 mins and above...could is this relevant?

**Comment by iangriggs** [comment]
@ZakAyesh, @PatrickAlphaC  - let me know if you need more info around repro, happy to help.

**Comment by PatrickAlphaC** [comment]
Hi sorry on this, backlogged. What version of the Chainlink node is this?

**Comment by iangriggs** [comment]
Hi Patrick. This was the same Chainlink instance I was using when I posted https://github.com/smartcontractkit/chainlink/issues/5728 (that has more env info in the issue).

The docker image then was chainlink:1.0.1.

**Comment by PatrickAlphaC** [comment]
Can you try on a newer instance? Like 1.1.1?

**Comment by iangriggs** [comment]
Hi @PatrickAlphaC ... I've performed some tests this afternoon and I'm not seeing the same problem with v1.1.1

Based on that you may wish to close this issue? Thanks!

**Comment by PatrickAlphaC** [comment]
Awesome! Thank you!
