### ISSUE TITLE
[JAVA/Android] <Remapping @chainlink import>

### ISSUE THREAD

**Issue by Gojic** [smartcontractkit/chainlink#5816]
**Description**
[I am getting File not found while trying to import  AggregatorV3Interface in AndroidStudio project]

**Your Environment**
[I am using Java ,AndroidStudio and PoweShell to create .bin and .abi files]

**Basic Information**
[Well i am getting error that File not found and need to remap path to AggregatorV3Interface.sol.I know that you can do this with Brownie in Python,but how to do this with Java/Android Studio.I tried to cerate .yaml file and to put dependecies like that but the problem still there]

**Steps to Reproduce**
[in power shell i am using this command  `solc src\main\res\solidity\solidity\FundMe.sol --bin --abi --optimize -o src\main\res\solidity\out`]

**Comment by pappas999** [comment]
thanks for raising @Gojic . This sounds more like a technical issue around using the chainlink libraries as opposed to an issue with the libraries themselves. Based on this, can you please raise your issue on [stackoverflow](https://stackoverflow.com/questions/ask?tags=chainlink), posting full code and steps to reproduce, and we can take the conversation there. If there is some underlying issue with the contracts, I'll re-open this and amend the info
