### ISSUE TITLE
[DEVEL] Postgres cluster support

### ISSUE THREAD

**Issue by killzoner** [smartcontractkit/chainlink#5846]
**Description**
I am trying to run a node using postgresql cluster from which connection string is as following `postgres://user:password@node1,node2,node3/mydb`

I couldn't find information about official support (maybe I've missed it), looking at the code I saw that this repository is using `jackc/pgx/v4` which I do know allows this support, but I also found this one code path (https://github.com/smartcontractkit/chainlink/blob/develop/core/services/pg/event_broadcaster.go#L74) where `lib/pq` is used, and this library does NOT support postgresql cluster configuration.

Can you state official support for postgresql cluster, and if my assumption is correct ?
If `lib/pq` is blocking the path, happy to work on a PR to add the feature.

**Comment by andrejrakic** [comment]
@killzoner, thanks for raising this issue! Currently, there is no support due to the library. I'll speak to the team regarding future support and get back to you.

**Comment by killzoner** [comment]
Thanks @andrejrakic , let me know if I can help in the process

**Comment by braddmiller** [comment]
Hey @killzoner, we do not support postgres clusters and it's not on our roadmap right now to add it. Is this a strict blocker for you for a project you're working on?

**Comment by killzoner** [comment]
No it's not a blocker, we are just trying to avoid SPOF as much as possible in our infrastructure and have more reliable solutions in case of server failures. But it will do for now. Thanks for answering @braddmiller

**Comment by killzoner** [comment]
Hey there, reopening this ticket to see if we can have something on the roadmap at some point.
We are trying to remove SPOFs as much as possible from our services, and this feature would be much needed

**Comment by pappas999** [comment]
thanks for raising @killzoner , I'll check again with the team to see if anything has changed since the last response
