### ISSUE TITLE
[NODE] Chainlink Node Crashes on Job run containing ethabiencode

### ISSUE THREAD

**Issue by Chad2302** [smartcontractkit/chainlink#5954]
**Description**
Chainlink Node Crashes on Job run containing ethabiencode(https://stackoverflow.com/questions/71024265/chainlink-node-crashes-on-job-run-containing-ethabiencode)

**Basic Information**
My chainlink node crashes everytime I run a function with ethabiencode in it

My Node Job is currently set up on polygon mumbai testnet and i can run other request such as direct requests and bridges

type = "directrequest"
schemaVersion = 1
name = "Veri-Test-2"
contractAddress = "ORACLE_ADDRESS"
maxTaskDuration = "0s"
observationSource = """
decode_log   [type="ethabidecodelog" abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)" data="$(jobRun.logData)" topics="$(jobRun.logTopics)"]

decode_cbor  [type="cborparse" data="$(decode_log.data)"]

encode_tx   [type="ethabiencode" abi="fulfillTestingFunction(bytes32 requestID, bytes32 resulttt)" data="{ \\"requestID\\": $(jobSpec.externalJobID),\\"resulttt\\": 48692043686164000000000000000000000000000000000000000000000000}"]

submit_tx    [type="ethtx" to="ORACLE_ADDRESS" data="$(encode_tx)"]

   decode_log   ->  decode_cbor  ->  encode_tx   -> submit_tx
"""

then my eth return function is defined as follows

function fulfillTestingFunction(bytes32 requestID, bytes32 resulttt)
    public
    recordChainlinkFulfillment(requestID)
  {
  
    _result = bytes32ToString(resulttt);
  }

I have created the Oracle and Activated the node on the oracle contract
I have funded the Oracle ontract with Polygon
I have funded the Contract with the contract with Link to pay for the request
I have been able to run other request successfuly but just not submit back to blockchain
Any help would be greatly appreciated !

- Network: Mumbai Polygon- Operating System: [name and version of operating system running Chainlink node]
- Hosting Provider: Google cloud platform

**Comment by PatrickAlphaC** [comment]
Thanks! Will pass this on to investigate.

**Comment by braddmiller** [comment]
@Chad2302 What version of the chainlink node are you running? We believe this was fixed in the 1.1.0 release.

**Comment by PatrickAlphaC** [comment]
Going to close, looks like this is fixed in more recent versions.
