### ISSUE TITLE
ETHDenver 2022 Hackathon Sponsor Prizes

### ISSUE THREAD

**Issue by ZakAyesh** [smartcontractkit/chainlink#5978]
# ETHDenver 2022 Hackathon: Chainlink Prizes #

## Prize Bounties🏅 
A total of $25,000 in LINK to be given out to the best projects that utilize Chainlink as part of the [ETHDenver 2022 Hackathon](https://www.ethdenver.com/judging).

In-Person
- Grand Prize: $4,500 in LINK to the overall best project using Chainlink.
- Eight Runner-Ups: $1,000 in LINK to eight runner-ups using Chainlink for a total of $8,000.

Virtual
- Grand Prize: $4,500 in LINK to the overall best project using Chainlink.
- Eight Runner-Ups: $1,000 in LINK to eight runner-ups using Chainlink for a total of $8,000.

Chainlink's decentralized oracle network provides reliable, tamper-proof inputs and outputs for complex smart contracts on any blockchain. [Get started with Chainlink and Solidity here!](https://docs.chain.link/docs/beginners-tutorial/) 

If more than 9 valid submissions are received, we will pick the best submission for the grand prize, and give the eight runner-ups $2000 in LINK each. If less than 8 submissions are received, we will pick the best submission or the grand prize and the runner-up prize money will be split among the remaining valid submissions.

## Challenge Description 📜 
Build something awesome using Chainlink! You must use Chainlink to make a state change on the blockchain to be eligible. Anything that came from the [Chainlink Documentation](https://docs.chain.link/) counts, using [Price Feeds](https://docs.chain.link/docs/using-chainlink-reference-contracts/), [VRF](https://docs.chain.link/docs/chainlink-vrf/), [Any-API](https://docs.chain.link/docs/request-and-receive-data/) or [Keepers](https://docs.chain.link/docs/chainlink-keepers/introduction/)

## Submission Requirements 📄 
You must use Chainlink to make a state change on the blockchain to be eligible. Anything that came from the [Chainlink Documentation](https://docs.chain.link/) counts. For example, you must successfully make a state change in a smart contract that's used Chainlink Price Feeds, Any-API, VRF or Keepers

## Judging Criteria 🧑‍⚖️ 
We will look at the following criteria:

- UI/UX/DX
How useable is your application? Is it visually appealing?
- Originality
How Creative is your project? Is it something we've never seen before? A new concept?
- Technicality
How technically challenging is your application?
- Practicality
Is this something people would actually use and want?
- Wow Factor
Anything not covered above! This is if you blow us away in some other way.

## Submission Deadline:  📆 
In Person:
February 20th 8:00am MST

Virtual:
March 21st, Time TBD

## Winner Announcement Date  🗓️ 
In Person:
February 20th 5:30pm MST

Virtual:
March 24th, Time TBD

**Comment by PatrickAlphaC** [comment]
Hackathon is over, closing.
