### ISSUE TITLE
[NODE] Node jobs do not work following quickstart guide 

### ISSUE THREAD

**Issue by typechip** [smartcontractkit/chainlink#6060]
**Description**
I have followed the quickstart guide to try the Running a Chainlink Node + Fulfilling Requests. I have tried several options and have not been able to get the Chainlink node to execute any job. 

**Basic Information**
I'm running a Chainlink Node locally, I followed the [quickstart guide](https://docs.chain.link/docs/running-a-chainlink-node/) and I deployed the contracts as discribed [here ](https://docs.chain.link/docs/fulfilling-requests/) to test the API request functionality. I have done it in `rinkeby`, with an external RPC provider (infura -  websocket connection string)  with LINK token obtained from the faucet. The node has ETH balance, displayed in the UI which confirms that the RPC provider is working. In no case have I managed to run the jobs, the chainlink node does not log any errors, only [DEBUG] logs that look normal (Received Head, Processed Head, ....).

In the contracts side everything seems right, after running que request with `requestEthereumPrice` from `ATestnetConsumer `the oracle receives the request and LINK and logs the event `OracleRequest (index_topic_1 bytes32 specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)`
https://rinkeby.etherscan.io/address/0x55c2Db75484A4D6EfD366A2d9D70424f45b532b8#events

I have tried different docker images, tags: [1.1.1-nonroot](https://hub.docker.com/layers/smartcontract/chainlink/1.1.1-nonroot/images/sha256-5b9257c76a468f1e58e34d2abfcce5eb311a2da39abf663bfba8ab3a0e48b2ea?context=explore) and [1.1.0-nonroot](https://hub.docker.com/layers/smartcontract/chainlink/1.1.0-nonroot/images/sha256-a7c29c054f1d1e242a9ce528cd94b0fddda02444da55fd961d1f06245a4289aa?context=explore)

I have also tried:
- different RPC provider with `wss` Moralis, Infura, ...- UNSUCCESSFUL
- building the chainlink node from the sources (dev branch) to test with BSC testnet - UNSUCCESSFUL

---
- Network: Rinkeby
- Blockchain Client: External provider (INFURA)
- Go Version: n/a
- Operating System: Ubuntu 20.04 LTS
- Commit: 1c68864ca5235efa9ef29be233642e2d88c02b88
- Hosting Provider: self-hosted
- Startup Command: 
```
cd ~/.chainlink-rinkeby && docker run -p 6688:6688 -v ~/.chainlink-rinkeby:/chainlink -it --env-file=.env smartcontract/chainlink:1.1.1-nonroot local n
```

**Environment Variables**
```
ROOT=.
LOG_LEVEL=debug
ETH_CHAIN_ID=4
CHAINLINK_TLS_PORT=0
SECURE_COOKIES=false
ALLOW_ORIGINS=*
ETH_URL=wss://rinkeby.infura.io/ws/v3/*********************************
DATABASE_URL=postgresql://postgres:mysecretpassword@172.17.0.2:5432/postgres?sslmode=disable
````

**Steps to Reproduce**
 [running-a-chainlink-node](https://docs.chain.link/docs/running-a-chainlink-node/)  [fulfilling-requests](https://docs.chain.link/docs/fulfilling-requests/)
 
 ***Additional information***
 From the doc, this is the job code I'm using:
 ```
 type = "directrequest"
schemaVersion = 1
name = "Get > Uint256"
# Optional External Job ID: Automatically generated if unspecified
# externalJobID = "b1d42cd5-4a3a-4200-b1f7-25a68e48aad8"
contractAddress = "YOUR_ORACLE_CONTRACT_ADDRESS"
maxTaskDuration = "0s"
observationSource = """
    decode_log   [type="ethabidecodelog"
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]

    decode_cbor  [type="cborparse" data="$(decode_log.data)"]
    fetch        [type="http" method=GET url="$(decode_cbor.get)"]
    parse        [type="jsonparse" path="$(decode_cbor.path)" data="$(fetch)"]
    multiply     [type="multiply" input="$(parse)" times=100]
    encode_data  [type="ethabiencode" abi="(uint256 value)" data="{ \\"value\\": $(multiply) }"]
    encode_tx    [type="ethabiencode"
                  abi="fulfillOracleRequest(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes32 data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"
                 ]
    submit_tx    [type="ethtx" to="YOUR_ORACLE_CONTRACT_ADDRESS" data="$(encode_tx)"]

    decode_log -> decode_cbor -> fetch -> parse -> multiply -> encode_data -> encode_tx -> submit_tx
"""


 ```

**Comment by rgottleber** [comment]
Hi,

I deployed a 1.1.1 node locally in docker and used the job code you supplied above.

Unfortunately, I'm not able to find any issue when I deploy the contracts myself. 

To double-check a couple of things,
- The LINK contract address was correct for Rinkeby when you deployed?
- Also, how long did you wait to check the price in the ATestnetConsumer?

**Comment by typechip** [comment]
Hi,

Thanks for your answer @[rgottleber](https://github.com/rgottleber) 

- Yes the LINK address was correct (`0x01BE23585060835E02B77ef475b0Cc51aA1e0709`)
- I waited more than half an hour

**Comment by typechip** [comment]
I found the problem:

![image](https://user-images.githubusercontent.com/96077562/155415949-d199931d-4ddd-4301-8ccc-d27c97b58501.png)

The external job id  in the doc has dash symbols `cf90dcbd-91fe-48a6-8d10-1f53eaa9b635`

If I remove them and run the `requestEthereumPrice ` with `_jobId = cf90dcbd91fe48a68d101f53eaa9b635` it works.

Chainlink Node 1.1.1 at commit [11788e23888b2d60554720faa237dabc62b1b8e7](https://github.com/smartcontractkit/chainlink/commit/11788e23888b2d60554720faa237dabc62b1b8e7)

**Comment by rgottleber** [comment]
Glad you found the issue, I was just going through this again and missed a `-` myself! They can be tricky for sure. 

I'll close this issue, if you need anything else let us know.

**Comment by typechip** [comment]
Ok, thank you!

**Comment by anantasty** [comment]
I just followed the Quickstart and was able to run it successfully. Can you ensure you do not have some sort of connectivity issues that could be cascading to this ?

**Comment by rgottleber** [comment]
Tracking in https://github.com/smartcontractkit/chainlink/issues/6094
