### ISSUE TITLE
[DEVEL] How to find the underlying asset address of oracle

### ISSUE THREAD

**Issue by gzliudan** [smartcontractkit/chainlink#6206]
Is there a document about the  underlying assets' address of oracle? For example, in document https://docs.chain.link/docs/matic-addresses/, I found:
```text
BTC / ETH	18	0x19b0F0833C78c0848109E3842D34d2fDF2cA69BA
BTC / USD	8	0xc907E116054Ad103354f2D350FD2514433D57F6f
......
WBTC / ETH	18	0xA338e0492B2F944E9F8C0653D3AD1484f2657a37
WBTC / USD	8	0xDE31F8bFBD8c84b5360CFACCa3539B938dd78ae6
```
It seems that BTC and WBTC are same asset, so I want to check the address of BTC and WBTC.

**Comment by ZakAyesh** [comment]
Hey good question,

Currently, there aren't any pages in the docs connecting the assets in the feed to any token requests.

BTC is referring to Bitcoin, the native on the Bitcoin blockchain while WBTC (Wrapped Bitcoin) is a token on Ethereum that is backed 1 to 1 by Bitcoin. Tokens have "addresses" but a blockchain's native currency like BTC doesn't.

That said, this could make an interesting feature request on the Documentation Repo if this is something you would like to see there! 
https://github.com/smartcontractkit/documentation/issues

Let me know if that answers your question and I'll close this out.

**Comment by gzliudan** [comment]
It's better to add function which provides underlying asset address in oracle contract.

**Comment by ZakAyesh** [comment]
Gotcha, if you would like to make a feature request for that here (instead of this bug report) we can put it up for votes. Thanks!
