### ISSUE TITLE
[FEAT] VRFCoordinatorV2Interface: would be nice to have a pendingRequestExists function

### ISSUE THREAD

**Issue by aelmanaa** [smartcontractkit/chainlink#6246]
**Description**
The goal is to track if a pending request exists. As a workaround I implemented the following in my contract:

```solidity
    // check if pending requests Exist
    function pendingRequestExists() external view returns (bool) {
        (, bytes memory returnData) = address(COORDINATOR).staticcall(
            abi.encodeWithSignature('pendingRequestExists(uint64)', s_subscriptionId)
        );
        return abi.decode(returnData, (bool));
    }
```
Ideally, would have preferred to implement the following

```solidity
    // check if pending requests Exist
    function pendingRequestExists() external view returns (bool) {
        return COORDINATOR.pendingRequestExists(s_subscriptionId);
    }
```

**Motivation**
The workaround with the `staticcall` function works. However, since there is already an interface, it would be more convenient to directly call `pendingRequestExists`

**Justification**
More convenient than `staticcall`

**Comment by PatrickAlphaC** [comment]
Ooooh, this is cool!

Are you looking for this just on the mock contracts? Or are you thinking on the main one too? 

I'm not sure it would make sense to add this function to the main contract, as you'd need another data structure to keep track of them all, which costs extra gas. You could use an indexer on a front end to do stuff based on the number of pending transactions. I'm not sure it makes sense to have that easily queryable on-chain.

Thoughts?

**Comment by aelmanaa** [comment]
In fact, the purpose here is not to track requests. 

The purpose here is to have a function `pendingRequestExists`  in _VRFCoordinatorV2Interface_ (so the main interface) if it makes sense of course. this function is present in [VRFCoordinatorV2](https://github.com/smartcontractkit/chainlink/blob/6c21b9cf6665484d2055908f8f99c5c1e26e6fdc/contracts/src/v0.8/dev/VRFCoordinatorV2.sol#L837) so I wonder why it's not present in [VRFCoordinatorV2Interface](https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/interfaces/VRFCoordinatorV2Interface.sol)

Actually, I had this idea when checking the [subscription manager contract example](https://docs.chain.link/docs/chainlink-vrf/example-contracts/#subscription-manager-contract). This contract is also a subscription owner so it calls the `COORDINATOR` to `addConsumer` , `removeConsumer` ,  `topUpSubscription` & `cancelSubscription`.
The problem with `cancelSubscription` is that you might probably want to check that there are no pending VRF requests before calling it.  The only way I was able to do it is via 
`address(COORDINATOR).staticcall(abi.encodeWithSignature('pendingRequestExists(uint64)', s_subscriptionId));`
while it would have been easier to leverage the interface `COORDINATOR.pendingRequestExists(s_subscriptionId);`

what do you think?

**Comment by PatrickAlphaC** [comment]
Ahh. Yes I love this suggestion. Will add it!

**Comment by makramkd** [comment]
Fixed in https://github.com/smartcontractkit/chainlink/pull/6290. Closing, thanks for the report @aelmanaa !
