### ISSUE TITLE
I followed this YY video: https://youtu.be/ZB3GLtQvgME?t=2003 but cannot 'chainlink node

### ISSUE THREAD

**Issue by johnnybegoode77** [smartcontractkit/chainlink#6273]
I followed this YY video: https://youtu.be/ZB3GLtQvgME?t=2003 but cannot 'chainlink node start'

Running 'chainlink help' is fine. Installation is Ok. Everything before the video checks out.

Need help with 'chainlink node start' Error:

```
`Jons-MacBook-Pro:.environments jon$ chainlink node start`
`2022-03-20T20:17:16.999-0700 [INFO]  Starting Chainlink Node 1.1.1 at commit `
`4dba946389cbf063ce374eb832007c3367abe3dc`
`SHA=4dba946389cbf063ce374eb832007c3367abe3dc Version=1.1.1`
`logger=1.1.1@4dba946.RunNode`
`2022-03-20T20:17:17.004-0700 [ERROR] Cannot boot Chainlink: opening db: failed to`
`open db: failed to connect to 'host=/private/tmp user=jon database=': server `
`error (FATAL: unrecognized configuration parameter "?application_name" (SQLSTATE `
`42704))                                  err=Cannot boot Chainlink: opening db: `
`failed to open db: failed to connect to 'host=/private/tmp user=jon `
`database=': server error (FATAL: unrecognized configuration parameter "? `
`application_name" (SQLSTATE 42704)) errVerbose=opening db: failed to open db: failed `
`to connect to 'host=/private/tmp user=jon database=': server error (FATAL: `
`unrecognized configuration parameter "?application_name" (SQLSTATE 42704))`
`Cannot boot Chainlink`
`github.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode`
`/Users/jon/chainlink/core/cmd/local_client.go:52`
`github.com/urfave/cli.HandleAction`
`/Users/jon/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524`
`github.com/urfave/cli.Command.Run`
`/Users/jon/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173`
`github.com/urfave/cli.(*App).RunAsSubcommand`
`/Users/jon/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405`
`github.com/urfave/cli.Command.startApp`
`/Users/jon/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372`
`github.com/urfave/cli.Command.Run`
`/Users/jon/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102`
`github.com/urfave/cli.(*App).Run`
`/Users/jon/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277`
`main.Run`
`/Users/jon/chainlink/core/main.go:25`
`main.main.func1`
`/Users/jon/chainlink/core/main.go:18`
`github.com/smartcontractkit/chainlink/core/recovery.ReportPanics`
`/Users/jon/chainlink/core/recovery/recover.go:17`
`main.main`
`/Users/jon/chainlink/core/main.go:17`
`runtime.main`
`/usr/local/go/src/runtime/proc.go:255`
`runtime.goexit`
`/usr/local/go/src/runtime/asm_amd64.s:1581 logger=1.1.1@4dba946 `
`Cannot boot Chainlink: opening db: failed to open db: failed to connect to `
`host=/private/tmp user=jon database=': server error (FATAL: unrecognized `
`configuration parameter "?application_name" (SQLSTATE 42704))`
`Jons-MacBook-Pro:.environments jon$ `
```

Thank you!

This is the .env

```
`ETH_URL=wss://kovan.infura.io/ws/v3/fc5cd704c8d44cf3ac09d16d13687ab2`
`FEATURE_EXTERNAL_INITIATORS=true`
`LOG_LEVEL=debug`
`ETH_CHAIN_ID=42`
`MIN_OUTGOING_CONFIRMATIONS=2`
`LINK_CONTRACT_ADDRESS=`
`CHAINLINK_TLS_PORT=0`
`SECURE_COOKIES=false`
`ALLOW_ORIGINS=*`
`DATABASE_URL=postgresql://localhost:5432/kovan_demo?sslmode=disable`
`DATABASE_TIMEOUT=0`
`FEATURE_FLUX_MONITOR=true`
`MINIMUM_CONTRACT_PAYMENT=0`
`CHAINLINK_DEV=true`
```

This is what happened if I use Docker: 
```
`failed to open db: failed to connect to host=localhost user=root database=kovan_demo: dial error (dial tcp [::1]:5432: connect: cannot assign requested address)`
```

```
`Jons-MacBook-Pro:.environments jon$ docker run -p 6688:6688 -v `
`~/.chainlink-kovan:/chainlink -it --env-file=.env `
`smartcontract/chainlink:1.1.1 local n`
`2022-03-21T21:48:44.372Z [DEBUG] Initializing API credentials    `                   
`cmd/client.go:636       file=/root/.chainlink/apicredentials `
`2022-03-21T21:48:44.373Z [INFO]  Starting Chainlink Node 1.1.1 at `
`commit 11788e23888b2d60554720faa237dabc62b1b8e7 `
`cmd/local_client.go:170 `
`SHA=11788e23888b2d60554720faa237dabc62b1b8e7 Version=1.1.1 `
`logger=RunNode `
`2022-03-21T21:48:44.373Z [WARN]  Chainlink is running in `
`DEVELOPMENT mode. This is a security risk if enabled in `
`production. cmd/local_client.go:173 logger=RunNode `
`opening db: failed to open db: failed to connect to `
`host=localhost user=root database=kovan_demo': dial error (dial `
`tcp [::1]:5432: connect: cannot assign requested address)`
`Jons-MacBook-Pro:.environments jon$ `
```

**Comment by PatrickAlphaC** [comment]
Going to close this for now, but feel free to follow up with questions. 

It looks like your database isn't connecting all the way. Are you able to connect via `psql` from the command line? 

```
postgresql://localhost:5432/kovan_demo?sslmode=disabl
```
^ Something might be wrong here.

**Comment by PatrickAlphaC** [comment]
Try installing `psql` and then connecting to your database with `psql postgresql://localhost:5432/kovan_demo?sslmode=disable`

**Comment by johnnybegoode77** [comment]
Yes I could.
I installed everything as in the video and they all checked out.

```
Jons-MacBook-Pro:environments jon$ psql postgresql://localhost:5432/kovan_demo?sslmode=disable
psql (14.2)
Type "help" for help.

kovan_demo=# 
```

**Comment by johnnybegoode77** [comment]
`Jons-MacBook-Pro:~ jon$ psql -V
psql (PostgreSQL) 14.2
Jons-MacBook-Pro:~ jon$ postgres -V
postgres (PostgreSQL) 14.2
Jons-MacBook-Pro:~ jon$ go version
go version go1.17.7 darwin/amd64
Jons-MacBook-Pro:~ jon$ yarn -v
1.22.17
Jons-MacBook-Pro:~ jon$ node -v
v16.13.2
Jons-MacBook-Pro:~ jon$ Python --version
Python 2.7.16
Jons-MacBook-Pro:~ jon$ npm -v
8.1.2
Jons-MacBook-Pro:~ jon$ nvm -v
0.39.1
Jons-MacBook-Pro:~ jon$ chainlink help
NAME:
   chainlink - CLI for Chainlink

USAGE:
   chainlink [global options] command [command options] [arguments...]

VERSION:
   1.1.1@4dba946389cbf063ce374eb832007c3367abe3dc

COMMANDS:
   admin           Commands for remotely taking admin related actions
   attempts, txas  Commands for managing Ethereum Transaction Attempts
   blocks          Commands for managing blocks
   bridges         Commands for Bridges communicating with External Adapters
   config          Commands for the node's configuration
   jobs            Commands for managing Jobs
   keys            Commands for managing various types of keys used by the Chainlink node
   node, local     Commands for admin actions that must be run locally
   txs             Commands for handling Ethereum transactions
   chains          Commands for handling chain configuration
   nodes           Commands for handling node configuration
   help, h         Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --json, -j     json output as opposed to table
   --help, -h     show help
   --version, -v  print the version
Jons-MacBook-Pro:~ jon$ 
`

**Comment by PatrickAlphaC** [comment]
Hmmm... it's saying `FATAL: unrecognized configuration parameter "?application_name"`

i wonder... do you have a question mark or something somewhere?

**Comment by johnnybegoode77** [comment]
Yes, I had tried removing the question mark. The error message is the same.
I had also tried creating a user and password and adding the user and password.
I had also tried running with Docker.

**Comment by pappas999** [comment]
hi @johnnybegoode77 what version of the node software are you running? and did you build from source or not? I can't replicate your issue, so just trying to get a sense of the environment

**Comment by johnnybegoode77** [comment]
node -v
v16.13.2

Hi, what do you mean by "build from source or not"?
Thank you!
