### ISSUE TITLE
[DEVEL] Warning from constructor visibility "public"

### ISSUE THREAD

**Issue by kwizzn** [smartcontractkit/chainlink#6278]
**Description**
I'm using the `VRFCoordinatorMock` in my project like so:
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@chainlink/contracts/src/v0.8/mocks/VRFCoordinatorMock.sol";
```

When I build, I get this compilation warning:
```
    Warning: Visibility for constructor is ignored. If you want the contract to be non-deployable, making it "abstract" is sufficient.
  --> @chainlink/contracts/src/v0.8/mocks/VRFCoordinatorMock.sol:12:3:
   |
12 |   constructor(address linkAddress) public {
   |   ^ (Relevant source part starts here and spans across multiple lines).
```

This is because the `public` visibility has no effect.

I would like to contribute a PR that removes the visibility for this particular mock contract and potentially others. Is that ok?

**Your Environment**
MacOS with local Truffle v5.5.5 installation

**Basic Information**
- `@chainlink/contracts/src/v0.8/mocks/VRFCoordinatorMock.sol`

**Steps to Reproduce**
- Import `VRFCoordinatorMock` as `VRFCoordinatorMock.sol` in your `contracts/` directory
- Run `truffle compile`

**Additional Information**
n/a

**Comment by PatrickAlphaC** [comment]
This is great! Thanks for making this issue. 

Would love to see a PR that fixes this. Thank you so much!

**Comment by kwizzn** [comment]
Done: #6353

**Comment by rdotterer09** [comment]
Thanks
