### ISSUE TITLE
[SMRT] VRF for Arbitrum 

### ISSUE THREAD

**Issue by dalaocu** [smartcontractkit/chainlink#6280]
Hi,

I noticed that https://docs.chain.link/docs/vrf-contracts/ contains several addresses for testnets and other nets, but I cannot find Layer2 Arbitrum.
Is there an address missing in the docs, or is VRF not yet available on Arbitrum Mainnet?

**Comment by PatrickAlphaC** [comment]
Thanks for making this issue!

We are working on it :)

**Comment by cesarhuret** [comment]
Was VRF for Arbitrum implemented? It's not in the docs
