### ISSUE TITLE
[BUG]: setPublicChainlinkToken() doesn't work on Mumbai

### ISSUE THREAD

**Issue by aelmanaa** [smartcontractkit/chainlink#6300]
Hello,

Does the pointer return the correct token address in Mumbai?
https://github.com/smartcontractkit/chainlink/blob/429c2f035042ca63d50137b2c40bdd48985f7e32/contracts/src/v0.8/ChainlinkClient.sol#L228

I was able to reproduce this issue https://github.com/smartcontractkit/documentation/issues/514 : The user was not able to deploy the _APIConsumer_ example on _Mumbai_.  I see other users running on the same issue as well; [for instance](https://stackoverflow.com/questions/71270669/unable-to-deploy-smart-contract-to-polygon-gas-estimation-error-internal-json)

You can try it yourself:

- If you use `setPublicChainlinkToken();` in the `constructor()` --> Revert
- If you use `setChainlinkToken(0x326C977E6efc84E512bB9C30f76E30c160eD06FB);`` in the `constructor()` -->  Deployment successful 

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;

import "@chainlink/contracts/src/v0.8/ChainlinkClient.sol";

contract APIConsumerMumbai is ChainlinkClient {
    using Chainlink for Chainlink.Request;
  
    uint256 public volume;
    
    address private oracle;
    bytes32 private jobId;
    uint256 private fee;
    
    /**
     * Network: Mumbai
     * Oracle: 0xc8D925525CA8759812d0c299B90247917d4d4b7C (GET > uint256 Linriver)
     * Job ID: bbf0badad29d49dc887504bacfbb905b
     * Fee: 0.01 LINK
     */
    constructor() {
        //setPublicChainlinkToken();
        setChainlinkToken(0x326C977E6efc84E512bB9C30f76E30c160eD06FB);
        oracle = 0xc8D925525CA8759812d0c299B90247917d4d4b7C;
        jobId = "bbf0badad29d49dc887504bacfbb905b";
        fee = 0.01 * 10 ** 18; // (Varies by network and job)
    }
    
    /**
     * Create a Chainlink request to retrieve API response, find the target
     * data, then multiply by 1000000000000000000 (to remove decimal places from data).
     */
    function requestVolumeData() public returns (bytes32 requestId) 
    {
        Chainlink.Request memory request = buildChainlinkRequest(jobId, address(this), this.fulfill.selector);
        
        // Set the URL to perform the GET request on
        request.add("get", "https://min-api.cryptocompare.com/data/pricemultifull?fsyms=ETH&tsyms=USD");
        
        // Set the path to find the desired data in the API response, where the response format is:
        // {"RAW":
        //   {"ETH":
        //    {"USD":
        //     {
        //      "VOLUME24HOUR": xxx.xxx,
        //     }
        //    }
        //   }
        //  }
        // request.add("path", "RAW.ETH.USD.VOLUME24HOUR"); // Chainlink nodes prior to 1.0.0 support this format
        request.add("path", "RAW,ETH,USD,VOLUME24HOUR"); // Chainlink nodes 1.0.0 and later support this format
        
        // Multiply the result by 1000000000000000000 to remove decimals
        int timesAmount = 10**18;
        request.addInt("times", timesAmount);
        
        // Sends the request
        return sendChainlinkRequestTo(oracle, request, fee);
    }
    
    /**
     * Receive the response in the form of uint256
     */ 
    function fulfill(bytes32 _requestId, uint256 _volume) public recordChainlinkFulfillment(_requestId)
    {
        volume = _volume;
    }

    // function withdrawLink() external {} - Implement a withdraw function to avoid locking your LINK in the contract
}
```

**Comment by PatrickAlphaC** [comment]
Maybe we do an `if` statement? Like

```
if(link) {
setPublicChainlinkToken();
} else {
setPublicChainlinkToken(address);
}
```

or something?

**Comment by aelmanaa** [comment]
actually, the [API Reference](https://docs.chain.link/docs/chainlink-framework/#setpublicchainlinktoken) and the behavior should be aligned. In the docs, it is stated:

"This method will only set the LINK token address if the calling contract is on a public network." 

So even if we update our docs, it won't prevent users from using this method (since it is documented on the API reference page). A user can think that `setPublicChainlinkToken()` will properly work on any supported [public network](https://docs.chain.link/docs/link-token-contracts/).

Therefore:

- if we think that `setPublicChainlinkToken()` is too limited then indeed we can replace it in our docs and maybe even remove it from the API reference?
- If we think that `setPublicChainlinkToken()` must work on supported public networks (as stated in the docs) then the fact that it doesn't work on Mumbai and other public networks can be considered a bug and we should inform about it in the _API reference_ (detailing all the public networks on which it currently doesn't work). 

what do you think?

**Comment by chiarawilden** [comment]
Hey everyone, thanks for looking into this! Not sure what the best path forward is, but I wanted to add that I did indeed consult the API reference, as @aelmanaa mentioned, and was confused by it at the time. I definitely think updating it is a good idea.

**Comment by pappas999** [comment]
@aelmanaa I think if it can't be used for all public networks, then it should be removed and replaced

**Comment by aelmanaa** [comment]
ok fine. just reopened https://github.com/smartcontractkit/documentation/issues/514 . we will :

- replace `setPublicChainlinkToken()` by `setChainlinkToken(<link_address>)`in our docs
- remove `setPublicChainlinkToken()` from the API reference. We can put it back once it can be used in all public networks

**Comment by PatrickAlphaC** [comment]
@aelmanaa, yes, we should do this.
