### ISSUE TITLE
Keepers GetConfig function does not return flatFeeMicroLink

### ISSUE THREAD

**Issue by wentzeld** [smartcontractkit/chainlink#6470]
https://github.com/smartcontractkit/chainlink/blob/4c58e4fd6d1e23040e94bc03a4af90608033d81c/contracts/src/v0.7/KeeperRegistry.sol#L586

Keepers GetConfig function does not return flatFeeMicroLink in v1.1 and v1.2

**Comment by infiloop2** [comment]
in 1.1 there's a separate function getFlatFee 

in 1.2 all of the config is merged into 'getState' function
