### ISSUE TITLE
Will Chainlink's AggregatorV3Interface.sol work with an OpenZeppelin upgradable contract?

### ISSUE THREAD

**Issue by johnnybegoode77** [smartcontractkit/chainlink#6489]
**Description**
Will Chainlink's AggregatorV3Interface.sol work with an OpenZeppelin upgradable contract?
Do I place the
"priceFeed = AggregatorV3Interface(0x9326BFA02ADD2366b30bacB125260Af641031331);"
inside the "initializer{}"?

I would like the address "0x9326BFA02ADD2366b30bacB125260Af641031331"
to be upgradable in the next version of the smart contract.

Is there already a way to do so?

Thank you!

**Motivation** & **Justification**
I hope that it makes sense to want to "getLatestPrice()" within the smart contract of a new token.
Before deployment, there is no way of knowing the new token's address.
I would like to change the address using the OpenZeppelin upgradable contract under the UUPS proxy pattern.

**Additional Information**
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "./@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol";
import "./@openzeppelin/contracts- 
upgradeable/token/ERC20/extensions/ERC20BurnableUpgradeable.sol";
import "./@openzeppelin/contracts- 
upgradeable/token/ERC20/extensions/ERC20SnapshotUpgradeable.sol";
import "./@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol";
import "./@openzeppelin/contracts-upgradeable/security/PausableUpgradeable.sol";
import "./@openzeppelin/contracts-upgradeable/token/ERC20/extensions/draft- 
ERC20PermitUpgradeable.sol";
import "./@openzeppelin/contracts- 
upgradeable/token/ERC20/extensions/ERC20VotesUpgradeable.sol";
import "./@openzeppelin/contracts- 
upgradeable/token/ERC20/extensions/ERC20FlashMintUpgradeable.sol";
import "./@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
import "./@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";

import "@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol";

contract UpToken is Initializable, ERC20Upgradeable, ERC20BurnableUpgradeable, 
ERC20SnapshotUpgradeable, OwnableUpgradeable, PausableUpgradeable, 
ERC20PermitUpgradeable, ERC20VotesUpgradeable, ERC20FlashMintUpgradeable, 
UUPSUpgradeable {
/// @custom:oz-upgrades-unsafe-allow constructor
AggregatorV3Interface internal priceFeed;
constructor() initializer {

    priceFeed = AggregatorV3Interface(0x9326BFA02ADD2366b30bacB125260Af641031331); // Kovan Testnet
}

function initialize() initializer public {
    __ERC20_init("UpToken", "UPT");
    __ERC20Burnable_init();
    __ERC20Snapshot_init();
    __Ownable_init();
    __Pausable_init();
    __ERC20Permit_init("UpToken");
    __ERC20FlashMint_init();
    __UUPSUpgradeable_init();
}

function snapshot() public onlyOwner {
    _snapshot();
}

function pause() public onlyOwner {
    _pause();
}

function unpause() public onlyOwner {
    _unpause();
}

function mint(address to, uint256 amount) public onlyOwner {
    _mint(to, amount);
}

function _beforeTokenTransfer(address from, address to, uint256 amount)
    internal
    whenNotPaused
    override(ERC20Upgradeable, ERC20SnapshotUpgradeable)
{
    super._beforeTokenTransfer(from, to, amount);
}

function _authorizeUpgrade(address newImplementation)
    internal
    onlyOwner
    override
{}

// The following functions are overrides required by Solidity.

function _afterTokenTransfer(address from, address to, uint256 amount)
    internal
    override(ERC20Upgradeable, ERC20VotesUpgradeable)
{
    super._afterTokenTransfer(from, to, amount);
}

function _mint(address to, uint256 amount)
    internal
    override(ERC20Upgradeable, ERC20VotesUpgradeable)
{
    super._mint(to, amount);
}

function _burn(address account, uint256 amount)
    internal
    override(ERC20Upgradeable, ERC20VotesUpgradeable)
{
    super._burn(account, amount);
}

function getLatestPrice() public view returns (int) {
    (
        /*uint80 roundID*/,
        int price,
        /*uint startedAt*/,
        /*uint timeStamp*/,
        /*uint80 answeredInRound*/
    ) = priceFeed.latestRoundData();
    return price;
}

}
```

This is the error message:

```
    ~/upgradable5  npx hardhat test                                                               
 1 ✘  6s  


UpToken
1) deploys


0 passing (2s)
1 failing

1) UpToken
   deploys:
 Error: Contract `UpToken` is not upgrade safe

contracts/UpToken.sol:20: Contract `UpToken` has a constructor
Define an initializer instead
https://zpl.in/upgrades/error-001
  at assertUpgradeSafe (node_modules/@openzeppelin/upgrades- 
core/src/validate/query.ts:19:11)
  at deployImpl (node_modules/@openzeppelin/hardhat- 
upgrades/src/utils/deploy-impl.ts:102:20)
  at deployProxyImpl (node_modules/@openzeppelin/hardhat- 
upgrades/src/utils/deploy-impl.ts:76:10)
  at Proxy.deployProxy (node_modules/@openzeppelin/hardhat- 
upgrades/src/deploy-proxy.ts:42:28)
  at Context.<anonymous> (test/test.js:8:5)
```

**Comment by ZakAyesh** [comment]
You need to remove the `constructor` function, as an implementation contract should not have one. Your initialize function should then point take in an argument for the data feed address that you want to change. This way, when it's time to upgrade to a new feed you can pass it in as an initializer argument in hardhat. Then when you deploy the proxy, it calls initialize with the need feed address and completes the upgrade. 

Check out this video for more about proxy patterns in general:
https://youtu.be/bdXJmWajZRY

Let me know if that helps.

**Comment by johnnybegoode77** [comment]
> You need to remove the `constructor` function, as an implementation contract should not have one. Your initialize function should then point take in an argument for the data feed address that you want to change. This way, when it's time to upgrade to a new feed you can pass it in as an initializer argument in hardhat. Then when you deploy the proxy, it calls initialize with the need feed address and completes the upgrade.
> 
> Check out this video for more about proxy patterns in general: https://youtu.be/bdXJmWajZRY
> 
> Let me know if that helps.

Most of the code is generated using https://wizard.openzeppelin.com/.
I checked on all features and select the UUPS proxy pattern. There are no errors even with the constructor.
The errors are there after I added 

```
import "@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol";
...
AggregatorV3Interface internal priceFeed;
...
priceFeed = AggregatorV3Interface(0x9326BFA02ADD2366b30bacB125260Af641031331); // Kovan Testnet
...
function getLatestPrice() 
...
```

My question is mainly asking how to upgrade the "priceFeed address" on version 2 of the smart contract.

**`priceFeed = AggregatorV3Interface(0x9326BFA02ADD2366b30bacB125260Af641031331); // Kovan Testnet**

`
Is that possible or achievable?
Thank you!

**Comment by PatrickAlphaC** [comment]
Going to close this, we are tracking this issue here: https://github.com/smartcontractkit/chainlink/issues/4976

Yes it's possible to do, but you'd have to currently do the work manually yourself.

**Comment by johnnybegoode77** [comment]
> priceFeed = AggregatorV3Interface(0x9326BFA02ADD2366b30bacB125260Af641031331); // Kovan Testnet

Is there any example online to update 

`priceFeed = AggregatorV3Interface(0x9326BFA02ADD2366b30bacB125260Af641031331); // Kovan Testnet
`

on version 2 of the smart contract?

Thank you!
