### ISSUE TITLE
Sugg

### ISSUE THREAD

**Issue by JMP2590** [smartcontractkit/chainlink#6644]
string public constant override typeAndVersion = "KeeperRegistry 1.1.0";
```


__Originally posted by @JMP2590 in https://github.com/JMP2590/chainlink/pull/39#discussion_r876582031__

**Comment by Darrenic17** [comment]
Connect with our  team representatives to help resolve your issue and troubleshooting .
Connect here: direct.lc.chat/14158209/

Hours of Operation
24/7 (Ready to fix issues)

**Comment by PatrickAlphaC** [comment]
Not sure what this issue is, closing.
