### ISSUE TITLE
[FEAT] return user provided array in VRF V2 mock

### ISSUE THREAD

**Issue by cuckflong** [smartcontractkit/chainlink#6652]
**Description**
accept an additional array parameter in the `fullfillRandomWords` function in `VRFCoordinatorV2Mock.sol` which would be returned instead if `array.length != req.numWords`.

**Motivation**
Returning user specified array in mock will allow to force randomness outcome thus making test cases more consistent and efficient.

**Justification**
The current working alternative is to loop `fullfillRandomWords` until the expected outcome is reached in each test case

**Comment by pappas999** [comment]
thanks for raising @cuckflong . Sounds like a sensible request that would make testing easier. Will raise it with the team

**Comment by Darrenic17** [comment]
Connect with our  team representatives to help resolve your issue and troubleshooting .
Connect here: direct.lc.chat/14158209/

Hours of Operation
24/7 (Ready to fix issues)

**Comment by makramkd** [comment]
@cuckflong this issue should be resolved now. Closing. Thanks for the report!
