### ISSUE TITLE
[FEAT] chainlink/contracts/src/v0.8/tests/MockV3Aggregator.sol is not in npm package

### ISSUE THREAD

**Issue by fields93** [smartcontractkit/chainlink#6802]
**Description**
I want to import the MockV3Aggregator into one of my projects. However, although I can find it in your repository at the path "smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/tests/MockV3Aggregator.sol", the file does not appear in npm after installing "@chainlink/contracts" for the v0.8.

**Motivation**
I understand this file should be in npm, same as it is in github and previous versions of the MockV3Aggregator.

**Justification**
Github and npm files would be on the same page, as it is for previous versions of the MockV3Aggregator.

**Additional Information**
Screenshot of the package folder in which the MockV3Aggregator should be

![noMockV3Aggregator](https://user-images.githubusercontent.com/56961432/174071554-db5802a8-07d5-42a5-9fb3-6e7f37fd6fc0.png)

**Comment by PatrickAlphaC** [comment]
It's in v0.6 not 0.8.
