### ISSUE TITLE
Install failed - Makefile:49: *** insufficient number of arguments (2) to function 'foreach'

### ISSUE THREAD

**Issue by doctorx32** [smartcontractkit/chainlink#687]
At https://github.com/smartcontractkit/chainlink#install `make install` step it throws this error:

```
[3/4] Linking dependencies...
warning "request-promise > request-promise-core@1.1.1" has unmet peer dependency "request@^2.34".
warning " > request-promise@4.2.2" has unmet peer dependency "request@^2.34".
[4/4] Building fresh packages...
Done in 81.81s.
Makefile:49: *** insufficient number of arguments (2) to function 'foreach'.  Stop.
```

### System Information

- Network (Main net, Ropsten, etc.): Ropsten
- Ethereum client (Geth/Parity) and version: 
- Go version: 
- Host OS: Kubuntu 18.04 x64
- Commit (INFO line when starting the node): Starting Parity/v1.11.3-beta-a66e36b-20180605/x86_64-linux-gnu/rustc1.26.2

### Environment Variables

OLDPWD=/home/dmitry/go/src/github.com/smartcontractkit
LC_NAME=lv_LV.UTF-8
USER=dmitry
GOPATH=/home/dmitry/go
HOME=/home/dmitry

### Additional Information
Latest Git commit 94998ddcb5f593f9c5892cfd425a7a6b6ae75cd8. Interesting that I tried to revert Makefile where no changes in foreach function, but it still throws this error. By the way, problem is on 49 line, but foearch is on 50, so it seems changing Makefile doesn't helps for me at all

**Comment by dimroc** [comment]
Hi there @doctorx32, thanks for reporting this issue. Can you let us know if the issue on `master` has been fixed? Do note that the instructions now recommend running `make bootstrap` on your first go rather than `make install`.

**Comment by doctorx32** [comment]
Hi @dimroc , I executed `git pull` in the project, then `make bootrap` and installing completed successfully
