### ISSUE TITLE
[FEAT] Deploy Chainlink contracts to Sepolia testnet

### ISSUE THREAD

**Issue by willianpaixao** [smartcontractkit/chainlink#6919]
**Description**

To deploy the LINK contracts to the [Sepolia testnet](https://github.com/eth-clients/sepolia).

**Motivation**

At the moment Chainlink is deployed to [these](https://docs.chain.link/docs/link-token-contracts/#ethereum) networks.

**Justification**

The Sepolia testnet will soon to be the de facto testnet once Rinkeby and Ropsten are [decomissioned](https://blog.ethereum.org/2022/05/30/ropsten-merge-announcement/).

**Additional Information**

- [Ropsten, Rinkeby & Kiln Deprecation Announcement](https://blog.ethereum.org/2022/06/21/testnet-deprecation/)

**Comment by supportteam99** [comment]
Contact the Support team directly to correct the issue     https://direct.lc.chat/14269734/

**Comment by spenweb** [comment]
What would be involved in making this happen?

**Comment by willianpaixao** [comment]
This is already done by #7078 and can be closed.

Documentation reference: [docs.chain.link/chainlink-nodes/v1/node-config](https://docs.chain.link/chainlink-nodes/v1/node-config#ethereum-sepolia-11155111)
