### ISSUE TITLE
Improve output of `chainlink r $JOB_ID`

### ISSUE THREAD

**Issue by NavyAdmiral** [smartcontractkit/chainlink#705]
The story [#158677628](https://www.pivotaltracker.com/story/show/158677628) asked for improved `chainlink r $JOB_ID`. 
When I was about to begin figuring this out, I checked it on my system first and I received the following output:
![image](https://user-images.githubusercontent.com/40662484/47832555-8e652580-dd6c-11e8-97b3-b6621c052344.png)

```
./chainlink.exe r 0663ce984b96482abf88a586045845a4
╔ Runs
╬══════════════════════════════════╬═════════════╬══════════════════════╬═══════════╬════════╬═══════╬
║                ID                ║   STATUS    ║       CREATED        ║ COMPLETED ║ RESULT ║ ERROR ║
╬══════════════════════════════════╬═════════════╬══════════════════════╬═══════════╬════════╬═══════╬
║ 3ec389b45eee465faab07216191ea0ce ║ in_progress ║ 2018-11-01T04:13:50Z ║           ║ {}     ║       ║
╬══════════════════════════════════╬═════════════╬══════════════════════╬═══════════╬════════╬═══════╬
```

Is this considered resolved accidentally by some other PR? The output I see is different from the story specifications so I don't know how to proceed.

@se3000

**Comment by se3000** [comment]
@NavyAdmiral it looks like the story outlines the output of a job spec, not a run. We want a similar breakout for runs, but we'll drive that out the GUI first to filter down the most essential points that we want to display to users.
