### ISSUE TITLE
Contract code size exceeds 24576 bytes encountered when compiling and deploying VRCoordinatorV2 contract

### ISSUE THREAD

**Issue by niuxiaojie81** [smartcontractkit/chainlink#7050]
**Description**
Contract code size exceeds 24576 bytes encountered when compiling and deploying VRCoordinatorV2 contract

**Basic Information**
When I import the v0.8 version of the contract in remix and try to compile and deploy the VRCoordinatorV2 contract to the Ethereum testnet, the error Contract code size exceeds 24576 bytes is reported.
So I am curious how this contract is deployed to the Ethereum mainnet, please advise.

**Comment by PatrickAlphaC** [comment]
Sorry on the delay. 

Could you send the code that you used to test this? I'm not able to replicate your issue.
