### ISSUE TITLE
CL GUI bugs out on return from Runs list

### ISSUE THREAD

**Issue by mvdiscuser** [smartcontractkit/chainlink#709]
- Network (Main net, Ropsten, etc.): Ropsten
- Ethereum client (Geth/Parity) and version: EaaS
- Host OS: Linux Ubuntu 18.04
- Node: running on AWS, connected via SSL

After clicking "Show More" (see top image) on the "Job Spec Detail" page to see all previous job runs and then when I want to return to the "Job Spec Detail" page by clicking on the job ID on top (see bottom image) to return back, the UI bugs out and the whole page is left all white.

I'm able to reproduce it every single time and with all currently running jobs.

![bug](https://user-images.githubusercontent.com/44779368/48007913-df806b00-e118-11e8-9287-a64337680f77.jpg)

**Comment by mvdiscuser** [comment]
Alright, got it. Yeah, I see the story for it to be fixed on the golang side.

**Comment by whatsadebugger** [comment]
working on it
