### ISSUE TITLE
[NODE] JSONPARSE can't parse large uint256

### ISSUE THREAD

**Issue by jpiabrantes** [smartcontractkit/chainlink#7369]
**Description**
I made this issue because I can't re-open https://github.com/smartcontractkit/chainlink/issues/7334 that was closed but not fixed.

My node is running v1.8.0.

I am using JSONPARSE to retrieve the number that I received from an external adaptor and JSONPARSE returns the wrong number.
The right number is `1565616210741547008` the retrieved number is `1565616210741547000`.
![image](https://user-images.githubusercontent.com/2369107/188582071-b4fe19b1-c9a0-41bc-8f03-492b31e3b570.png)

I can imagine a few ways this bug can be breaking and harming dapps relying on chainlink oracles to return the right number.

**Comment by rgottleber** [comment]
Thank you for opening this issue, our engineering team is looking into it and should have a fix coming soon.

**Comment by jpiabrantes** [comment]
@rgottleber why close issues before they are fixed?

**Comment by rgottleber** [comment]
@jpiabrantes Thanks for flagging. Meant to only comment not comment and close

**Comment by pinebit** [comment]
The change https://github.com/smartcontractkit/chainlink/pull/7344 did not went to `1.8.x`.
@jpiabrantes you need to either wait for the next release (e.g. `1.9.0`) or use `develop` (not recommended).

**Comment by jpiabrantes** [comment]
@pinebit ok. Meanwhile any smart contract using chainlink to bridge assets or provide prices is vulnerable to getting hacked and lose all its assets.

**Comment by jpiabrantes** [comment]
@pinebit @rgottleber tried to run a node from the `develop` branch. All jobs are working but the job that uses `jsonparser` to parse a large uint. That one fails without giving an error. How can I debug this?

More info here: https://stackoverflow.com/questions/73733171/task-fails-with-no-way-to-debug

**Comment by CL-Andrew** [comment]
Hi @jpiabrantes, thank you for raising and testing this issue. 

We would like to direct you to participate in our Bug Bounty Program and continue conversation here: https://hackerone.com/chainlink, where issues of this nature are eligible for compensation.

We appreciate your contribution, thank you again for investigating and getting our attention on this. In the future we ask you please practice responsible private disclosure, as this is a public medium.

Kind Regards,
 Andrew

**Comment by jpiabrantes** [comment]
@CL-Andrew you're absolutely right please delete this issue.

I haven't discussed it with anyone outside the chainlink team.

I will submit to your bounty program (wasn't aware you had one).
