### ISSUE TITLE
[FEAT] Add auto-signing of CLA to a PR

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/chainlink#7616]
Like with the slither tool, when you submit a PR they have you auto sign a license agreement. It would be cool if we had something like that.

https://github.com/crytic/slither/pull/1411#issuecomment-1270262281

**Comment by StephenFluin** [comment]
We investigated a year ago and legal told us we don't need a CLA at this time. Contributions to our repositories are licensed under the MIT license.
