### ISSUE TITLE
[DEVEL] Pnpm packages install error

### ISSUE THREAD

**Issue by drseu55** [smartcontractkit/chainlink#7751]
**Description**
Hello. I cloned the repository, installed pnpm from official docs and run `pnpm install`.
Throws this error:

```
Lockfile is up to date, resolution step is skipped
Packages: +1467
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1467, reused 1465, downloaded 0, added 0, done
node_modules/.pnpm/secp256k1@3.7.1/node_modules/secp256k1: Running install script...
node_modules/.pnpm/postinstall-postinstall@2.1.0/node_modules/postinstall-postinstall: Running postinstall script...
node_modules/.pnpm/sha3@1.2.6/node_modules/sha3: Running install script...
ELIFECYCLE  Command failed.
```

I am assuming that it is related to my OS but I am not sure. Node-sha3 maintainer recommends all projects using sha3 library to switch to 2.x release. Link: https://github.com/phusion/node-sha3/issues/83

**Your Environment**
Fedora 36
Node 16.15.0
npm 8.5.5
pnpm 7.14.0

**Steps to Reproduce**
Clone the repository, change directory to contracts and run `pnpm install`.

**Comment by drseu55** [comment]
Thanks. Tests ran successfully with `yarn`.

**Comment by braddmiller** [comment]
Glad you were able to get this to run with yarn, an alternative that we'll post just for future reference would be to clean the repo with the command `git clean -dfx` and try using pnpm again.
