### ISSUE TITLE
[FAUC] Exodus wallet connected instead of metamask

### ISSUE THREAD

**Issue by tilipman** [smartcontractkit/chainlink#7905]
**Description**
When both exodus and metamask extensions are installed, exodus pops up when trying to connect Metamask wallet.

**Basic Information**
I have tried to use faucet as part of web3 course by Patricks web3 course. The instruction was to connect metamask to faucets. I, however, kept getting exodus to popup instead of metamask. I tried to find out why, and eventually discovered that it was because I had Exodus extension installed. I removed the extension, and the metamask wallet connected as it should. When i installed exodus extension again, the problem reappeared. 

**Steps to Reproduce**
I managed to replicate the problem on both Chrome and Brave browsers.

1. Have both Exodus and Metamask extensions installed on your browser
2. On https://faucets.chain.link/ click connect wallet
3. Click MetaMask
4. Exodus pops up instead of Metamask

**Additional Information**
<img width="1440" alt="Screenshot 2022-11-14 at 1 44 30 PM" src="https://user-images.githubusercontent.com/47461975/201640583-c831401d-75d6-42b7-b4f5-150554a419f4.png">

**Comment by QingyangKong** [comment]
Hi @tilipman, from the webpage, we cannot pick the correct provider because Exodus has `isMetaMask:true` property to pretend to be metamask. Exodus replaces Metamask as default injected provider and make it impossible for us to connect to metamask. 

The solution is to disable Exodus extension in Chrome and you can connect metamask successfully.

**Comment by tilipman** [comment]
Thanks for pointing out the mechanics of it. I've noticed the same behavior occurring  with the newly released Trust wallet extension. @QingyangKong
