### ISSUE TITLE
[NODE] Polygon oracle direct requests elapsed time of 1-10k blocks to confirm

### ISSUE THREAD

**Issue by mgladson** [smartcontractkit/chainlink#7908]
**Description**
Direct request node: ~1-10k block times on oracle request response time

The jobs which are handling all these requests are all of the format: `Get > Uint256`.

SLA breaking bug, where received requests can take some nodes up to 5hrs to respond to the requesting smart contract depending on the block count on Polygon Mainnet.

**Basic Information**

This issue has been unresolved from node version `v1.4.1` and onward, with `v1.4.1` experiencing high latency of 1-2k block times. 

Other DON operators running `v1.9.0` experience this high latency response time with 10k block times. Stable version being `1.1.1`.

Once operators whom were running `v1.4.1` and `v1.9.0` downgraded to `v.1.1.1` with the exact same `.env` and RPC node setup, 1-10k block times did not occur (0% over 24hr).

All node operators during our multiple 24hr delta's had the same RPC node settings for bor listed [here](https://docs.chain.link/docs/evm-performance-configuration/):
```
--rpc.gascap=0 --rpc.txfeecap=0
```

|Version | Blocks Elapsed request/received | (%) Total of all requests serviced |
| ------ | ------ | ------ |
|v1.9.0|9-11k +/- 1k |  >75% |
|v1.4.1| 1-2k +/- 0.5k | >75% |
|v1.1.1| 1-3 +/- 2 | ~100% |

Node version `1.9.0` and `1.4.1` data was taken during the same 24hr time delta.

Node version `1.9.0`: # of blocks elapsed over 24hrs [10k average] 
![10k](https://user-images.githubusercontent.com/99776898/201680361-4527912f-ff0b-4c04-8ec1-e0a30a6158fe.png)

Node version `1.4.1`: # of blocks elapsed over 24hrs [1k average] 
![1k](https://user-images.githubusercontent.com/99776898/201680692-3901143a-02bc-4377-a5f7-2eeb1c5b361d.png)

Node version `1.1.1` (same nodes as above, but downgraded versions): # of blocks elapsed over 24hrs [2-4 average]
![photo_2022-11-14_05-42-31](https://user-images.githubusercontent.com/99776898/201680811-e272ca11-0f5b-49ec-a2cb-095112baac6a.jpg)

- Network: Polygon Mainnet
- Blockchain Client: self hosted RPC's=0xpolygon/bor:0.2.16 & remote RPC cloud provider
- Go Version: `1.4.1-root`
- Operating System: `ubuntu-os-cloud/ubuntu-minimal-1804-lts`
- Commit: `73e70a9`
- Hosting Provider: GCP
- Startup Command: 
```
docker run --name link-main-node -d --restart unless-stopped \
            --log-driver json-file --log-opt max-size=1000m \
            --log-opt max-file=1 \
            --log-opt tag="{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}" \
            -p 6689:6689 \
            -v ${local.local_vars.locals.chainlink_dir}/.chainlink-${local.local_vars.locals.chainlink_network_name}:/chainlink \
            -it --env-file=${local.local_vars.locals.chainlink_child_dir}/.chainlink-${local.local_vars.locals.chainlink_network_name}/.env \
            smartcontract/chainlink:${local.local_vars.locals.chainlink_version} \
            local n -p /chainlink/.password -a /chainlink/.api
```

**Environment Variables**
```
ADVISORY_LOCK_CHECK_INTERVAL	1s
ADVISORY_LOCK_ID	1027321974924625846
ALLOW_ORIGINS	*
BLOCK_BACKFILL_DEPTH	10
BLOCK_HISTORY_ESTIMATOR_BLOCK_DELAY	0
BLOCK_HISTORY_ESTIMATOR_BLOCK_HISTORY_SIZE	0
BLOCK_HISTORY_ESTIMATOR_TRANSACTION_PERCENTILE	0
BRIDGE_RESPONSE_URL	
CHAINLINK_DEV	false
CHAINLINK_PORT	6688
CHAINLINK_TLS_HOST	
CHAINLINK_TLS_PORT	6689
CHAINLINK_TLS_REDIRECT	false
CHAIN_TYPE	
CLIENT_NODE_URL	
DATABASE_BACKUP_FREQUENCY	1h0m0s
DATABASE_BACKUP_MODE	none
DATABASE_BACKUP_ON_VERSION_UPGRADE	true
DATABASE_LOCKING_MODE	lease
DEFAULT_HTTP_LIMIT	32768
DEFAULT_HTTP_TIMEOUT	15s
ETH_CHAIN_ID	137
ETH_HTTP_URL	
ETH_SECONDARY_URLS	[]
ETH_URL	
EVM_RPC_ENABLED	true
EXPLORER_URL	
FEATURE_EXTERNAL_INITIATORS	false
FEATURE_OFFCHAIN_REPORTING	false
FLAGS_CONTRACT_ADDRESS	
FM_DEFAULT_TRANSACTION_QUEUE_DEPTH	1
GAS_ESTIMATOR_MODE	
INSECURE_FAST_SCRYPT	false
JOB_PIPELINE_REAPER_INTERVAL	1h0m0s
JOB_PIPELINE_REAPER_THRESHOLD	24h0m0s
JSON_CONSOLE	false
KEEPER_BASE_FEE_BUFFER_PERCENT	20
KEEPER_CHECK_UPKEEP_GAS_PRICE_FEATURE_ENABLED	false
KEEPER_DEFAULT_TRANSACTION_QUEUE_DEPTH	1
KEEPER_GAS_PRICE_BUFFER_PERCENT	20
KEEPER_GAS_TIP_CAP_BUFFER_PERCENT	20
KEEPER_MAXIMUM_GRACE_PERIOD	0
KEEPER_REGISTRY_CHECK_GAS_OVERHEAD	0
KEEPER_REGISTRY_PERFORM_GAS_OVERHEAD	0
KEEPER_REGISTRY_SYNC_UPKEEP_QUEUE_SIZE	0
KEEPER_TURN_FLAG_ENABLED	false
KEEPER_TURN_LOOK_BACK	1000
LEASE_LOCK_DURATION	10s
LEASE_LOCK_REFRESH_INTERVAL	1s
LINK_CONTRACT_ADDRESS	
LOG_FILE_DIR	/chainlink
LOG_FILE_MAX_AGE	0
LOG_FILE_MAX_BACKUPS	1
LOG_FILE_MAX_SIZE	1.00gb
LOG_SQL	false
OCR_DEFAULT_TRANSACTION_QUEUE_DEPTH	1
OCR_TRACE_LOGGING	false
P2PV2_ANNOUNCE_ADDRESSES	[]
P2PV2_BOOTSTRAPPERS	[]
P2PV2_DELTA_DIAL	15s
P2PV2_DELTA_RECONCILE	1m0s
P2PV2_LISTEN_ADDRESSES	[]
P2P_BOOTSTRAP_CHECK_INTERVAL	20s
P2P_BOOTSTRAP_PEERS	[]
P2P_DHT_LOOKUP_INTERVAL	10
P2P_INCOMING_MESSAGE_BUFFER_SIZE	10
P2P_LISTEN_IP	0.0.0.0
P2P_LISTEN_PORT	
P2P_NETWORKING_STACK	V1
P2P_NEW_STREAM_TIMEOUT	10s
P2P_OUTGOING_MESSAGE_BUFFER_SIZE	10
P2P_PEER_ID	
REAPER_EXPIRATION	240h0m0s
ROOT	/chainlink
SECURE_COOKIES	true
SESSION_TIMEOUT	15m0s
SHUTDOWN_GRACE_PERIOD	5s
TELEMETRY_INGRESS_LOGGING	false
TELEMETRY_INGRESS_SERVER_PUB_KEY	
TELEMETRY_INGRESS_URL	
TRIGGER_FALLBACK_DB_POLL_INTERVAL	30s
```

**Steps to Reproduce**
Run node version `1.4.1` or later, on Polygon Mainnet. 
Measure the block numbers between once the smart contract has requested data, and then again once the smart contract has received the oracle request data over a 24hr time delta.

**Additional Information**
The only log line that populates the log which is out of the ordinary is listed [here](https://github.com/smartcontractkit/chainlink/issues/7701).
We have confirmed that on fresh nodes which do not have the mailbox error has its runtime increased, once the runtime is long enough for the error to arise. The consequence of the error is long block responses.

**Comment by QingyangKong** [comment]
Hi @mgladson, thanks for raising this issue! I will talk with the engineering team about this issue.

**Comment by Tobias35** [comment]
it seems this issue is somehow connected with the mailbox issue. as soon as the mailbox error logs appear the node looses performance and has its block response going sky high. 
https://github.com/smartcontractkit/chainlink/issues/7701

**Comment by QingyangKong** [comment]
The engineering team is working on it and it will be fixed based on priority amongst their other fixes and enhancements.

**Comment by thebuidler** [comment]
Can confirm, we've had positive results running the patched version. Thanks @QingyangKong

**Comment by mgladson** [comment]
> The problem is fixed in this [PR](https://github.com/smartcontractkit/chainlink/pull/8029).

Thank you for the Chainlink team's hardwork on this. We can confirm, after ~6 weeks of putting that PR under load on Arbitrum, that the mailbox error has been resolved.

This was my first github issue with Chainlink, please let me know how I could have better communicated the technical issue and if Chainlink needed any more information/logs which we might have had that could have sped the resolution process up.
