### ISSUE TITLE
[SMRT] Chainlink DeFI whitelists seem to not be working

### ISSUE THREAD

**Issue by cryptoenron** [smartcontractkit/chainlink#8174]
**Description**
Chainlink DeFI whitelists seem to not be working properly as they are still not being used to monetize data feeds now that initial bootstrapping of most feeds is over.

**Basic Information**
Continuing to subsidize node operators gas costs instead of making developers choose between paying their fair share, joining Chainlink BUILD or finding someone else that provides lively price feeds to Ethereum Layer1 seems negligent. Chainlink has already established first mover advantage and bootstrapped an entire ecosystem. Not actively moving to monetize that infrastructure is leading to financial problems for node operators and the community at large. As token price relates to ecosystem security not taking every opportunity to increase revenue for node operators seems negligent. If the whitelist exists to monetize data feeds, well, then after over 3 and half years of loss leader market capture, it seems like its time to shit or get off the pot.

**Steps to Reproduce**
Have you seen the Twitter comments from both well respected devs and community about this? Devs are only too happy to freeride while laughing at LINK marines.
![image](https://user-images.githubusercontent.com/51174000/210156873-0920b43e-6eee-4317-8666-69d8abe09a0e.png)

**Comment by fitchmultz** [comment]
Completely agree. Why is Chainlink Labs refusing to monetize the services they are offering? Why are they hanging token holders out to dry? They continue to dump tokens to subsidize Node Ops and R&D. They should have a warchest of over $1 billion at this point. It's truly a shame.

**Comment by rgottleber** [comment]
Thank you for your feedback regarding the whitelisting of Chainlink Data Feeds. I have passed it along to the relevant teams. For the latest updates around Chainlink Economics 2.0, please refer to Sergey Nazarov’s [recent blog post](https://blog.chain.link/the-chainlink-network-in-2023/), which covers expanding the Chainlink Network monetization model.

As this is not a technical issue related to the code itself, I will be closing this PR. Any further feedback can be shared in the Chainlink Official Discord: https://discord.com/channels/592041321326182401/592041321787818015
