### ISSUE TITLE
[NODE] LOG_TO_DISK env var no longer documented.

### ISSUE THREAD

**Issue by WilsonBillkia** [smartcontractkit/chainlink#8183]
**Description**
The documentation no longer mentions LOG_TO_DISK at https://docs.chain.link/chainlink-nodes/v1/configuration
**Basic Information**
Should there still be an entry for this under the documentation? I use the disk logs for an integration with an open source syslog-ng based logging and monitoring on my nodes.
- Node version 1.1.1
- Operating System: Built from source (1.1.1) on Ubuntu Server 20.04

- **Environment Variables**
- LOG_TO_DISK=true

**Additional Information**
Proposing addition of entry under docs eg
LOG_TO_DISK - Defaults to Off. If set to true the node will write logs to the $ROOT directory

**Comment by jmank88** [comment]
Hi @WilsonBillkia :wave:
The `LOG_TO_DISK` environment variable was actually removed in  https://github.com/smartcontractkit/chainlink/releases/tag/v1.3.0
That release also introduced debug-level disk logging by default (see "Added disk rotating logs..."), which can be _disabled_ by setting `LOG_FILE_MAX_SIZE=0`.

**Comment by WilsonBillkia** [comment]
K, awesome thanks. yep 1.1.1 nodes are a year old now - release notes v helpful - I'll log STD_OUT to files when I upgrade to 1.3
