### ISSUE TITLE
[SMRT] The function PendingRequestExists in OCR2DRRegistry.sol seems not correct

### ISSUE THREAD

**Issue by EMOSAMA** [smartcontractkit/chainlink#8189]
**Description**
PendingRequestExists in OCR2DRRegistry.sol has bug.

**Basic Information**
https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/dev/ocr2dr/OCR2DRRegistry.sol
OCR2DRRegistry.sol::765

**Steps to Reproduce**
When there is no request exist, it returns true. 

**Additional Information**
I think should change "if (s_requestCommitments[requestId].don == address(0))" to "if (s_requestCommitments[requestId].don != address(0))"

**Comment by bolekk** [comment]
Fixed as of Jan 10th, thanks for reporting! Closing.
