### ISSUE TITLE
[NODE] Chainlink async bridge task returns HTTP Error 422

### ISSUE THREAD

**Issue by fedecastelli** [smartcontractkit/chainlink#8284]
**Description**
I have to integrate my Chainlink Bridge task with an asynchronous call. Looking at the official [documentation](https://docs.chain.link/chainlink-nodes/oracle-jobs/task-types/task_bridge), there's the parameter named async and I can set it to true to invoke it asynchronously.

I also found this [link](https://docs.chain.link/chainlink-nodes/external-adapters/developers/#asynchronous-callbacks) which explains how to create Asynchronous callbacks.

- Network: Mumbai
- Blockchain Client: alchemy
- Operating System: Ubuntu but I'm running it on Docker
- Hosting Provider: AWS
- Startup Command: `docker run -p 6688:6688 -v ~/.chainlink-mumbai:/chainlink -it -d --env-file=.env smartcontract/chainlink:1.11.0-root local n -p /chainlink/.password -a /chainlink/.api`

**Environment Variables**

I set the environment variable [BRIDGE_RESPONSE_URL](https://docs.chain.link/chainlink-nodes/v1/configuration#bridge_response_url) equals to my Chainlink Oracle address. Looking at the documentation, I must set when using async external adapters.

**Steps to Reproduce**
I created the following job step:

```
fetch        [type="bridge"
                 name="generate-hash"
                 requestData="{\\"id\\": $(jobSpec.externalJobID), \\"data\\": {\\"fileList\\": $(decode_cbor.fileList)}}"
                 async=true
                ]
```

If I start the job execution, I can see the async call to my bridge and it contains the responseURL equals to {BRIDGE_RESPONSE_URL}/v2/resume/{id}.

Once the process finishes, I call the responseURL using the PATCH http method with the following body:

```json
{
  "data": {
    "fileList": ["aaa...fff", "bbbb...vvvv"],
    "hashList": ["0x...", "0x..."]
  }
}
```
The error I get is 422 - Unprocessable Entity.

The logs I see on my node are these ones:

```
2023-01-17T21:49:01.538Z [DEBUG] PATCH /v2/resume/{jobID} web/router.go:535                body={"data":{"fileList":["aaa...fff","bbbb...vvvv"],"hashList":["0x...","0x..."]}} clientIP={client_ip} errors=Error #01: must provide only one of either 'value' or 'error' key
```

I think the documentation should be updated because it says I have to send the `data` parameter but no words about the `value` parameter.

**Comment by rgottleber** [comment]
Thanks for bringing this to our attention. We've opened an issue in the docs repo to look into this.
