### ISSUE TITLE
[SMRT] There is an issue in FunctionsBillingRegistry.sol. The Requester will always get their money "stolen" by the transmitter.

### ISSUE THREAD

**Issue by EMOSAMA** [smartcontractkit/chainlink#8537]
**Description**
According to the billing design in **[FunctionsBillingRegistry.sol]**，the requester will always pay more than the calculated totoalCost which produced by **[FunctionsBillingRegistry.sol::calculatePaymentAmount]**.

The design assums that **"the transmitter address will always be in the signers list"**, and allocate the **signer payment** to transmitter in advance. (refer to [FunctionsBillingRegistry.sol::calculatePaymentAmount]) . But according to the design of Chainlink Node , the signning address and transmitter address are different which means the transmitter address will never in the signers list. This fact causes the requester pay extra **signer payment** to transmitter, and lead the totalCost mismatch with actual payment. Additionally, the nodes in signers list is only a subset of all nodes, which means the node which represented by transmitter address may not be included. 

In conclusion, The totalCost calculation is **_(n * signnerPayment + gasPayment)_**, but the actual payment will be **_((n+1) * signerPayment + gasPayment)_**, the **_n_** is the size of signers list.

Currently, the **total signers payment** (or called reward) is default to 0 (refer to FunctionsBillingRegistry.sol::getRequrieFee). So, This issue may not be awared.

**Basic Information**
1. Code location is https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/dev/functions/FunctionsBillingRegistry.sol :467 and :481

2. And use this [Tx](https://mumbai.polygonscan.com/tx/0xd30f35635a4cfcbe596734d1f4b509aba42a55df618475e4f934ba1c05237d20) on Mumbai as example.

**Steps to Reproduce**
In the [Transmit Tx](https://mumbai.polygonscan.com/tx/0xd30f35635a4cfcbe596734d1f4b509aba42a55df618475e4f934ba1c05237d20) on Mumbai, the involoved signers' addresses is **["0x12024999d75B69E7edC04383889aB2ffbdc409E9"**, **"0x219D033aeB68213FC98FF28d613A48d10c337B9b"**, **"0xaD095D87F24a69D01f45681c1C6868c80FEC5703"**] and the transmitter address is **"0xf318d60885c95b3262fa70fbc6e912282eb2925b"** which is not in the signers list .

**Additional Information**
I notice that the **function** feature is preparing for publish, this issue may cause losses in Mainnet if it decides to start charge requesters.
Adpot [the payees design in the OCR-OffchainAggregator contract](https://github.com/smartcontractkit/libocr/blob/master/contract/OffchainAggregatorBilling.sol) to correct the billing part seems good. At least, I think it shouldn't be allowed to assign siger payment to transmitter address in advance.

**Comment by justinkaseman** [comment]
Hi @EMOSAMA. Thanks for opening this as an issue :pray: :pray:. I appreciate how much detail you added.

Indeed this bit of the logic was incorrect. I have opened a Pull Request to fix.

**Comment by justinkaseman** [comment]
Closing as completed. Feel free to re-open if further discussion is needed.
