### ISSUE TITLE
Empty bridge table & empty jobs table not consistent

### ISSUE THREAD

**Issue by NavyAdmiral** [smartcontractkit/chainlink#870]
![image](https://user-images.githubusercontent.com/40662484/50721769-e54fe980-1092-11e9-9521-dede6d59ae77.png)

vs

![image](https://user-images.githubusercontent.com/40662484/50721771-e97c0700-1092-11e9-983b-35a9c9b22acc.png)

Can tables get a redesign too?

**Comment by rupurt** [comment]
@NavyAdmiral 👍 

I've started a [branch](https://github.com/smartcontractkit/chainlink/tree/chores/generic-table-component) to start extracting a shared generic custom `<Table>` component that will have defaults + overrides for this kind of stuff. 

It should reduce the amount of boilerplate code we need for our tables.

**Comment by thoughtmerchant** [comment]
@NavyAdmiral We are currently in the process of improving the tables in Operator. You are currently critiquing the incomplete design which will change as we roll out the improved Operator UI in the next few weeks.
