### ISSUE TITLE
Documentation edit 

### ISSUE THREAD

**Issue by JesseAbram** [smartcontractkit/chainlink#878]
### System Information

- remix ide

When interacting with RopstenConsumer.sol. When I try to send it 10 linkcoin as directed to in the documentation [here](https://docs.chain.link/docs/fund-your-contract). My transactions fail because it runs out of [gas](https://ropsten.etherscan.io/tx/0x817cc504c45b831b1eb16a50011c3373658de085a5d3b69a79dc9765acff6646). 

Not a big issue, all I need to do is increase the gas price but considering the detailed nature of the documentation I thought you might want to update it to deal with that trouble shooting.

**Comment by JesseAbram** [comment]
I would be happy to write up a fix and email it to you if you so wish (I would create a PR but the documentation is not hosted on github)

**Comment by thodges-gh** [comment]
@JesseAbram Are you referring to Metamask not using the correct gas limit for a token transfer?

**Comment by thodges-gh** [comment]
I can put a callout note in the docs to ensure that the gas limit is updated. Is that what your fix is?

**Comment by JesseAbram** [comment]
ya, pretty much it wasn't an issue for me I just changed it manually. The documentation which was very detailed (great so far by the way) I thought it may be worthwhile to add it.

**Comment by thodges-gh** [comment]
Cool, thanks for letting us know. That screenshot needed to be updated anyway. Let me know if the added callout works for you, you'll just need to refresh the page.

**Comment by JesseAbram** [comment]
It looks great, hopefully it helps some people out 

cheers
