### ISSUE TITLE
[SMRT] Some Sepolia price feeds don't work

### ISSUE THREAD

**Issue by GitMark0** [smartcontractkit/chainlink#8905]
**Description**

Retrieving ETH/USD price via `AggregatorV3Interface` interface on Sepolia testnet results in an error.

**Steps to Reproduce**

1. Visit `https://docs.chain.link/data-feeds/using-data-feeds/#examine-the-sample-contract`.
2. Copy the `PriceConsumer` contract and replace the `AggregatorV3Interface` address with `0x694AA1769357215DE4FAC081bf1f309aDC325306` (Sepolia ETH/USD feed address, as it is stated in the docs here: https://docs.chain.link/data-feeds/price-feeds/addresses/#Sepolia%20Testnet).
3. Deploy the contract to Sepolia testnet and try to call the `getLatestPrice` function.

OR communicate with `AggregatorV3` directly via interface and call `latestRoundData`.

**Additional Information**

`AggregatorV3Interface` is imported from `@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol`.

**Comment by Inderdeep01** [comment]
Hey @GitMark0 , Can you please share the error or a screenshot. Because I deployed the ETH/USD price feed on Sepolia testnet and it works fine. It is deployed at address 0x976436F617290e687c159581056E42971b2e835a. Kindly share your code or screenshot.

Thanks

**Comment by Inderdeep01** [comment]
Please check your network from metamask. chances are that it might be some other network you have chosen. If that's not the case, share some more information

**Comment by rockyko** [comment]
I face the same problem, when I try to decompile the contracts in the address, the function in that address looks strange https://sepolia.etherscan.io/bytecode-decompiler?a=0x694AA1769357215DE4FAC081bf1f309aDC325306

**Comment by zeuslawyer** [comment]
@rockyko 
Can you please clarify what the problem is you face?  (I note the original post is almost 1 year old).

I followed [these instructions](https://docs.chain.link/data-feeds/using-data-feeds/#reading-data-feeds-onchain)

I updated the price feed from the BTC/USD provided in the Code Sample to `0x694AA1769357215DE4FAC081bf1f309aDC325306` which is ETH/USD on Sepolia as the original poster indicated.

I deployed to Sepolia using remix.

I called `getChainlinkDataFeedLatestAnswer()`

And got the value `397302360042` in return.

This appears to be WAI.

**Comment by Inderdeep01** [comment]
@rockyko , you do not need to do any decompilation in case you just want to deploy a smart contract and get the price feed. if there is something else you are trying to achieve, please state your objective. Thanks

**Comment by rockyko** [comment]
Hi @zeuslawyer @Inderdeep01 ,Thanks for coming back, I was trying to call the decimal function in AggregatorV3Interface . The reason why I can't call the function is I wasnt using a Injected Provider environment.

**Comment by zeuslawyer** [comment]
Will make this as closed for now @rockyko .  Please re-open if the issue presents, and please provide screenshots/video etc to helps us understand the nature of the error you're facing.

Thanks!

**Comment by zeuslawyer** [comment]
Will make this as closed for now @rockyko .  Please re-open if the issue presents, and please provide screenshots/video etc to helps us understand the nature of the error you're facing.

Thanks!
