### ISSUE TITLE
[NODE] <replace with issue title>em_tnwrruimmdstxjqjweaibbfxdagg6chttps://t.me/ChinapumpWXC/2745#Sweeptoken 是年度#BSC 上最好的模因创新硬币！

sweeptoken 于 2022 年 9 月推出，其特点是其透明的团队和超过 8000 名持有者的强大社区。

它不仅仅是一个简单的模因硬币，其主要目标是使 BSC 和奖励持有者的 nfts 民主化。

要了解多个实用程序，您可以查看我们在@BSCNews 上的最新文章：

https://www.bsc.news/post/sweeptoken-the-community-driven-meme-utility-token-on-bnb-chain

加入#sweeparmy！

主 TG : https://t.me/sweepproject
中文TG：https://t.me/SweepProjectCN

https://poocoin.app/tokens/0x09c704c1eb9245af48f058878e72129557a10f04

### ISSUE THREAD

**Issue by DXJ999empireZ** [smartcontractkit/chainlink#8930]
**Description**
[replace this line with a clear and concise description of the issue you are experiencing]

**Basic Information**
[replace this line with basic information about the issue you are experiencing, including but not limited to all relevant logs and any other relevant information, such as if you are using a Docker container to run the node, job specification, oracle contract address, transaction IDs, etc.]

- Network: [e.g. Ethereum Mainnet, Ropsten]
- Blockchain Client: [name and version of blockchain client e.g. Geth v1.9.6]
- Go Version: [e.g. v1.12]
- Operating System: [name and version of operating system running Chainlink node]
- Commit: [log INFO line when starting node]
- Hosting Provider: [e.g. AWS, GCP, self-hosted]
- Startup Command: [e.g. `docker run smartcontract/chainlink local n`]

**Environment Variables**
[replace this line with the output of the environment variables when running the node in debug mode]

**Steps to Reproduce**
[replace this line with detailed steps to reproduce the issue you are experiencing]

**Additional Information**
[replace this line with any additional information you would like to provide, such as screenshots illustrating the issue]

**Comment by zeuslawyer** [comment]
No issue
