### ISSUE TITLE
Handle error in loggerFunc

### ISSUE THREAD

**Issue by tclass** [smartcontractkit/chainlink#90]
should handle error like
```
buf, err := ioutil.ReadAll(c.Request.Body)
if err != nil {
     logger.Error(err.Error())
}

```
https://github.com/smartcontractkit/chainlink/blob/f14e1acbd1c88e547f9d7f896094351224616724/web/router.go#L43

**Comment by dimroc** [comment]
Want to do the honors with a PR or shall I?

**Comment by se3000** [comment]
@tclass thanks for bringing this to our attention.

Fixed here: https://github.com/smartcontractkit/chainlink/pull/93
