### ISSUE TITLE
Installation Error: multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by JimmyStavros** [smartcontractkit/chainlink#91]
Get the following error while trying to install on MacOS High Sierra 10.13.3
```
# github.com/smartcontractkit/chainlink/utils
go/src/github.com/smartcontractkit/chainlink/utils/utils.go:115:35: multiple-value uuid.NewV4() in single-value context
```

**Comment by dimroc** [comment]
Hi @JimmyStavros, seems we have a version discrepancy with a dependency. Can you try the following steps:

1. `brew install dep`
2. `cd $GOPATH/src/github.com/smartcontractkit/chainlink` (in your case `cd go/src/github.com/smartcontractkit/chainlink`
3.  `dep ensure`

This should install the correct version of `uuid`. Please let us know if it works for you and we'll update documentation.

**Comment by JimmyStavros** [comment]
Yep, that fixed it. Thanks!
