### ISSUE TITLE
Sign In Form Input & Auto Fill

### ISSUE THREAD

**Issue by NavyAdmiral** [smartcontractkit/chainlink#960]
Was taking a look at the recent changes and there's this cheese in the form w auto-fill enabled (chrome):
![image](https://user-images.githubusercontent.com/40662484/52311649-ac4ab380-2975-11e9-8809-7c0d7c8701d1.png)

I believe adding `InputLabelProps={{ shrink: true }}` for both inputs in https://github.com/smartcontractkit/chainlink/blob/master/gui/src/containers/SignIn.js#L98 and https://github.com/smartcontractkit/chainlink/blob/master/gui/src/containers/SignIn.js#L112 will fix the issue

cc @rupurt

**Comment by rupurt** [comment]
@NavyAdmiral what OS are you using? I don't see this in Chrome or FF on OS X

**Comment by NavyAdmiral** [comment]
That is chrome's auto-fill for passwords and it's on Windows. To reproduce it you have to open CL in a new tab. I'll get you a gif asap

**Comment by NavyAdmiral** [comment]
@rupurt 
https://i.imgur.com/jAokn4i.gif

**Comment by rupurt** [comment]
@NavyAdmiral cool. Time to fire up the VM

**Comment by NavyAdmiral** [comment]
@rupurt https://github.com/mui-org/material-ui/issues/718 goes back to 2015 😓

**Comment by steeply** [comment]
I have the same problem

**Comment by NavyAdmiral** [comment]
Closing as this is a browser issue https://github.com/mui-org/material-ui/issues/14427#issuecomment-502050518
