### ISSUE TITLE
Uppercase bridge name provides invalid navigation

### ISSUE THREAD

**Issue by NavyAdmiral** [smartcontractkit/chainlink#981]
1. Create a bridge with uppercase letters in it
2. Click the hyperlink to navigate to the details page
3. 🐛 🐞 🐛

**Comment by NavyAdmiral** [comment]
Yeah, not an issue if url's correct:
https://i.imgur.com/mqlykOF.gif

**Comment by thodges-gh** [comment]
I can't reproduce this when running the compiled binary built from master. Can you verify if this is just when running the front-end?

**Comment by thodges-gh** [comment]
@NavyAdmiral This should be resolved now with https://www.pivotaltracker.com/story/show/165893278.
