### ISSUE TITLE
HttpPost documentation is incomplete

### ISSUE THREAD

**Issue by coventry** [smartcontractkit/chainlink#986]
The only argument mentioned in the [docs for the `HttpPost` external adapter](https://docs.chain.link/docs/adapters#section-httppost) is the URL. It must take a `POST` body, as well.

**Comment by thodges-gh** [comment]
I think your page might be cached, and really old? This was updated on the docs site weeks ago.

![screenshot from 2019-02-16 08-12-00](https://user-images.githubusercontent.com/10747945/52900954-98e3e780-31c2-11e9-805d-32060965dfb0.png)

**Comment by se3000** [comment]
I believe this is resolved. Feel free to reopen if not.
